### ISSUE TITLE
Support for multiple vault secrets in the same generic K8s Secret key

### ISSUE THREAD

**Issue by wmgroot** [banzaicloud/bank-vaults#1001]
**Is your feature request related to a problem? Please describe.**
Using the vault-secrets mutating webhook, I'm unable to replace multiple secrets inside the same key, or replace secrets inside a larger string of text.

This would be useful for projects that expect config files embedded inside a single, such as AlertManager and ArgoCD. I would like to keep my secret values in Vault simple and segregated, so that I do not have to update the entire contents of my secret in Vault each time a single value changes.

**Describe the solution you'd like**
I would like the following example to function as expected, only the vault value is replaced. Multiple vault values are replaced successfully.

```
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argo-cd
  annotations:
    vault.security.banzaicloud.io/vault-addr: <omitted>
    vault.security.banzaicloud.io/vault-path: <omitted>
    vault.security.banzaicloud.io/vault-role: vault-secrets-webhook_vault-secrets-webhook
stringData:
  # this works
  # key: vault:secret/data/project/argocd/prod/notifications#SLACK_TOKEN#1

  # this does not
  notifiers.yaml: |
    slack:
      token: vault:secret/data/project/argocd/prod/notifications#SLACK_TOKEN#1
```

I believe this is the code that would need to be modified, and that docker registry credentials have some special handling that appear to be similar to what we would want for generic Secrets.
https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/secret.go#L31-L76

**Describe alternatives you've considered**
I can work around this today by placing the entire multi line text block into Vault as a single value.

**Comment by kschu91** [comment]
We are having the same issue and would love to see that coming. We thought about the following design for implementation:

1. Add a new annotation `vault.security.banzaicloud.io/inline: true`

2. In [func secretNeedsMutation](https://github.com/banzaicloud/bank-vaults/blob/e83a577ddc5fc36f1756d17d8ff63a8ad02438f3/cmd/vault-secrets-webhook/secret.go#L31-L76) add an additional check when the above annotation set to `true` and search for occurences of `vault:` in the whole value.

3. Add a third condition in the [foreach statement](https://github.com/banzaicloud/bank-vaults/blob/e83a577ddc5fc36f1756d17d8ff63a8ad02438f3/cmd/vault-secrets-webhook/secret.go#L76) which is then using a modified version of [mutateSecretData](https://github.com/banzaicloud/bank-vaults/blob/e83a577ddc5fc36f1756d17d8ff63a8ad02438f3/cmd/vault-secrets-webhook/secret.go#L150) (eg. mutateInlineSecretData) and search for all occurences with `vault:` **ending with `:endvault`** and replace those with the secret content.

This would allow you to do something like:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argo-cd
  annotations:
    vault.security.banzaicloud.io/vault-addr: <omitted>
    vault.security.banzaicloud.io/vault-path: <omitted>
    vault.security.banzaicloud.io/vault-role: vault-secrets-webhook_vault-secrets-webhook
    vault.security.banzaicloud.io/inline: true
stringData:
  # this works
  key: vault:secret/data/project/argocd/prod/notifications#SLACK_TOKEN#1

  # and this would work as well
  notifiers.yaml: |
    slack:
      token: vault:secret/data/project/argocd/prod/notifications#SLACK_TOKEN#1:endvault

  # also something like this would work
  addr: vault:secret/data/project/db#host#1:endvault:vault:secret/data/project/db#port#1:endvault
```

We are currently discussing if we can support you by implementing this, when the design fits your thoughts @bonifaido?
