### ISSUE TITLE
error initializing vault: error testing keystore before init: error getting data: error getting object for key 'vault-test': storage: object doesn't exist

### ISSUE THREAD

**Issue by shanehughes1990** [banzaicloud/bank-vaults#1009]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Using vault-operator helm chart, deploying the cr-gcp-hs-autounseal crd yaml results in bank-vaults error

"error initializing vault: error testing keystore before init: error getting data: error getting object for key 'vault-test': storage: object doesn't exist"

**Expected behaviour**:
Vault operator should operator init the vault cluster and push root token and unseal keys to gcp storage bucket and end up in a running state

**Steps to reproduce the bug**:
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm upgrade --install vault-operator banzaicloud-stable/vault-operator
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/rbac.yaml
edit the following to match your gcp infrastructure bucket, kms-key etc...
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 2
  image: vault:latest
  bankVaultsImage: banzaicloud/bank-vaults:1.3.0


  # unsealConfig:
  #   # In this case we are storing the root token and the unseal keys in Kubernetes secrets.
  #   kubernetes:
  #     secretNamespace: default
  # Describe where you would like to store the Vault unseal keys and root token
  # in GCS encrypted with KMS.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      preFlightChecks: true
    google:
      kmsKeyRing: "REDACTED"
      kmsCryptoKey: "REDACTED"
      kmsLocation: "REDACTED"
      kmsProject: "REDACTED"
      storageBucket: "REDACTED"


  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # A YAML representation of a final vault config file, this config represents
  # a HA config in Google Cloud.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      gcs:
        bucket: "REDACTED"
        ha_enabled: "true"
    seal:
      gcpckms:
        project: "REDACTED"
        region: "REDACTED"
        key_ring: "REDACTED"
        crypto_key: "REDACTED"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.default:8200
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h

  # If you are not using a Service Account to authenticate against GCP you can pass in an
  # GCP credentials refering to a Secret with the following configuration block. You have to
  # create the "gcp-sa" secret manually, it has to have a key called "service-account.json"
  # holding the configuration in the following format:
  # https://cloud.google.com/docs/authentication/getting-started
  credentialsConfig:
    env: GOOGLE_APPLICATION_CREDENTIALS
    path: /etc/gcp/service-account.json
    secretName: REDACTED
```
create a service account in gcp with Role/kms.admin Role/kms.encryptdecrypt and Role/Storage.admin, download the json file for that service account, rename json file to service-account.json

create a kubernetes secret with the json for that service account,
```
kubectl create secret generic gcp-credentials --from-file=service-account.json
```
Add the kubernetes secret for the gcp account as a volume in the crd yaml
```
  credentialsConfig:
    env: GOOGLE_APPLICATION_CREDENTIALS
    path: /etc/gcp/service-account.json
    secretName: gcp-credentials << name of kubernetes secret
```

then run commands 
```
kubectl apply -f location/of/cr-gcp-ha-autounseal.yaml
kubectl logs vault-0 bank-vaults
```

**Environment details**:
- kubectl version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
```
GKE
```
- bank-vaults version (e.g. 0.4.17):
```
1.3.0
```
- Install method (e.g. helm or static manifests):
helm release for operator and kubeconfig for crd file
- Logs from the misbehaving component (and any other relevant logs):
log from bank-vaults 
```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :9091
time="2020-06-09T12:40:04Z" level=info msg="initializing vault..."
time="2020-06-09T12:40:04Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
time="2020-06-09T12:40:04Z" level=info msg="initializing vault"
time="2020-06-09T12:40:04Z" level=fatal msg="error initializing vault: error testing keystore before init: error getting data: error getting object for key 'vault-test': storage: object doesn't exist"
```
/kind bug
