### ISSUE TITLE
Cannot connect to vault in namespace

### ISSUE THREAD

**Issue by mikeyGlitz** [banzaicloud/bank-vaults#1024]
I have two manifests: 1 which sets up cluster roles, and one which sets up the vault:

`rbac.yaml`

```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: keycloak
  namespace: keycloak
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: keycloak
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: keycloak
roleRef:
  kind: Role
  name: vault-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: keycloak
```

`cr.yaml`

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: keycloak
spec:
  size: 1
  image: vault:1.4.2
  bankVaultsImage: banzaicloud/bank-vaults:latest

  # Common annotations for all created resources
  annotations:
    common/annotation: "true"

  # Vault Pods , Services and TLS Secret annotations
  vaultAnnotations:
    type/instance: "vault"

  # Vault Configurer Pods and Services annotations
  vaultConfigurerAnnotations:
    type/instance: "vaultconfigurer"

  # Vault Pods , Services and TLS Secret labels
  vaultLabels:
    example.com/log-format: "json"

  # Vault Configurer Pods and Services labels
  vaultConfigurerLabels:
    example.com/log-format: "string"

  # Support for nodeAffinity Rules
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key : "node-role.kubernetes.io/your_role"
  #         operator: In
  #         values: ["true"]

  # Support for pod nodeSelector rules to control which nodes can be chosen to run
  # the given pods
  # nodeSelector:
  #   "node-role.kubernetes.io/your_role": "true"

  # Support for node tolerations that work together with node taints to control
  # the pods that can like on a node
  # tolerations:
  # - effect: NoSchedule
  #   key: node-role.kubernetes.io/your_role
  #   operator: Equal
  #   value: "true"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: keycloak

  # Specify the Service's type where the Vault Service is exposed
  # Please note that some Ingress controllers like https://github.com/kubernetes/ingress-gce
  # forces you to expose your Service on a NodePort
  serviceType: ClusterIP

  # Specify existing secret contains TLS certificate (accepted secret type: kubernetes.io/tls)
  # If it is set, generating certificate will be disabled
  # existingTlsSecretName: selfsigned-cert-tls

  # Specify threshold for renewing certificates. Valid time units are "ns", "us", "ms", "s", "m", "h".
  # tlsExpiryThreshold: 168h

  # Request an Ingress controller with the default configuration
  # ingress:
  #   # Specify Ingress object annotations here, if TLS is enabled (which is by default)
  #   # the operator will add NGINX, Traefik and HAProxy Ingress compatible annotations
  #   # to support TLS backends
  #   annotations:
  #   # Override the default Ingress specification here
  #   # This follows the same format as the standard Kubernetes Ingress
  #   # See: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ingressspec-v1beta1-extensions
  #   spec: {}

  # Use local disk to store Vault file data, see config section.
  volumes:
    - name: vault-file
      persistentVolumeClaim:
        claimName: vault-file

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces:
    - "vault-infra"

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: keycloak

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      file:
        path: "${ .Env.VAULT_STORAGE_FILE }" # An example how Vault config environment interpolation can be used
    listener:
      tcp:
        address: "0.0.0.0:8200"
        # Uncommenting the following line and deleting tls_cert_file and tls_key_file disables TLS
        # tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_pki
        rules: path "pki/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook", "keycloak"]
            bound_service_account_namespaces: ["keycloak", "vault-infra"]
            policies: ["allow_secrets", "allow_pki"]
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

      - type: pki
        description: Vault PKI Backend
        config:
          default_lease_ttl: 168h
          max_lease_ttl: 720h
        configuration:
          config:
          - name: urls
            issuing_certificates: https://vault.keycloak:8200/v1/pki/ca
            crl_distribution_points: https://vault.keycloak:8200/v1/pki/crl
          root/generate:
          - name: internal
            common_name: vault.keycloak
          roles:
          - name: default
            allowed_domains: localhost,pod,svc,keycloak
            allow_subdomains: true
            generate_lease: true
            ttl: 1m

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    # startupSecrets:
    #   - type: kv
    #     path: secret/data/accounts/aws
    #     data:
    #       data:
    #         AWS_ACCESS_KEY_ID: secretId
    #         AWS_SECRET_ACCESS_KEY: s3cr3t
    #   - type: kv
    #     path: secret/data/dockerrepo
    #     data:
    #       data:
    #         DOCKER_REPO_USER: dockerrepouser
    #         DOCKER_REPO_PASSWORD: dockerrepopassword
    #   - type: kv
    #     path: secret/data/mysql
    #     data:
    #       data:
    #         MYSQL_ROOT_PASSWORD: s3cr3t
    #         MYSQL_PASSWORD: 3xtr3ms3cr3t

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
    - name: VAULT_STORAGE_FILE
      value: "/vault/file"

  # Marks presence of Istio, which influences things like port namings
  istioEnabled: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  # storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: vault-file
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   hostPath:
#     path: /vault/file
```

I get the following errors -- indicating that the health check to the vault is failing

```text
{"level":"info","ts":1592270008.5322635,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"keycloak","Request.Name":"vault"}
{"level":"error","ts":1592270011.6160483,"logger":"controller_vault.health","msg":"failed to query vault health","error":"Get "https://vault-0.keycloak:8200/v1/sys/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
```

Running a `vault kv put` operation gives the following error

```text
Error making API request.

URL: GET https://127.0.0.1:8200/v1/sys/internal/ui/mounts/secret/keycloak/application/credential
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "secret/keycloak/application/credential/"
```

The `vault-configurer` pod has the following logs

```text
time="2020-06-16T01:01:37Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
time="2020-06-16T01:01:37Z" level=info msg="applying config file : /config/vault-configurer/vault-config.yml"
time="2020-06-16T01:01:37Z" level=info msg="checking if vault is sealed..."
time="2020-06-16T01:01:37Z" level=info msg="watching directory for changes: /config/vault-configurer/"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:	export GIN_MODE=release
- using code:	gin.SetMode(gin.ReleaseMode)
[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :9091
time="2020-06-16T01:03:11Z" level=error msg="error checking if vault is sealed: error checking status: Get \"https://vault.keycloak:8200/v1/sys/seal-status\": dial tcp: i/o timeout, waiting 5s before trying again..."
time="2020-06-16T01:03:16Z" level=info msg="checking if vault is sealed..."
```

How can the connection issue be fixed? Is there something wrong with configuration?
