### ISSUE TITLE
Ability to have hostAliases and change the vault-addr through operator

### ISSUE THREAD

**Issue by isca0** [banzaicloud/bank-vaults#1049]
I'm using bank-vaults with the operator using custom certificates(that can't be regenerated) and would like to have the ability to change the hostAliases and vault-addr, in the way that is not needed to regenerate certificates with IP SAN 127.0.0.1 on it.

If you use a custom certificate without IP SAN 127.0.0.1 you will see bank_vault failing to reach vault API with the error:
```level=fatal msg="error initializing vault: error testing if vault is initialized: Get \"https://127.0.0.1:8200/v1/sys/init\": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs" ```

**Describe the solution you'd like**
Have ability to change the vault_addr used for bank_vaults and add hostAliases in cr. This way, it can use an address from the hostAliases, and as a result, will not be necessary to regenerate the certificate.
E.g:
```cat /etc/hosts
127.0.0.1    myCustomName
```
`VAULT_ADDR=myCustomName`

**Describe alternatives you've considered**
It would be nice if we have some annotation for the vault-addr and a valid hostAliases accepted in the Custom Resourse, like:
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  ....
  # Common annotations for all created resources
  annotations:
    common/annotation: "true"
    vault.security.banzaicloud.io/vault-addr: "https://myCustomName:8200"
  .....
  hostAliases:
   - ip: "127.0.0.1"
     hostnames:
       - "myCustomName"
```
