### ISSUE TITLE
[vault-operator] Cannot use AWS IAM Role to access s3 bucket

### ISSUE THREAD

**Issue by borisputerka** [banzaicloud/bank-vaults#1063]
**Describe the bug**:
Using IAM role ARN to auth against s3 is not working for me (using OIDC provider in eks). I am using `vault-operator` and when I follow https://banzaicloud.com/docs/bank-vaults/cloud-permissions/ vault is not able to access s3 bucket. But, if I use `envsConfig` and use aws credentials for IAM user created from the same IAM Policy its working fine(also had to put aws_secret and aws_key to s3 backend config) 

Here are my files I use for configuration:

`vault.tf`
```
resource "aws_s3_bucket" "bank_vaults_ct_test" {
  acl    = "private"
  bucket = "bank-vaults-test-eu"
  region = "eu-central-1"
}

resource "aws_iam_role" "vault_test_eu" {
  name = "vault-test-eu"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "${module.eks-test-eu.oidc_provider_arn}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity"
    }
  ]
}
EOF
}

resource "aws_iam_policy" "vault_test_eu" {
  name        = "VaultTestEuIAMPolicy"
  path        = "/"
  description = "Vault secrets policy"

  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kms:*"
            ],
            "Resource": [
                "KMS KEY ARN"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "${aws_s3_bucket.bank_vaults_ct_test.arn}/*"
            ]
        }
    ]
}
EOF
}
resource "aws_iam_role_policy_attachment" "vault_test_eu" {
  role       = aws_iam_role.vault_test_eu.name
  policy_arn = aws_iam_policy.vault_test_eu.arn
}
```
`vault.yaml`
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:1.4.2
  bankVaultsImage: banzaicloud/bank-vaults:latest
  unsealConfig:
    aws:
      kmsKeyId: "<KMS KEY ID>"
      kmsRegion: "eu-central-1"
      s3Bucket: "<BucketNAME>"
      s3Prefix: "vault-operator/"
      s3Region: "eu-central-1"
  serviceAccount: vault
  config:
    storage:
      s3:
        region: "eu-central-1"
        bucket: "<BucketNAME>"
        kms_key_id: "<KMS KEY ID>"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.vault:8200
    telemetry:
      statsd_address: localhost:9125
    ui: true
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: ["*"]
            policies: allow_secrets
            ttl: 1h
```

`rbac.yaml`
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault
  annotations:
    eks.amazonaws.com/role-arn: MY_ROLE_ARN

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
roleRef:
  kind: Role
  name: vault-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
```
As I said After using `envsConfig` with aws secrets credentials in vault.yaml and also adding those credentials into s3 backend config it works like a charm, but really I do not want to use those.

Can you guys see or help me what I did wrong or it is really not working atm?
Thank you.

LOGS
container: vault
```
Error initializing storage of type s3: unable to access bucket "<my BUCKET NAME>" in region "eu-central-1": AccessDenied: Access Denied
	status code: 403, request id: XXX host id: XXX
```

container: bank-vaults
```
time="2020-07-25T15:31:11Z" level=fatal msg="error initializing vault: error testing if vault is initialized: Get \"https://127.0.0.1:8200/v1/sys/init\": dial tcp 127.0.0.1:8200: connect: connection refused"
```

**Environment details**:
- Kubernetes version (1.16):
- Cloud-provider/provisioner (EKS):
- bank-vaults version (latest):
- Install method (manifests):
