### ISSUE TITLE
"bank-vaults.version" template seems to break some things

### ISSUE THREAD

**Issue by smoorsausje** [banzaicloud/bank-vaults#1065]
**Describe the bug**:
The "bank-vaults.version" template is used in both the vault and vault-secrets-webhook charts.
Therefore when using both charts as dependencies it will give unexpected behavior.

**Expected behaviour**:
Global templates should be unique.
See best practices: https://helm.sh/docs/chart_best_practices/templates/#names-of-defined-templates

**Steps to reproduce the bug**:
Create a parent chart with dependencies vault + vault-secrets-webhook:
```
apiVersion: v2
name: some-parent-chart
type: application
version: 1.0
appVersion: 1.0
dependencies:
  - name: vault
    alias: vault
    version: 1.3.10
    repository: http://kubernetes-charts.banzaicloud.com/branch/master
  - name: vault-secrets-webhook
    alias: vault-secrets-webhook
    version: 1.3.10
    repository: http://kubernetes-charts.banzaicloud.com/branch/master
```
`helm install --dry-run` produces the following images:
```
      - name: vault
        image: "vault:1.4.2"

      - name: vault-unsealer
        image: "banzaicloud/bank-vaults:1.4.2"

      - name: vault-configurer
        image: "banzaicloud/bank-vaults:1.4.2"
```
It looks like the `vault` image tag from vault-secrets-webhook values.yaml is set in the `bank-vaults` image tag.
I've also had the reverse happen, where the webhook would try to get the 'unsealer.image.tag' value.

Thank you in advance!

/kind bug
