### ISSUE TITLE
vaultLabels and vaultConfigurerLabels not applied to the StatefulSet itself

### ISSUE THREAD

**Issue by kanadaj** [banzaicloud/bank-vaults#1077]
**Describe the bug**:
Based on the documentation (https://banzaicloud.com/docs/bank-vaults/annotations-and-labels/), vaultLabels and vaultConfigurerLabels should be applied to both the StatefulSet and the Pods; however it appears that the label is only applied to the `StatefulSet.spec.template.metadata`, but not to `StatefulSet.metadata`. 

**Expected behaviour**:
Adding labels should also apply to the Statefulset itself, not just the template spec.

**Steps to reproduce the bug**:

1. Install Vault Operator 1.4.0
2. Add a new Vault cluster with default settings and an arbitrary vaultLabels entry
3. Check the vault StatefulSet's metadata

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): OKD 3.11
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare metal
- bank-vaults version (e.g. 0.4.17): 1.4.0
- Install method (e.g. helm or static manifests): manifests
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: default
spec:
  size: 1
  config:
    storage:
      file:
        path: /vault/file
    listener:
      tcp:
        address: '0.0.0.0:8200'
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: 'localhost:9125'
    ui: true
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9102'
  externalConfig:
    policies:
      - name: allow_secrets
        rules: >-
          path "secret/*" { capabilities = ["create", "read", "update",
          "delete", "list"] }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
  serviceType: ClusterIP
  vaultLabels:
    app: my-vault
  ingress:
    annotations: null
    spec: {}
  serviceAccount: vault
  unsealConfig:
    kubernetes:
      secretNamespace: default
  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
  image: 'vault:1.4.0'
  bankVaultsImage: 'banzaicloud/bank-vaults:latest'

```

/kind bug
