### ISSUE TITLE
[vault-secrets-webhook] ">>vault:" write functionality does not work as intended in secrets and CRDs

### ISSUE THREAD

**Issue by pcjun97** [banzaicloud/bank-vaults#1083]
**Describe the bug**:
In secrets and CRDs, `>>vault:` triggers GET request instead of POST/PUT.

**Expected behaviour**:
`>>vault:` should trigger POST/PUT request to the designated path.

**Steps to reproduce the bug**:
Create a secret that has data with `>>vault` prefix. (e.g. approle secret-id)

**Environment details**:
- vault-secrets-webhook version: 1.4.0
- Install method: helm
- Logs from the misbehaving component:
```
admission webhook error: mutate generic secret failed: failed to read secret from path: auth/approle/role/example/secret-id: Error making API request.

URL: GET https://vault.example.com/v1/auth/approle/role/example/secret-id?version=-1
Code: 405. Errors:

* 1 error occurred:
    * unsupported operation
```
- Resource definition that caused the issue:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example
  namespace: example
type: Opaque
stringData:
  secretId: '>>vault:auth/approle/role/example/secret-id#secret_id'
```

I believe this is caused by the `removePunctuation` function which removes `>` from the path thus preventing the webhook from determining the correct type of prefix.
https://github.com/banzaicloud/bank-vaults/blob/1969396c70bef261865d369f88320d509c928f40/cmd/vault-secrets-webhook/common.go#L26-L32
https://github.com/banzaicloud/bank-vaults/blob/1969396c70bef261865d369f88320d509c928f40/cmd/vault-secrets-webhook/secret.go#L137-L142
https://github.com/banzaicloud/bank-vaults/blob/1969396c70bef261865d369f88320d509c928f40/internal/injector/inejctor.go#L63-L68
