### ISSUE TITLE
probe errored: strconv.Atoi: parsing "vault": invalid syntax

### ISSUE THREAD

**Issue by gowthamsubbu** [banzaicloud/bank-vaults#114]
@bonifaido I ran the CRD for operator and Bank-vault with the latest image and found only one Vault pods got initialized. After digging, I found the below issue which is marking the container unhealthy

kubectl decribe pod vault-0

Events:
  Type     Reason                 Age                From                                   Message
  ----     ------                 ----               ----                                   -------
  Normal   SuccessfulMountVolume  24s                kubelet, ip-10-25-112-58.ec2.internal  MountVolume.SetUp succeeded for volume "vault-file"
  Normal   SuccessfulMountVolume  24s                kubelet, ip-10-25-112-58.ec2.internal  MountVolume.SetUp succeeded for volume "vault-config"
  Normal   SuccessfulMountVolume  24s                kubelet, ip-10-25-112-58.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-mkmb2"
  Normal   SuccessfulMountVolume  24s                kubelet, ip-10-25-112-58.ec2.internal  MountVolume.SetUp succeeded for volume "vault-tls"
  Normal   SuccessfulMountVolume  24s                kubelet, ip-10-25-112-58.ec2.internal  MountVolume.SetUp succeeded for volume "etcd-tls"
  Normal   Scheduled              24s                default-scheduler                      Successfully assigned vault-0 to ip-10-25-112-58.ec2.internal
  Normal   Pulled                 23s                kubelet, ip-10-25-112-58.ec2.internal  Container image "banzaicloud/bank-vaults:latest" already present on machine
  Normal   Started                23s                kubelet, ip-10-25-112-58.ec2.internal  Started container
  Normal   Created                23s                kubelet, ip-10-25-112-58.ec2.internal  Created container
  Normal   Created                22s (x2 over 24s)  kubelet, ip-10-25-112-58.ec2.internal  Created container
  Normal   Started                22s (x2 over 23s)  kubelet, ip-10-25-112-58.ec2.internal  Started container
  Normal   Pulled                 22s (x2 over 24s)  kubelet, ip-10-25-112-58.ec2.internal  Container image "vault:0.10.3" already present on machine
  Warning  Unhealthy              10s (x2 over 20s)  kubelet, ip-10-25-112-58.ec2.internal  Readiness probe errored: strconv.Atoi: parsing "vault": invalid syntax
  Warning  Unhealthy              8s (x2 over 18s)   kubelet, ip-10-25-112-58.ec2.internal  Liveness probe errored: strconv.Atoi: parsing "vault": invalid syntax

Below are the deployment and CRD for operator and Vault respectively.

Operator.yaml

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaults.vault.banzaicloud.com
spec:
  group: vault.banzaicloud.com
  names:
    kind: Vault
    listKind: VaultList
    plural: vaults
    singular: vault
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-operator
  template:
    metadata:
      labels:
        name: vault-operator
    spec:
      containers:
        - name: vault-operator
          image: banzaicloud/vault-operator:latest
          command:
          - vault-operator
          imagePullPolicy: IfNotPresent
          env:
          # OPERATOR_NAMESPACE defines the namespace where the operator watches
          # for CRD objects, if not defined all namespaces are whatched.
          - name: OPERATOR_NAMESPACE
            value: default
      serviceAccountName: vault-operator
```

cr-aws-etcd-ha.yaml

```yaml
piVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 2
  image: vault:0.10.3
  bankVaultsImage: banzaicloud/bank-vaults:latest
  imagePullPolicy: IfNotPresent
  
  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    aws:
      kmsKeyId: 937aa21e-0fdb-******
      kmsRegion: us-east-1
      s3Bucket: vault.k8s.eis-platformdevqa.cloud
      s3Region: us-east-1

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      etcd:
        address: https://etcd-cluster:2379
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.default:8200
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
    - name: allow_secrets
      rules: path "secret/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "auth/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
    auth:
    - type: aws
      roles:
      # Add roles for AWS instances or principals
      # See https://www.vaultproject.io/api/auth/aws/index.html#create-role
      - name: EKSWorker-Role
        bound_iam_principal_arn: arn:aws:iam::*****:role/RoleEksWorkers
        policies: allow_secrets
        period: 1h
    secrets:
    # This plugin stores arbitrary secrets within the configured physical storage for Vault.
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for
    # more information.
    - path: secret
      type: kv
      description: General secrets.
```

**Comment by bonifaido** [comment]
Just pushed a fix, for it, please pull the latest image again.

**Comment by bonifaido** [comment]
Fixed in: https://github.com/banzaicloud/bank-vaults/pull/115
@gowthamsubbu could you please retry?

**Comment by gowthamsubbu** [comment]
@bonifaido Getting this

 Warning  Unhealthy              1m               kubelet, ip-10-25-112-58.ec2.internal  Liveness probe failed: Get https://10.25.112.76:8200/v1/sys/init: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy              1m               kubelet, ip-10-25-112-58.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 429

**Comment by gowthamsubbu** [comment]
@bonifaido FYI, used latest image for both operator and Bank-Vault

**Comment by bonifaido** [comment]
If this is from the second pod than that is correct, because it shouldn't get any traffic, if the leader Vault crashes this health check would go to green and the second Vault instance will be marked as health by the probe.

**Comment by bonifaido** [comment]
Yes I just pushed a new latest image with a fix after you have opened up this issue.

**Comment by bonifaido** [comment]
So if you pull now you should see two Vault instances, one should be 2/2 and the other 1/2

**Comment by gowthamsubbu** [comment]
@bonifaido Thanks a lot. You can close this issue.

**Comment by bonifaido** [comment]
Happy to help @gowthamsubbu! Did it work?

**Comment by gowthamsubbu** [comment]
@bonifaido Yes, it did !

**Comment by gowthamsubbu** [comment]
@bonifaido Quick question, Is there a built in support for handling Prometheus metrics within the operator pattern ?

**Comment by bonifaido** [comment]
Not yet, there is https://github.com/banzaicloud/bank-vaults/issues/72 to make it happen, but we haven't had the time for it yet. Do you need this feature? It is very straightforward to implement, the following YAML part: https://github.com/banzaicloud/banzai-charts/blob/master/vault/templates/deployment.yaml#L111 has to be "operator-ized" (transformed to Go code).

**Comment by gowthamsubbu** [comment]
@bonifaido Thanks a lot. Since we decided to proceed with Bank-Vault for Vault secrets management, We are using EKS cluster to deploy Vault which has instance profile associated and it is a generic one for all EKS cluster. ( Instance profile cannot be modified, specific to Vault at this moment )

As you mentioned, instance profile should have access to S3 and KMS encrypt and decrypt. We cannot grant S3 and KMS access to generic instance profile, so we would like to know if there is any other mechanism supported by Bank-Vault other than using instance profile to store token and keys in S3 with KMS.

**Comment by bonifaido** [comment]
Hi @gowthamsubbu,
yes, this is certainly possible, we do this for GCP as well. All you have to do is to define a secret where your AWS credential file is stored and pass it as an environment variable as `AWS_SHARED_CREDENTIALS_FILE` as seen here: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/apis/vault/v1alpha1/types.go#L232

I have created an example of how to do this for AWS here: https://github.com/banzaicloud/bank-vaults/pull/117/files

About EKS, did you know that we are also implementing EKS support in the [Pipeline](https://github.com/banzaicloud/pipeline)? EKS cluster VPC, IAM, roles, node pools etc, creation is fully managed and automated there. It is available in the master branch already. If you have any questions about it please don't hesitate to write to us, our open up issues in the [Pipeline](https://github.com/banzaicloud/pipeline) repository.

**Comment by bonifaido** [comment]
@gowthamsubbu have you managed to try out the example?

**Comment by gowthamsubbu** [comment]
@bonifaido Thanks for the example. We are planning to test the Vault cluster today with the above example. Will let you know by EOD.

**Comment by gowthamsubbu** [comment]
@bonifaido We decided not to use credential config, since it involves storing plain secrets in the nodes which is not recommended by our architects, considering the security and privilege access escalation.

We will be using different node group for Vault which isolates the vault specific nodes from application nodes. Let us know your thoughts on our approach and feel free to recommend any alternate approach.

**Comment by raoofm** [comment]
@bonifaido we use [kube2iam](https://github.com/jtblin/kube2iam) and allow the instance to assume role

**Comment by bonifaido** [comment]
@gowthamsubbu separating node pools is the best idea I think if you are having any issues with that regarding Bank-Vaults don't hesitate to write it up here.

As @raoofm has pointed out [kube2iam](https://github.com/jtblin/kube2iam) is also a good idea if you are not using multiple node pools. Since the latest release 0.2.12 you can pass in annotations on the CRD Vault object so like this:

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:0.10.3
  bankVaultsImage: banzaicloud/bank-vaults:latest

  # Support for custom Vault (and sidecar) pod annotations
  annotations:
    prometheus.io/scrape: "true"
    iam.amazonaws.com/role: "role-arn..."
```
