### ISSUE TITLE
[webhook chart] AdmissionReviewVersions is unavailable in Kubernetes < 1.14

### ISSUE THREAD

**Issue by fdpeiter** [banzaicloud/bank-vaults#1149]
**Describe the bug**:
PR https://github.com/banzaicloud/bank-vaults/pull/1078 introduced AdmissionReviewVersions to the chart, but it is missing a validation related to the Kubernetes version, as this parameter was only introduced in [Kubernetes 1.14](https://github.com/kubernetes/kubernetes/commit/f7dff4725f8dc694a852e7fdbdde2c8a6dd5b7d4). Trying to apply the chart in versions lower than 1.14 generates the following error:
```
2020/10/14 17:56:40 Error generating helm template: Error generating manifests for chart banzaicloud-stable/vault-secrets-webhook: Failed to generate chart: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook, ValidationError(MutatingWebhookConfiguration.webhooks[1]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook]
```

**Expected behavior**:
The chart should validate the Kubernetes version and omit the field that isn't available in old Kubernetes versions.

**Steps to reproduce the bug**:
1. Create a Kubernetes cluster < 1.14.
2. Try to apply the chart using helm install/upgrade.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.13.12
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS
- bank-vaults version (e.g. 0.4.17): 1.6.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
helm logs:
```
2020/10/14 17:56:40 Error generating helm template: Error generating manifests for chart banzaicloud-stable/vault-secrets-webhook: Failed to generate chart: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook, ValidationError(MutatingWebhookConfiguration.webhooks[1]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook]
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
releaseName: vswh
namespace: vswh

replicaCount: 3

debug: false

certificate:
    generate: true
    server:
        tls:
            crt:
            key:
    ca:
        crt:
image:
  repository: banzaicloud/vault-secrets-webhook
  tag: 1.6.0
  pullPolicy: Always
  imagePullSecrets: []

service:
  name: vault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443

env:
  VAULT_ENV_IMAGE: banzaicloud/vault-env:1.3.1
  VAULT_ADDR: https://example.io
  VAULT_SKIP_VERIFY: true
  VAULT_PATH: xxx
  VAULT_IMAGE: vault:1.3.1

metrics:
  enabled: false
  port: 8443
  serviceMonitor:
    enabled: false
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

volumes: []

volumeMounts: []

podAnnotations: {}

labels: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

## Assign a PriorityClassName to pods if set
priorityClassName: ""

rbac:
  enabled: true
  psp:
    enabled: false

# This can cause issues when used with Helm, so it is not enabled by default
configMapMutation: false
configmapFailurePolicy: Ignore
podsFailurePolicy: Ignore
secretsFailurePolicy: Ignore
apiSideEffectValue: NoneOnDryRun
namespaceSelector:
  matchExpressions:
  - key: name
    operator: NotIn
    values:
    - kube-system
objectSelector: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 1
```

/kind bug
