### ISSUE TITLE
Allow Token Based Authentication

### ISSUE THREAD

**Issue by bradfordwagner** [banzaicloud/bank-vaults#1155]
I would like to be able to use a pre-provided token to acces the vault. We are using the mutating webhook to access but there is no way to use a provided token throughout the mutating webhook.

## Proposed Annotation
```
vault.security.banzaicloud.io/token-auth-mount: "token:vault-token"
```
Where token is:
```
    spec:
      volumes:
      - name: token
        secret:
          secretName: my-secret-vault-token
```
From a secret:
```
kind: Secret
type: Opaque
metadata:
  labels:
    owner: bwagner
  name: my-secret-vault-token
data:
  vault-token: {{ myBase64EncodedToken }}
```
or any such configuration that puts a file on the filesystem for example [azure-csi-driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure) or [flex-volume](https://github.com/Azure/kubernetes-keyvault-flexvol).

This token should be usable with `consul-template` or `vault-env`.

## Additional Benefits
- This will stop auto kubernetes auth of `vault-env`, and allow the following to trickle down
```
vault.security.banzaicloud.io/vault-agent: "true"
vault.security.banzaicloud.io/vault-agent-configmap: "my-configmap"
```
