### ISSUE TITLE
Vault fails to automatically join Raft when set as ha_storage

### ISSUE THREAD

**Issue by amoskyler** [banzaicloud/bank-vaults#1165]
**Describe the bug**:
Vault nodes appear to fail joining the raft consensus when being used as `ha_storage` but not as backend storage.

I receive this error from the vault API when attempting to authenticate: 
```Authentication failed: local node not active but active cluster node not found```

I believe it is due to the behaviors around `raft join`.

https://www.vaultproject.io/docs/commands/operator/raft#join

```
If raft is used for storage, the node must be joined before unsealing and the leader-api-addr argument must be provided. If raft is used for ha_storage, the node must be first unsealed before joining and the leader-api-addr must not be provided.
```

When raft is used for `ha_storage` but not `storage`, no leader-api-adder should be provided to `raft join`

**Expected behaviour**:
Vault nodes should all correctly join the raft consensus

**Steps to reproduce the bug**:
Configure a Vault spec with the following config:
```
  config:
    ui: true
    storage:
      s3:
        bucket: <bucket>
        region: <region>
    ha_storage:
      raft:
        path: "/vault/file"
```

**Additional context**:
I've attempted configuring the raftLeaderAddress to "self" but this didn't remediate.

**Environment details**:
- Kubernetes version (e.g. v1.18.9):
- Cloud-provider/provisioner AWS/KOPS
- bank-vaults version 1.7.0
- Install method Helm

/kind bug
