### ISSUE TITLE
Vault operator store secrets in plain text for AWS S3 KMS SSE

### ISSUE THREAD

**Issue by mkryva** [banzaicloud/bank-vaults#1189]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
After first setup, bank-vaults puts root token to s3 without encryption of KMS Key.

**Expected behaviour**:
Encrypted vault-root file with KMS

**Steps to reproduce the bug**:
Setup vault via configuration of CR below.
**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.18.8
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.8.0
- Install method (e.g. helm or static manifests): Operator via Helm chart, Vault via CR
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
  config:
    api_addr: http://vault.vault-operator:8200
    disable_clustering: false
    storage:
      s3:
        bucket: bucket
        region: eu-central-1
        max_parallel: 512
    ha_storage:
      dynamodb:
        region: eu-central-1
        table: bucket
        ha_enabled: "true"
    seal:
      awskms:
        kms_key_id: some-key-id
        region: eu-central-1
    default_lease_ttl: "1h"
    max_lease_ttl: "24h"
    plugin_directory: "/usr/local/lib/vault/plugins"
    ui: true
  unsealConfig:
    aws:
      kmsKeyId: some-key-id
      kmsRegion: eu-central-1
      s3Bucket: bucket
      s3Region: eu-central-1
      s3SSE: aws:kms
```

/kind bug
