### ISSUE TITLE
envsConfig not available in auditlog-exporter

### ISSUE THREAD

**Issue by containerpope** [banzaicloud/bank-vaults#1195]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
envsConfig environment variables are not available in auditlog-exporter sidecar.

**Expected behaviour**:
all envsConfig settings are available in the auditlog-exporter.

**Steps to reproduce the bug**:
Create a vault cluster with envConfig and audit logs enabled and exec in sidecar. Then print env and grep variables.

**Additional context**:
Add any other context about the problem here. The secrets are available in the bank-vaults sidecar.

**Environment details**:
- Kubernetes version: 1.18
- Cloud-provider/provisioner: Azure AKS
- bank-vaults version: ghcr.io/banzaicloud/bank-vaults:1.8.0
- Install method: helm
- Logs from the misbehaving component: - 

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

This is specified in the vault manifest:

```yaml
  envsConfig:
    - name: LOKI_USERNAME
      valueFrom:
        secretKeyRef:
          name: vault-secrets
          key: loki-username
    - name: LOKI_PASSWORD
      valueFrom:
        secretKeyRef:
          name: vault-secrets
          key: loki-password
    - name: LOKI_URL
      value: "https://loki:XXX"
    - name: FLUENTD_CONF
      value: "/fluentd/etc/fluent.conf"
```

The resulting audit exporter pod has no envs variables. 

```yaml
...
  - image: grafana/fluent-plugin-loki:master
    imagePullPolicy: IfNotPresent
    name: auditlog-exporter
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /vault/logs
      name: vault-auditlogs
    - mountPath: /fluentd/etc
      name: fluentd-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-bszcz
      readOnly: true
...
```

/kind bug
