### ISSUE TITLE
Key not found as soon as key-versioning was enable

### ISSUE THREAD

**Issue by phootip** [banzaicloud/bank-vaults#1204]
**Describe the bug**:
I was using `vault-env` to inject secrets as ENV just fine, but after I enable key-versioning on vault, the `vault-env` failed to inject secrets and giving me 
```
time="2020-12-04T10:57:10Z" level=warning msg="app-secrets/foo/bar: Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation." app=vault-env
time="2020-12-04T10:57:10Z" level=fatal msg="failed to inject secrets from vault: key 'PRIVATE_KEY' not found under path: app-secrets/foo/bar" app=vault-env
```

I have tried changing the url from `vault:app-secrets/foo/bar#PRIVATE_KEY` to `vault:app-secrets/data/foo/bar#PRIVATE_KEY` and `vault:app-secrets/metadata/foo/bar#PRIVATE_KEY` but it's giving me this error instead
```
time="2020-12-04T11:06:00Z" level=fatal msg="failed to inject secrets from vault: path not found: app-secrets/data/foo/bar" app=vault-env
```

I tried using `vault kv get app-secrets/foo/bar` and `curl -H "X-Vault-Token: {ROOT_TOKEN}" "localhost:8200/v1/app-secrets/data/foo/bar" and it worked fine

**Expected behaviour**:
Pods get secret as ENV

**Steps to reproduce the bug**:
Deploy vault with `1.5.5`, vault-webhook with `1.8.0` use injection as instructed to any deployments. Then enable key-versioning with `vault kv enable-versioning app-secrets/`

**Additional context**:
I think it might be version miss-match or some missing annotation, since I have tried everything and still can't fix it.
Here is my annotation
```
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://piggy.piggy.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-role: "fooo"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
```
I would really be appreciate if you could help, since I can't find a way to disable key-versioning and it causing a lot of problems, Thank you

**Environment details**:
- Helm3
- Kubernetes version (e.g. v1.10.2): v1.17.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.8.0
- Install method (e.g. helm or static manifests): helm install
- Logs from the misbehaving component (and any other relevant logs): already given
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: already given

/kind bug
