### ISSUE TITLE
can we get etcd tolerations

### ISSUE THREAD

**Issue by gespinoza22** [banzaicloud/bank-vaults#1235]
**Is your feature request related to a problem? Please describe.**
Looking to get etcd cluster pods running on a specific instancegroup which contain tolerations. However bankvault doesnt support setting tolerations on etcd pods, only on the vault pods are tolerations accepted.

**Describe the solution you'd like**
would like to do some like below on the cr yaml  in order to set tolerations on etcd pods. 

```
  etcdTolerations:
    - effect: NoSchedule
      key: key1
      operator: Equal
      value: "true"
```

**Describe alternatives you've considered**

**Additional context**
