### ISSUE TITLE
Garabage Collector deleted my vault instance

### ISSUE THREAD

**Issue by TomaszKlosinski** [banzaicloud/bank-vaults#1243]
**Describe the bug**:
After few weeks of normal operation today I've realised that my vault instance disappeared. I've checked the Kubernetes Audit trails and discovered that Garbage Collector has deleted it. I'm not sure if it's bank-vaults bug or Kubernetes bug. 

**Expected behaviour**:
I'd expect that vault instance is not getting deleted by Garabage Collection.

**Steps to reproduce the bug**:
I have no clue how to reproduce this. It just happened randomly after few weeks of operation.

**Environment details**:
- Kubernetes version: v1.18.8
- Cloud-provider/provisioner: on-prem with kubeadm
- bank-vaults version: vault-operator v1.3.5, secrets-webhook v1.3.9
- Install method:
```
helm upgrade --install --namespace=vault-operator vault-operator banzaicloud-stable/vault-operator --version 1.3.5 --wait
helm upgrade --install --namespace=vault-operator vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --values vault-secrets-webhook-values.yaml --version 1.3.9 --wait
```

- Logs from the misbehaving component (and any other relevant logs):

I've parsed the audit logs to be more readable:
https://pastebin.com/099tK0Dq

And here are the logs from the deleted vault instance:
https://pastebin.com/sRi0VCct

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

Definition of the Vault instance
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "${INSTANCE_NAME}"
spec:
  size: 1
  image: vault:1.4.3
  bankVaultsImage: banzaicloud/bank-vaults:latest

  # Vault Pods , Services and TLS Secret labels
  # Add extra label which nodeport service will use it for selector
  # vaultLabels:
  #  kube.digital/local-pod: "true"

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces: ${VAULT_ACCESS_NAMESPACES}

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: ${NAMESPACE}

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Custom TLS
  # existingTlsSecretName: ${INSTANCE_NAME}-custom-tls

  # A YAML representation of a final vault config file, this config represents
  # a backend config in S3.
  # https://www.vaultproject.io/docs/configuration/storage/mysql
  config:
    log_level: "Trace"

    storage:
      mysql:
        username: "${MYSQL_USER}"
        database: "${MYSQL_DB}"
        table: "${NAMESPACE}"
        password: "${MYSQL_VAULT_PW}"
        address: "${MYSQL_HOST}:3306"
        #ha_enabled: "true"
        plaintext_connection_allowed: "true"

    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
        #tls_disable: "true"

    api_addr: https://${INSTANCE_NAME}.${NAMESPACE}:8200

    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: readonly_secrets
        rules: |
          path "secret/*" {
            capabilities = ["read", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
(...)
            ttl: 1h

      - type: ldap
        description: LDAP directory authentication.
        options:
          listing_visibility: "unauth"
        config:
(...)
        groups:
          # Superuser group policies
          superusers:
            policies:
              - allow_secrets
          # Dev group policies
          developers:
            policies:
              - readonly_secrets

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
```

/kind bug
