### ISSUE TITLE
OIDC provider_config errors

### ISSUE THREAD

**Issue by TimJones** [banzaicloud/bank-vaults#1247]
**Describe the bug**:
Setting up OIDC with Google Suite as provider with the vault-operator gives an error.

```yaml
    externalConfig:
      auth:
        - type: oidc
          config:
            default_role: default
            oidc_client_id: ...snip...
            oidc_discovery_url: https://accounts.google.com
            provider_config:
              provider: gsuite
              fetch_groups: true
              fetch_user_info: false
              groups_recurse_max_depth: 5
              gsuite_admin_impersonate: ...snip...
              gsuite_service_account: /vault/google/service-account.json
          options:
            listing_visibility: unauth
          roles:
            - name: default
              role_type: oidc
              user_claim: sub
              groups_claim: groups
              policies: default
              ttl: 1h
```
Results in vault-configurer logging
```
time="2021-01-29T15:17:30Z" level=error msg="error configuring vault: error configuring auth methods for vault: error configuring oidc auth on path oidc for vault: error putting oidc auth config into vault: json: unsupported type: map[interface {}]interface {}"
```

Since the error was for an unknown type, I tried converting the `provider_config` into a JSON string (i.e. `provider_config: '{"provider":"gsuite",...}'`) and that resulted in vault-configurer logging:
```
time="2021-01-29T15:23:27Z" level=error msg="error configuring vault: error configuring auth methods for vault: error configuring oidc auth on path oidc for vault: error putting oidc auth config into vault: Error making API request.\n\nURL: PUT http://vault.vault-system:8200/v1/auth/oidc/config\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* error converting input {\"fetch_groups\":true,\"fetch_user_info\":true,\"groups_recurse_max_depth\":5,\"gsuite_admin_impersonate\":\"...snip...\",\"gsuite_service_account\":\"/vault/google/service-account.json\",\"provider\":\"gsuite\"} for field \"provider_config\": '' expected a map, got 'string'\n\n"
```
so I'm pretty sure it should just be a map as above.

**Expected behaviour**:
bank-vaults operator should write the provider configuration to the auth config endpoint.

**Steps to reproduce the bug**:
Set up a clean vault, apply above config.

**Environment details**:
- Kubernetes version: v1.18.9
- Cloud-provider/provisioner: EKS
- bank-vaults version: 1.10.0
- Install method: Helm

/kind bug
