### ISSUE TITLE
Pods randomly failing (failed to request new Vault token context deadline exceeded)

### ISSUE THREAD

**Issue by TomaszKlosinski** [banzaicloud/bank-vaults#1250]
**Describe the bug**:
After few weeks of normal operation, my pods started failing to connect to Vault. I'm getting randomly (every second deployment or so):
```
time="2021-02-02T09:15:33Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
time="2021-02-02T09:15:45Z" level=info msg="failed to request new Vault token context deadline exceeded"
time="2021-02-02T09:15:45Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
```

One potential reason is that we have much more users now than before, so maybe people running their apps in skaffold and testing deployments, are just DDoSing Vault with too many requests. That's my guess but I'm not sure how to verify this.

Maybe as a first step it would make sense to increase vault server log verbosity and increase the client timeout. How can I do that? I couldn't find it in the CR manifest examples or docs.

And is it possible to automatically restart vault-client init container when the connection hit timeout, so that it tries to connect until success?

**Expected behaviour**:
I'd expect that clients connects to vault every single time.

**Steps to reproduce the bug**:
I have no clue how to reproduce this. It just happened randomly after few weeks of operation.

**Environment details**:
- Kubernetes version: v1.18.8
- Cloud-provider/provisioner: on-prem with kubeadm
- bank-vaults version: vault-operator v1.3.5, secrets-webhook v1.3.9
- Install method:
```
helm upgrade --install --namespace=vault-operator vault-operator banzaicloud-stable/vault-operator --version 1.3.5 --wait
helm upgrade --install --namespace=vault-operator vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --values vault-secrets-webhook-values.yaml --version 1.3.9 --wait
```

- Logs from the misbehaving component (and any other relevant logs):

There are no errors in the logs.

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

Definition of the Vault instance
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "${INSTANCE_NAME}"
spec:
  size: 1
  image: vault:1.4.3
  bankVaultsImage: banzaicloud/bank-vaults:latest

  # Vault Pods , Services and TLS Secret labels
  # Add extra label which nodeport service will use it for selector
  # vaultLabels:
  #  kube.digital/local-pod: "true"

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces: ${VAULT_ACCESS_NAMESPACES}

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: ${NAMESPACE}

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Custom TLS
  # existingTlsSecretName: ${INSTANCE_NAME}-custom-tls

  # A YAML representation of a final vault config file, this config represents
  # a backend config in S3.
  # https://www.vaultproject.io/docs/configuration/storage/mysql
  config:
    log_level: "Trace"

    storage:
      mysql:
        username: "${MYSQL_USER}"
        database: "${MYSQL_DB}"
        table: "${NAMESPACE}"
        password: "${MYSQL_VAULT_PW}"
        address: "${MYSQL_HOST}:3306"
        #ha_enabled: "true"
        plaintext_connection_allowed: "true"

    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
        #tls_disable: "true"

    api_addr: https://${INSTANCE_NAME}.${NAMESPACE}:8200

    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: readonly_secrets
        rules: |
          path "secret/*" {
            capabilities = ["read", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
(...)
            ttl: 1h

      - type: ldap
        description: LDAP directory authentication.
        options:
          listing_visibility: "unauth"
        config:
(...)
        groups:
          # Superuser group policies
          superusers:
            policies:
              - allow_secrets
          # Dev group policies
          developers:
            policies:
              - readonly_secrets

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
```

/kind bug

**Comment by TomaszKlosinski** [comment]
I actually realised that the limits/requests are pretty low by default:
```
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
```

Is it possible to increase these values via CR manifest?
