### ISSUE TITLE
awskms template function should not be decoding the base64 blob

### ISSUE THREAD

**Issue by TimJones** [banzaicloud/bank-vaults#1253]
**Describe the bug**:
I've been trying to set up bank vaults backed by AWS KMS and it works great for unsealing, but the templating function *always* causes the `vault-configurer` pod to fail with the following error:

```
level=fatal msg="error parsing vault config file: While parsing config: yaml: invalid leading UTF-8 octet"
```

**Expected behaviour**:
That the vault-configurer pod can load the config, decrypt the ciphertext blob and configure the vault instance correctly.

**Additional context**:
It looks as if the ciphertext blob is being decoded from base64 before being passed into the AWK KMS function for decrypting.
https://github.com/banzaicloud/bank-vaults/blob/2a0b4ed263357bfe5c8256ad1af2e0841003603e/internal/configuration/template.go#L155-L159
but the AWS SDK specifies that the ciphertext blob is decoded by the SDK itself
https://github.com/aws/aws-sdk-go/blob/d87d92b4412739c6ef8917979e922fae98b7654c/service/kms/api.go#L8138-L8146

Slack discussions: 
 * https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1611941244028600
 * https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1612796687072800

**Environment details**:
- Kubernetes version: v1.18.9
- Cloud-provider/provisioner: EKS
- bank-vaults version: 1.10.0
- Install method: Helm chart
- Logs from the misbehaving component (and any other relevant logs): *See above*
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
externalConfig:
  secrets:
    - type: database
      description: Database access secrets
      configuration:
        roles:
          - name: mongo-admin
            db_name: mongo
            default-ttl: 1h
            max_ttl: 2h
            creation_statements: '{"database_name": "admin","roles": [{"databaseName":"admin","roleName":"atlasAdmin"}]}'
        config:
          - name: mongo
            plugin_name: mongodbatlas-database-plugin
            allowed_roles:
              - courses-service-admin
            project_id: ...snip...
            public_key: ...snip...
            private_key: '${ awskms (env `ENCRYPTED_MONGODB_ATLAS_COURSES_SERVICE_PRIVATE_KEY`) }'
envsConfig:
  - name: ENCRYPTED_MONGODB_ATLAS_COURSES_SERVICE_PRIVATE_KEY
    value: AQICAHh...snip...5X6oXS0=
```

/kind bug
