### ISSUE TITLE
Issues with policies and AWS secrets engine

### ISSUE THREAD

**Issue by gowthamsubbu** [banzaicloud/bank-vaults#126]
@bonifaido We are trying to create the Vault-Etcd cluster with the below manifest. As you can see, we are creating AWS secrets engine with access and secret key config and also policies dedicated for respective auth roles.

However, vault is not initialized with AWS secret engine and the policies are also not listed, also there is no trace in logs as well. I tried looking at Bank-Vaults code for configuring secret engine and couldn't find any specification.

FYI, We are using the latest image for both operator and Bank-vault.

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: secrets
spec:
  size: 2
  image: vault:0.10.3
  bankVaultsImage: banzaicloud/bank-vaults:master
  imagePullPolicy: IfNotPresent
  
  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    aws:
      kmsKeyId: f2fa72dd-80d1-*****
      kmsRegion: us-east-1
      s3Bucket: vault-key-bucket-dev
      s3Region: us-east-1

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      etcd:
        address: https://etcd-cluster:2379
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.default:8200
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
    - name: admin
      rules: path "secret/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "auth/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "aws/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/auth/*" {
              capabilities = ["create", "read", "update", "delete", "sudo"]
            }
             path "sys/policy" {
              capabilities = ["read"]
            }
             path "sys/policy/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/mounts/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/health" {
              capabilities = ["read", "sudo"] 
            }
             path "sys/capabilities" {
              capabilities = ["create", "update"] 
            }
             path "sys/capabilities-self" {
              capabilities = ["create", "update"] 
            }
    - name: provisioner
      rules: path "auth/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/auth/*" {
              capabilities = ["create", "read", "update", "delete", "sudo"]
            }
             path "sys/policy" {
              capabilities = ["read"]
            }
             path "sys/policy/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "secret/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "aws/*" {
              capabilities = ["create"]
            }
    auth:
    - type: kubernetes
      roles:
        # Allow every pod in the secrets namespace to use the secret kv store
        - name: Kube-Vault-ServiceAccount-Role
          bound_service_account_names: vault
          bound_service_account_namespaces: secrets
          policies: admin
          ttl: 1h
    - type: aws
      roles:
      # Add roles for AWS instances or principals
      # See https://www.vaultproject.io/api/auth/aws/index.html#create-role
      - name: Jenkins-woker-Role
        bound_iam_principal_arn: arn:aws:iam::*********:role/jenkinsRole
        policies: provisioner
        period: 1h
    secrets:
    # This plugin stores arbitrary secrets within the configured physical storage for Vault.
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for
    # more information.
    - path: secret
      type: kv
      description: General secrets
    - path: aws
      type: aws
      description: AWS secrets
      configuration:
        config:
          - name: root
            access_key: AKIAI********
            secret_key: yibA3/RjRZVaH***********
            region: us-east-1
  credentialsConfig:
    env: AWS_SHARED_CREDENTIALS_FILE
    path: /etc/aws/credentials
    secretName: aws-cred
```

**Comment by bonifaido** [comment]
Hi @gowthamsubbu, could you please past any logs from Vault and all the sidecar and helping pods?

**Comment by gowthamsubbu** [comment]
@bonifaido Apologizes. I take back my word and there are traces of logs in configurer pod. 

Vault pod logs

==> Vault server configuration:

             Api Address: https://vault.default:8200
                     Cgo: disabled
         Cluster Address: https://vault.default:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
               Log Level: debug
2018-08-22T12:34:10.259Z [DEBUG] storage.cache: creating LRU cache: size=0
2018-08-22T12:34:10.458Z [DEBUG] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
                   Mlock: supported: true, enabled: true
                 Storage: etcd (HA available)
                 Version: Vault v0.10.3
             Version Sha: c69ae68faf2bf7fc1d78e3ec62655696a07454c7

==> Vault server started! Log data will stream in below:

2018-08-22T12:34:11.397Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:13.025Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:17.425Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:19.725Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:23.001Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:29.876Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:33.012Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:39.837Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:39.897Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:41.097Z [INFO ] core: security barrier not initialized
2018-08-22T12:34:41.218Z [INFO ] core: security barrier initialized: shares=5 threshold=3
2018-08-22T12:34:41.346Z [DEBUG] core: cluster name not found/set, generating new
2018-08-22T12:34:41.346Z [DEBUG] core: cluster name set: name=vault-cluster-c7d5c7d3
2018-08-22T12:34:41.346Z [DEBUG] core: cluster ID not found, generating new
2018-08-22T12:34:41.346Z [DEBUG] core: cluster ID set: id=faa23069-95dc-3de4-f5ff-51cb2671c1ac
2018-08-22T12:34:41.533Z [DEBUG] core: generating local cluster certificate
2018-08-22T12:34:41.674Z [INFO ] core: post-unseal setup starting
2018-08-22T12:34:41.674Z [DEBUG] core: clearing forwarding clients
2018-08-22T12:34:41.674Z [DEBUG] core: done clearing forwarding clients
2018-08-22T12:34:41.839Z [INFO ] core: loaded wrapping token key
2018-08-22T12:34:41.839Z [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018-08-22T12:34:41.959Z [INFO ] core: no mounts; adding default mount table
2018-08-22T12:34:42.120Z [INFO ] core: successfully mounted backend: type=kv path=secret/
2018-08-22T12:34:42.120Z [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018-08-22T12:34:42.120Z [INFO ] core: successfully mounted backend: type=system path=sys/
2018-08-22T12:34:42.120Z [INFO ] core: successfully mounted backend: type=identity path=identity/
2018-08-22T12:34:42.321Z [INFO ] core: restoring leases
2018-08-22T12:34:42.321Z [INFO ] rollback: starting rollback manager
2018-08-22T12:34:42.321Z [DEBUG] expiration: collecting leases
2018-08-22T12:34:42.324Z [DEBUG] expiration: leases collected: num_existing=0
2018-08-22T12:34:42.324Z [INFO ] expiration: lease restore complete
2018-08-22T12:34:42.547Z [DEBUG] identity: loading entities
2018-08-22T12:34:42.594Z [DEBUG] identity: entities collected: num_existing=0
2018-08-22T12:34:42.596Z [INFO ] identity: entities restored
2018-08-22T12:34:42.596Z [DEBUG] identity: identity loading groups
2018-08-22T12:34:42.598Z [DEBUG] identity: groups collected: num_existing=0
2018-08-22T12:34:42.598Z [INFO ] identity: groups restored
2018-08-22T12:34:42.599Z [DEBUG] core: starting cluster listeners
2018-08-22T12:34:42.599Z [DEBUG] core: cluster listener setup function
2018-08-22T12:34:42.599Z [DEBUG] core: clearing forwarding clients
2018-08-22T12:34:42.599Z [DEBUG] core: done clearing forwarding clients
2018-08-22T12:34:42.600Z [DEBUG] core: leaving cluster listener setup function
2018-08-22T12:34:42.600Z [INFO ] core: post-unseal setup complete
2018-08-22T12:34:42.600Z [INFO ] core: core/startClusterListener: starting listener: listener_address=0.0.0.0:8201
2018-08-22T12:34:42.600Z [INFO ] core: core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
2018-08-22T12:34:42.682Z [INFO ] core: root token generated
2018-08-22T12:34:42.699Z [INFO ] core: pre-seal teardown starting
2018-08-22T12:34:42.699Z [INFO ] core: stopping cluster listeners
2018-08-22T12:34:42.699Z [DEBUG] core: waiting for success notification while stopping cluster listeners
2018-08-22T12:34:42.699Z [INFO ] core: shutting down forwarding rpc listeners
2018-08-22T12:34:42.699Z [INFO ] core: forwarding rpc listeners stopped
2018-08-22T12:34:43.108Z [INFO ] core: rpc listeners successfully shut down
2018-08-22T12:34:43.108Z [INFO ] core: cluster listeners successfully shut down
2018-08-22T12:34:43.108Z [DEBUG] expiration: stop triggered
2018-08-22T12:34:43.108Z [DEBUG] expiration: finished stopping
2018-08-22T12:34:43.108Z [INFO ] rollback: stopping rollback manager
2018-08-22T12:34:43.108Z [INFO ] core: pre-seal teardown complete
2018-08-22T12:34:44.528Z [DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=3 nonce=69f2f4a4-1080-d4ca-9fb7-22cb1978a9c6
2018-08-22T12:34:44.585Z [DEBUG] core: cannot unseal, not enough keys: keys=2 threshold=3 nonce=69f2f4a4-1080-d4ca-9fb7-22cb1978a9c6
2018-08-22T12:34:44.849Z [INFO ] core: vault is unsealed
2018-08-22T12:34:44.850Z [INFO ] core: entering standby mode
2018-08-22T12:34:45.015Z [INFO ] core: acquired lock, enabling active operation
2018-08-22T12:34:45.466Z [DEBUG] core: generating local cluster certificate
2018-08-22T12:34:45.666Z [INFO ] core: post-unseal setup starting
2018-08-22T12:34:45.666Z [DEBUG] core: clearing forwarding clients
2018-08-22T12:34:45.666Z [DEBUG] core: done clearing forwarding clients
2018-08-22T12:34:45.727Z [INFO ] core: loaded wrapping token key
2018-08-22T12:34:45.728Z [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018-08-22T12:34:45.743Z [INFO ] core: successfully mounted backend: type=kv path=secret/
2018-08-22T12:34:45.743Z [INFO ] core: successfully mounted backend: type=system path=sys/
2018-08-22T12:34:45.743Z [INFO ] core: successfully mounted backend: type=identity path=identity/
2018-08-22T12:34:45.743Z [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018-08-22T12:34:45.886Z [INFO ] core: restoring leases
2018-08-22T12:34:45.887Z [INFO ] rollback: starting rollback manager
2018-08-22T12:34:45.887Z [DEBUG] expiration: collecting leases
2018-08-22T12:34:46.048Z [DEBUG] expiration: leases collected: num_existing=0
2018-08-22T12:34:46.048Z [INFO ] expiration: lease restore complete
2018-08-22T12:34:46.093Z [DEBUG] identity: loading entities
2018-08-22T12:34:46.132Z [DEBUG] identity: entities collected: num_existing=0
2018-08-22T12:34:46.132Z [INFO ] identity: entities restored
2018-08-22T12:34:46.132Z [DEBUG] identity: identity loading groups
2018-08-22T12:34:46.175Z [DEBUG] identity: groups collected: num_existing=0
2018-08-22T12:34:46.175Z [INFO ] identity: groups restored
2018-08-22T12:34:46.193Z [DEBUG] core: starting cluster listeners
2018-08-22T12:34:46.193Z [DEBUG] core: cluster listener setup function
2018-08-22T12:34:46.193Z [DEBUG] core: clearing forwarding clients
2018-08-22T12:34:46.193Z [DEBUG] core: done clearing forwarding clients
2018-08-22T12:34:46.194Z [DEBUG] core: leaving cluster listener setup function
2018-08-22T12:34:46.194Z [INFO ] core: post-unseal setup complete
2018-08-22T12:34:46.194Z [INFO ] core: core/startClusterListener: starting listener: listener_address=0.0.0.0:8201
2018-08-22T12:34:46.194Z [INFO ] core: core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
2018-08-22 12:34:55.899963 I | http: TLS handshake error from 10.25.113.218:59162: EOF
2018-08-22 12:35:05.886677 I | http: TLS handshake error from 10.25.113.218:59178: EOF
2018-08-22 12:35:05.950921 I | http: TLS handshake error from 10.25.113.218:59182: EOF
2018-08-22 12:35:05.957330 I | http: TLS handshake error from 10.25.113.218:59180: EOF
2018-08-22 12:35:12.920283 I | http: TLS handshake error from 10.25.113.218:59188: EOF


Bank-Vaults log

time="2018-08-22T12:34:39Z" level=info msg="initializing vault..."
time="2018-08-22T12:34:39Z" level=info msg="initializing vault"
time="2018-08-22T12:34:43Z" level=info msg="unseal key stored in key store" key=vault-unseal-0
time="2018-08-22T12:34:43Z" level=info msg="unseal key stored in key store" key=vault-unseal-1
time="2018-08-22T12:34:43Z" level=info msg="unseal key stored in key store" key=vault-unseal-2
time="2018-08-22T12:34:44Z" level=info msg="unseal key stored in key store" key=vault-unseal-3
time="2018-08-22T12:34:44Z" level=info msg="unseal key stored in key store" key=vault-unseal-4
time="2018-08-22T12:34:44Z" level=info msg="root token stored in key store" key=vault-root
time="2018-08-22T12:34:44Z" level=info msg="checking if vault is sealed..."
time="2018-08-22T12:34:44Z" level=info msg="vault sealed: true"
time="2018-08-22T12:34:44Z" level=info msg="successfully unsealed vault"
time="2018-08-22T12:35:14Z" level=info msg="checking if vault is sealed..."
time="2018-08-22T12:35:15Z" level=info msg="vault sealed: false"


Vault-configurer pod

time="2018-08-22T12:34:09Z" level=info msg="New config file change \"Initial\": CREATE"
time="2018-08-22T12:34:09Z" level=info msg="checking if vault is sealed..."
time="2018-08-22T12:35:18Z" level=info msg="vault is not sealed, configuring..."
time="2018-08-22T12:35:18Z" level=error msg="error configuring vault: error finding config block for aws: unable to cast <nil> of type <nil> to map[string]interface{}"

**Comment by bonifaido** [comment]
The last line above:
```
time="2018-08-22T12:35:18Z" level=error msg="error configuring vault: error finding config block for aws: unable to cast of type to map[string]interface{}"
```

means that the AWS configuration is not correct in the `auth` section, it has to have the following scheme (seen in the README):
```yaml
  # Allows creating roles in Vault which can be used later on for AWS
  # IAM based authentication.
  # See https://www.vaultproject.io/docs/auth/aws.html for
  # more information.
  - type: aws
    config:
      access_key: VKIAJBRHKH6EVTTNXDHA
      secret_key: vCtSM8ZUEQ3mOFVlYPBQkf2sO6F/W7a5TVzrl3Oj
      iam_server_id_header_value: vault-dev.example.com # consider setting this to the Vault server's DNS name
    roles:
    # Add roles for AWS instances or principals
    # See https://www.vaultproject.io/api/auth/aws/index.html#create-role
    - name: dev-role-iam
      bound_iam_principal_arn: arn:aws:iam::123456789012:role/dev-vault
      policies: allow_secrets
      period: 1h
```
