### ISSUE TITLE
[Mutating Webhook] With environment variable VAULT_TOKEN: vault:login VAULT_ADDR is unset

### ISSUE THREAD

**Issue by ichasco-heytrade** [banzaicloud/bank-vaults#1263]
Hi,

I am using the feature `vault:login` it works but it unsets the variable `VAULT_ADDR` for the container

I set these variables 

```
env:
  - name: ENVIRONMENT
    value: dev
  - name: VAULT_ADDR
    value: https://vault.example.com
  - name: VAULT_STAGE
    value: development
  - name: VAULT_TOKEN
    value: vault:login
```

and when I do a `printenv` I get all of them except `VAULT_ADDR`

Webhook version: `1.11.2`

Thanks!
