### ISSUE TITLE
[vault-secrets-webhook] able to use certs-manager v1 resources

### ISSUE THREAD

**Issue by caiofralmeida** [banzaicloud/bank-vaults#1283]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
In our Kubernetes cluster, we are using the latest version of certs-manager (v1.2.0), when we try to enable certificate management in vault-secrets-webhook we have the following error:
```
[2021-03-24T19: 16: 15.217Z] Error: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]
```
Is there any way we can use the features of cert-manager (v1alpha2) without having to update its version?

**Expected behavior**:
The certs-manager installed successfully.

**Steps to reproduce the bug**:
Try to enable vault-secrets-webhook certs-manager in the k8s cluster that has the certs-manager operator v1.2.0.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.18
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.50.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
```
[2021-03-24T19: 16: 15.217Z] Error: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml
/kind bug
/kind improvement

**Comment by bonifaido** [comment]
Is the issue that you have cert-manager with API version `cert-manager.io/v1` right? I think we need to define a check here in the templates.

**Comment by caiofralmeida** [comment]
Yes @bonifaido, when I use the `cert-manager.io/v1` works fine.

e.g.:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-foo
  namespace: default
spec:
  dnsNames:
  - foo.svc
  - foo.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: foo-selfsigned-issuer
  secretName: foo-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: foo-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
```
I don't know if there is some workaround solution for that unless updating the version of the resources to v1.
