### ISSUE TITLE
Unable to mutate secrets

### ISSUE THREAD

**Issue by laukaichung** [banzaicloud/bank-vaults#1309]
**Describe the bug**:
I tried to use Bank Vaults to generate custom secrets for authorization of [Redis operator](https://github.com/spotahome/redis-operator#enabling-redis-auth). Vault webhook didn't inject the secret, so the redis cluster just used the literal `vault:secret/data/cred#REDIS_PASSWORD` as the password instead of the actual password stored in Vault secret.

**Expected behaviour**:
Able to inject the secrets inline.

**Steps to reproduce the bug**:

````
kind: Secret
apiVersion: v1
metadata:
  name: redis-auth
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/inline-mutation: "true"
data:
  # vault:secret/data/cred#REDIS_PASSWORD
  password: dmF1bHQ6c2VjcmV0L2RhdGEvY3JlZCNSRURJU19QQVNTV09SRA==

---

apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  auth:
    secretPath: redis-auth
  sentinel:
    replicas: 1
    podAnnotations:
      vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
      vault.security.banzaicloud.io/vault-role: "default"
      vault.security.banzaicloud.io/vault-skip-verify: "false"
      vault.security.banzaicloud.io/vault-path: "kubernetes"
      vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 1
    podAnnotations:
      vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
      vault.security.banzaicloud.io/vault-role: "default"
      vault.security.banzaicloud.io/vault-skip-verify: "false"
      vault.security.banzaicloud.io/vault-path: "kubernetes"
      vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
````

**Environment details**:
- Kubernetes version: 1.21
- Cloud-provider/provisioner: localhost
- bank-vaults version : 1.6.2
- Install method: static manifests

----

**Comment by laukaichung** [comment]
I finally got this working after reading a few threads.

Here's an example:

````
apiVersion: v1
kind: Secret
metadata:
  name: mutate-me
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
data:
  test: dmF1bHQ6c2VjcmV0L2RhdGEvd2ViI01ZX1BBU1NXT1JE
````

To enable `vault-skip-verify`, I have to add `vault-infra` to the `caNamespaces` in `cr.yaml`. `"vault-infra"` is where `vault-secrets-webhook` resides.

cr.yaml
````
  caNamespaces:
    - "vswh"
    - "vault-infra" #<<
```` 

The `vault.security.banzaicloud.io/vault-addr` should be `https://vault.default.svc.cluster.local:8200` instead of `https://vault.8200` because the local vault operator is in the `default` namespace, while `vault-secrets-webhook` is in `vault-infra`. 

I read that configMapMutation was disable by default, so I have to upgrade the helm settings like this:
 
````
helm upgrade --namespace vault-infra --install vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --set=secretsFailurePolicy=Fail --set=configMapMutation=true
````

The `secretsFailurePolicy=Fail ` is very useful for debugging. If the secret doesn't work, it immediately stops and returns the reason of failure. 

After running `kubectl apply -f secret.yaml`, I head to the k8s dashboard, and find that the secret shows the actual password instead of `vault:secret/data/web#MY_PASSWORD`.
