### ISSUE TITLE
[vault-secrets-webhook] service account name not authorized; namespace not authorized - documentation issue maybe?

### ISSUE THREAD

**Issue by notjames** [banzaicloud/bank-vaults#1313]
Not able to mutate secrets if the operator (vault) and the webhook are in separate namespaces (error: `namespace not authorized`) and if they are in the same namespace then I get `service account name not authorized`.

I think this is a documentation first. There is no clear documentation that explicitly describes what needs to be set as what in order to get mutations to work; specifically secrets and configmaps. Looking through issues, mine is not an isolated issue. 

The questions I have are: 
 * can the vault-operator/vault and the webhook run in separate namespaces?
   * if so, what configuration nuances exist?
 * I finally figured out the `roles` in the CR under `externalConfig.auth` but documentation is very sparse on the purpose of this
 * How do the `bound_service_account_names` and `bound_service_account_namespaces` work together? What is their function in terms of how the operator uses these functions?

Because I am unable to figure out these nuances, I'm working with the following problem

similar to: https://www.gitmemory.com/issue/banzaicloud/bank-vaults/542/508459934

At very least, I'm suggesting that the documentation for the operator/webhook needs to be very clear and specific about how to set up namespaces, serviceaccounts, and rbac, etc as well as defining exactly what the options in the CR under `auth[].roles[]` under different conditions (single and multi-tenancy).

For instance:

The setup we have is that the vault-operator runs in the `vault` namespace. The mutator runs in the `vault-secrets-webhook` namespace. The relevant bits in the operator config:

helm:
```
 helm upgrade --install vault-operator banzaicloud-stable/vault-operator --create-namespace -n vault 
 helm upgrade --install vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --create-namespace -n vault-secrets-webhook --set secretsFailurePolicy=Fail
```

separate namespaces (relevant policies):
```
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names:
              - alertmanager
            bound_service_account_namespaces:
              - monitoring
            policies:
              - allow_secrets
            ttl: 1h
```

rbac:
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault
  namespace: vault

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "patch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
roleRef:
  kind: Role
  name: vault-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    # current cluster specifies "vault" namespace here.
    namespace: vault

---

# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
```

The secret:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mutate-me
  namespace: monitoring
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: default
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/inline-mutation: 'true'
    kubernetes.io/service-account.name: alertmanager
data:
  testconfig.yaml: >-
    c210cF9hdXRoX3Bhc3N3b3JkOiAke3ZhdWx0OnNlY3JldC9kYXRhL21vbml0b3JpbmcyL2FsZXJ0bWFuYWdlciNzbXRwX2F1dGhfcGFzc3dvcmR9CnNtdHBfYXV0aF91c2VybmFtZTogJHt2YXVsdDpzZWNyZXQvZGF0YS9tb25pdG9yaW5nMi9hbGVydG1hbmFnZXIjc210cF9hdXRoX3VzZXJuYW1lfQotIHJvdXRpbmdfa2V5OiAke3ZhdWx0Oi9zZWNyZXQvZGF0YS9tb25pdG9yaW5nMi9wYWdlcmR1dHkjbWFpbl9yb3V0aW5nX2tleX0K
```

The error:
```
time="2021-05-07T01:07:45Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
time="2021-05-07T01:07:50Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
time="2021-05-07T01:07:51Z" level=error msg="admission webhook error: failed to create vault client: timeout [10s] during waiting for Vault token" app=vault-secrets-webhook
```

=========== SAME NAMESPACE =============

If they both run in the `vault` namespace:

helm
```
helm upgrade --install vault-operator banzaicloud-stable/vault-operator --create-namespace -n vault 
helm upgrade --install vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --create-namespace -n vault --set secretsFailurePolicy=Fail
```

relevant policies:
```
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: vault-secrets
            bound_service_account_names: alertmanager
            bound_service_account_namespaces: monitoring
            policies: allow_secrets
            ttl: 1h
```

rbac:
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault
  namespace: vault

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "patch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
roleRef:
  kind: Role
  name: vault-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault

---

# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
```

Secrets mutations cause various errors depending on how I have things setup in the vault operator. 

The following secret:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mutate-me
  namespace: vault
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: default
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/inline-mutation: 'true'
    kubernetes.io/service-account.name: vault
data:
  testconfig.yaml: >-
    c210cF9hdXRoX3Bhc3N3b3JkOiAke3ZhdWx0OnNlY3JldC9kYXRhL21vbml0b3JpbmcyL2FsZXJ0bWFuYWdlciNzbXRwX2F1dGhfcGFzc3dvcmR9CnNtdHBfYXV0aF91c2VybmFtZTogJHt2YXVsdDpzZWNyZXQvZGF0YS9tb25pdG9yaW5nMi9hbGVydG1hbmFnZXIjc210cF9hdXRoX3VzZXJuYW1lfQotIHJvdXRpbmdfa2V5OiAke3ZhdWx0Oi9zZWNyZXQvZGF0YS9tb25pdG9yaW5nMi9wYWdlcmR1dHkjbWFpbl9yb3V0aW5nX2tleX0K
```

```
❯ kg sa -n monitoring
NAME           SECRETS   AGE
alertmanager   1         17h
default        1         17h
```

With this configuration, when I try mutate secrets, the error I get is `service account name not authorized`

**Environment details**:
- Kubernetes version (e.g. v1.10.2):  `v1.20.2`
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): testing with `kind`
- bank-vaults version (e.g. 0.4.17): `latest`
- Install method (e.g. helm or static manifests): `helm`
- Logs from the misbehaving component (and any other relevant logs):

```
time="2021-05-06T06:35:44Z" level=warning msg="no tracer active" app=vault-secrets-webhook
time="2021-05-06T06:35:44Z" level=warning msg="no tracer active" app=vault-secrets-webhook
time="2021-05-06T06:35:44Z" level=info msg="Listening on https://:8443" app=vault-secrets-webhook
time="2021-05-06T06:36:34Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* service account name not authorized"
time="2021-05-06T06:36:38Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* service account name not authorized"
time="2021-05-06T06:36:39Z" level=error msg="admission webhook error: failed to create vault client: timeout [10s] during waiting for Vault token" app=vault-secrets-webhook
time="2021-05-06T06:36:39Z" level=info msg="Vault token renewal closed" app=vault-secrets-webhook

```

**Expected behaviour**:
expect k8s secret to mutate

Possibly related issues:

https://github.com/banzaicloud/bank-vaults/issues/1270

https://github.com/banzaicloud/bank-vaults/issues/1309

/kind bug

**Comment by bonifaido** [comment]
I don't think the operator documentation should replicate what is stated already at: https://www.vaultproject.io/docs/auth/kubernetes and https://www.vaultproject.io/api/auth/kubernetes

The operator does nothing special just forwards the values of `bound_service_account_names`, `bound_service_account_namespaces` etc... (described in the above docs) to Vault.

**Comment by bonifaido** [comment]
In case of secrets, the web hook accesses the data in Vault (since nobody else can, compared to pods, where the pod has a serviceAccount so it can access Vault).

So you have to add the serviceAccount name of the web hook to bound_service_account_names and the namespace of it to bound_service_account_namespaces to make this work.

**Comment by notjames** [comment]
> In case of secrets, the web hook accesses the data in Vault (since nobody else can, compared to pods, where the pod has a serviceAccount so it can access Vault).
> 
> So you have to add the serviceAccount name of the web hook to bound_service_account_names and the namespace of it to bound_service_account_namespaces to make this work.

OK. Good information. So just to make sure I'm understanding: the values (SAs and namespaces) in `bound_service_account-names` and `bound_service_account_namespaces` don't need values of all of the various services we want to allow the ability to mutate secrets; just the one for the webhook pods -- and if we're only running one vault-secrets-webhook then we really only need one or two values in those fields? If that's the case then some of our engineers have totally misunderstood something somewhere, which in turn caused my confusion. I'll take a look at the documentation you linked as well. It might just be that there's information overload.

**Comment by notjames** [comment]
OK, I finally got this working. What. a. PAIN. The documentation you shared was useful, but I had to go digging through everything myself instead of just having documentation for this project explain the necessary pieces required for successful secrets mutation. I think, but I'm not 100% sure, that the thing that was a main culprit to keeping my stuff from working was the `spec.serviceAccount` not properly set in the CR manifest and I glossed by it because it wasn't clear what manifest required which configurations. In the end, I think I nailed it to the following:

 * the SA and namespace of the manifest bearing the secret I wanted to mutate didn't matter with respect to what was in the manifest.
 * the `spec.serviceAccount` of the CR needs to specify the correct serviceaccount where the vault pod and configurer runs
 * the `externalConfig.policies` and `externalConfig.policies` are used by the configurer to set up `kubernetes` roles and policies in Vault according to the documentation you linked and the most important part of that point as far as I believe I've learned is:
   * **pods** service accounts and namespaces are respected with respect to the `externalConfig.auth.roles[].bound_service_account_names` and `externalConfig.auth.roles[].bound_service_account_namespaces`
   * **secrets** `externalConfig.auth.roles[].bound_service_account_names` and `externalConfig.auth.roles[].bound_service_account_namespaces` require the ns and sa of the vault-secrets-webhook pod; this was my main confusion and as far as I could tell, not documented.

If any of that is wrong, I'd love correction, but this was how I got things properly configured:

```
spec:  
...
 serviceAccount: vault 
...
  externalConfig:                                                                                                                                                                                                                                                                                                                                        
    policies:                                                                                                                                                                                                                                                                                                                                            
      - name: allow_secrets                                                                                                                                                                                                                                                                                                                              
        rules: path "secret/*" {                                                                                                                                                                                                                                                                                                                         
          capabilities = ["create", "read", "update", "delete", "list"]                                                                                                                                                                                                                                                                                  
          }                                                                                                                                                                                                                                                                                                                                              
    auth:                                                                                                                                                                                                                                                                                                                                                
      - type: kubernetes                                                                                                                                                                                                                                                                                                                                 
        roles:                                                                                                                                                                                                                                                                                                                                           
          # Allow every pod in the default namespace to use the secret kv store                                                                                                                                                                                                                                                                          
          - name: default                                                                                                                                                                                                                                                                                                                                
            bound_service_account_names:                                                                                                                                                                                                                                                                                                                 
              - things
            bound_service_account_namespaces:
              - things
            policies:
              - allow_secrets
            ttl: 1h

          # Allow mutation of secrets using secrets-mutation annotation to use the secret kv store
          - name: secretsmutation
            bound_service_account_names:
              - vault-secrets-webhook
            bound_service_account_namespaces:
              - vault-secrets-webhook
            policies:
              - allow_secrets
            ttl: 1h
```
