### ISSUE TITLE
Database connection never gets created if initially not available 

### ISSUE THREAD

**Issue by tandrup** [banzaicloud/bank-vaults#1316]
**Describe the bug**:
If bank vaults is not able to configure a connection in the database engine initially it does not retry.

**Expected behaviour**:
I expect bank vaults to continue retrying to apply the configuration.

**Steps to reproduce the bug**:
In the bank vaults CRD specify:
```
      - type: database
        description: Database secret engine.
        configuration:
          config:
            - name: cassandra
              plugin_name: "cassandra-database-plugin"
              hosts: "cassandra"
              protocol_version: 4
              allowed_roles: "cs-*"
              username: "{{ .Values.databases.cassandra.username }}"
              password: "{{ .Values.databases.cassandra.password }}" 
              root_rotation_statements: "ALTER ROLE {{ "{{" }}username}} WITH PASSWORD '{{ "{{" }}password}}" 
              rotate: true
```

There's no need to actually have a Cassandra server. But if during the first run there is some connection issue to my Cassandra the log says:
```
time="2021-05-06T20:25:51Z" level=info msg="mounted database to database"
time="2021-05-06T20:25:51Z" level=error msg="error configuring vault: error configuring secret engines for vault: error configuring database/config/cassandra config in vault: Error making API request.\n\nURL: PUT https://envvault.sc-vault-cassandra-vault:8200/v1/database/config/cassandra\nCode: 400. Errors:\n\n* error creating database object: failed to initialize: error verifying connection: error creating session: gocql: unable to create session: control: unable to connect to initial hosts: Provided username vault and/or password are incorrect"
time="2021-05-06T20:25:51Z" level=info msg="Failed applying configuration file: /config/envvault-configurer/vault-config.yml , sleeping for 500ms before trying again"
```

Based on the last message I expect bank vaults to retry. When it tries again it seems to think it was successful at creating the Cassandra connection previously and now tries to rotate the credentials:

```
time="2021-05-06T20:25:53Z" level=info msg="tuning already existing mount: database/"
time="2021-05-06T20:25:53Z" level=info msg="Secret at configpath database/config/cassandra already exists, rotate was set so this will not be updated"
time="2021-05-06T20:25:53Z" level=info msg="doing credential rotation at database/rotate-root/cassandra"
time="2021-05-06T20:25:57Z" level=error msg="error configuring vault: error configuring secret engines for vault: error rotating credentials for 'database/config/cassandra' config in vault: error rotating credentials for 'database/config/cassandra' config in vault: Error making API request.\n\nURL: PUT https://envvault.sc-vault-cassandra-vault:8200/v1/database/rotate-root/cassandra\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* failed to find entry for connection with name: \"cassandra\"\n\n"
time="2021-05-06T20:25:57Z" level=info msg="Failed applying configuration file: /config/envvault-configurer/vault-config.yml , sleeping for 1s before trying again"
```

**Additional context**:
If the Cassandra server is missing it says this:
```
time="2021-05-06T12:49:12Z" level=error msg="error configuring vault: error configuring secret engines for vault: error configuring database/config/cassandra config in vault: Error making API request.\n\nURL: PUT https://envvault.sc-vault-cassandra-vault:8200/v1/database/config/cassandra\nCode: 400. Errors:\n\n* error creating database object: failed to initialize: error verifying connection: error creating session: gocql: unable to create session: failed to resolve any of the provided hostnames"
```
But the pattern is the same

**Environment details**:
- Kubernetes version: 1.18
- Cloud-provider/provisioner: AKS
- bank-vaults version: 1.11.2
- Install method: helm

/kind bug
