### ISSUE TITLE
Is `spec.command` required in a deployment file for Vault to work?

### ISSUE THREAD

**Issue by laukaichung** [banzaicloud/bank-vaults#1320]
**Describe the bug**:
I don't understand why Bank Vaults won't inject secrets and mount `/vault` the folder into the pod unless `spec.command` is added to deployment.yaml.

**Expected behaviour**:
Vault should work without the need of `spec.command`

**Steps to reproduce the bug**:

I already has this command ["dumb-init","node", "index.js"] in the node.js Dockerfile.
````
FROM node:15.14 As build
WORKDIR /app/
COPY ./package.json .
COPY yarn.lock .
RUN yarn install --production

FROM node:15.14

RUN  apt-get update -y && apt-get install -y dumb-init

ENV NODE_ENV=production
WORKDIR /app/
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package.json .
COPY index.js .
CMD ["dumb-init","node", "index.js"]
````

so I thought I didn't need to add the command again to the deployment file. The vault operator doesn't have any error log related to the app pod.  I have to uncomment `command: ["dumb-init","node", "index.js"]` in the following file for Vault to inject the secrets. Is it normal?

deployment.yaml 
````

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "false"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      serviceAccountName: default
      containers:
        - name: web
          image: nodejs
          #command: ["dumb-init","node", "index.js"]
          env:
            - name: AWS_SECRET_ACCESS_KEY
              value: vault:secret/data/something#ELASTIC_ADMIN_PASSWORD

````

**Additional context**:

**Environment details**:
- Kubernetes version: 1.21
- Cloud-provider/provisioner : localhost
- bank-vaults version (e.g. 0.4.17): 1.6.2
- Install method (e.g. helm or static manifests): kustomize

/kind bug
