### ISSUE TITLE
[vault-operator] bank-vaults fails when using Vault auto unseal feature. Root key doesn't get stored.

### ISSUE THREAD

**Issue by dgamo** [banzaicloud/bank-vaults#1325]
**Describe the bug**:
Bank-vaults fails to encrypt and store root key when using the auto unseal feature from Vault.

**Expected behaviour**:
We are expecting bank-vaults to do just init, no unseal, letting Vault to auto unseal. It should store the encrypted root key in the desired bucket.

**Steps to reproduce the bug**:
After installing the operator. Try to create a Vault CRD with auto unseal. Like the provided one or https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-gcs-ha-autounseal.yaml

**Additional context**:
From the logs, we can see Vault gets initialized so bank-vaults is doing that and Vault does auto unseal, but it feels like at some point another call to init is made that results in a 400 which causes an error before storing the root key.

We believe this is the erroring call, as we can see the preflight check happening correctly, the test file is in the bucket.

https://github.com/banzaicloud/bank-vaults/blob/27e2ac544358bd3fc28e9c4cd22bb2b822f66a76/internal/vault/operator_client.go#L278-L286

But, at that point..seems that init already happened.

If we remove the seal config from Vault, everything works as expected. We get a cluster and the root and seal keys are stored in our bucket. This only happens when Vault auto unseal.

We can see that bank-vaults is run with:

```
Command:
      bank-vaults
      unseal
      --init
      --auto
      --raft
      --raft-leader-address
      http://vault-0:8200
```

**Environment details**:
- Kubernetes version: 1.19
- Cloud-provider/provisioner: GKE
- bank-vaults version: 1.12.1
- Install method: manifest (via argo)
- Logs from the misbehaving component: These are the logs of vault and bank-vaults.

```
+ vault-0 › vault
+ vault-0 › bank-vaults
vault-0 bank-vaults time="2021-05-14T14:04:03Z" level=info msg="joining leader vault..."
vault-0 bank-vaults time="2021-05-14T14:04:03Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
vault-0 bank-vaults time="2021-05-14T14:04:07Z" level=info msg="initializing vault..."
vault-0 bank-vaults time="2021-05-14T14:04:27Z" level=info msg="initializing vault"
vault-0 vault Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
vault-0 vault ==> Vault server configuration:
vault-0 vault
vault-0 vault       GCP KMS Crypto Key: key
vault-0 vault         GCP KMS Key Ring: keyring
vault-0 vault          GCP KMS Project: project
vault-0 vault           GCP KMS Region: europe-west2
vault-0 vault              Api Address: http://vault.default.:8200
vault-0 vault                      Cgo: disabled
vault-0 vault          Cluster Address: https://vault-0:8201
vault-0 vault               Go Version: go1.15.7
vault-0 vault               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
vault-0 vault                Log Level: debug
vault-0 vault                    Mlock: supported: true, enabled: false
vault-0 vault            Recovery Mode: false
vault-0 vault                  Storage: raft (HA available)
vault-0 vault                  Version: Vault v1.6.2
vault-0 vault              Version Sha: be65a227ef2e80f8588b3b13584b5c0d9238c1d7
vault-0 vault
vault-0 vault ==> Vault server started! Log data will stream in below:
vault-0 vault
vault-0 vault 2021-05-14T14:04:05.037Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
vault-0 vault 2021-05-14T14:04:05.128Z [DEBUG] service_registration.kubernetes: "namespace": "default"
vault-0 vault 2021-05-14T14:04:05.128Z [DEBUG] service_registration.kubernetes: "pod_name": "vault-0"
vault-0 vault 2021-05-14T14:04:07.015Z [DEBUG] core: set config: sanitized config={"api_addr":"http://vault.default:8200","cache_size":0,"cluster_addr":"https://vault-0:8201","cluster_cipher_suites":"","cluster_name":"","default_lease_ttl":0,"default_max_request_duration":0,"disable_cache":false,"disable_clustering":false,"disable_indexing":false,"disable_mlock":true,"disable_performance_standby":false,"disable_printable_check":false,"disable_sealwrap":false,"disable_sentinel_trace":false,"enable_ui":true,"listeners":[{"config":{"address":"0.0.0.0:8200","tls_disable":true},"type":"tcp"}],"log_format":"unspecified","log_level":"","max_lease_ttl":0,"pid_file":"","plugin_directory":"","raw_storage_endpoint":false,"seals":[{"disabled":false,"type":"gcpckms"}],"service_registration":{"type":"kubernetes"},"storage":{"cluster_addr":"https://vault-0:8201","disable_clustering":false,"redirect_addr":"http://vault.default:8200","type":"raft"}}
vault-0 vault 2021-05-14T14:04:07.015Z [DEBUG] storage.cache: creating LRU cache: size=0
vault-0 vault 2021-05-14T14:04:07.016Z [DEBUG] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
vault-0 vault 2021-05-14T14:04:07.017Z [INFO]  core: stored unseal keys supported, attempting fetch
vault-0 vault 2021-05-14T14:04:07.017Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
vault-0 vault 2021-05-14T14:04:12.017Z [INFO]  core: stored unseal keys supported, attempting fetch
vault-0 vault 2021-05-14T14:04:12.017Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
vault-0 vault 2021-05-14T14:04:17.017Z [INFO]  core: stored unseal keys supported, attempting fetch
vault-0 vault 2021-05-14T14:04:17.017Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
vault-0 vault 2021-05-14T14:04:22.017Z [INFO]  core: stored unseal keys supported, attempting fetch
vault-0 vault 2021-05-14T14:04:22.017Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
vault-0 vault 2021-05-14T14:04:27.017Z [INFO]  core: stored unseal keys supported, attempting fetch
vault-0 vault 2021-05-14T14:04:27.017Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
vault-0 vault 2021-05-14T14:04:27.049Z [INFO]  core: security barrier not initialized
vault-0 vault 2021-05-14T14:04:27.049Z [INFO]  core: security barrier not initialized
vault-0 vault 2021-05-14T14:04:28.519Z [WARN]  core: stored keys supported on init, forcing shares/threshold to 1
vault-0 vault 2021-05-14T14:04:28.519Z [INFO]  core: security barrier not initialized
vault-0 vault 2021-05-14T14:04:28.519Z [DEBUG] core: bootstrapping raft backend
vault-0 vault 2021-05-14T14:04:28.523Z [INFO]  storage.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:1f340b49-7f93-8865-56f0-645888f868d4 Address:vault-0:8201}]"
vault-0 vault 2021-05-14T14:04:28.523Z [INFO]  storage.raft: entering follower state: follower="Node at 1f340b49-7f93-8865-56f0-645888f868d4 [Follower]" leader=
vault-0 vault 2021-05-14T14:04:35.112Z [WARN]  storage.raft: heartbeat timeout reached, starting election: last-leader=
vault-0 vault 2021-05-14T14:04:35.112Z [INFO]  storage.raft: entering candidate state: node="Node at 1f340b49-7f93-8865-56f0-645888f868d4 [Candidate]" term=2
vault-0 vault 2021-05-14T14:04:35.116Z [DEBUG] storage.raft: votes: needed=1
vault-0 vault 2021-05-14T14:04:35.116Z [DEBUG] storage.raft: vote granted: from=1f340b49-7f93-8865-56f0-645888f868d4 term=2 tally=1
vault-0 vault 2021-05-14T14:04:35.116Z [INFO]  storage.raft: election won: tally=1
vault-0 vault 2021-05-14T14:04:35.116Z [INFO]  storage.raft: entering leader state: leader="Node at 1f340b49-7f93-8865-56f0-645888f868d4 [Leader]"
vault-0 vault 2021-05-14T14:04:35.119Z [DEBUG] core: finished bootstrapping raft backend

---- VAULT INITIALIZED HERE ---- 

vault-0 vault 2021-05-14T14:04:35.124Z [INFO]  core: security barrier initialized: stored=1 shares=1 threshold=1

---- END VAULT INITIALIZED HERE ---- 

vault-0 vault 2021-05-14T14:04:35.157Z [DEBUG] core: cluster name not found/set, generating new
vault-0 vault 2021-05-14T14:04:35.157Z [DEBUG] core: cluster name set: name=vault-cluster-90ca590a
vault-0 vault 2021-05-14T14:04:35.157Z [DEBUG] core: cluster ID not found, generating new
vault-0 vault 2021-05-14T14:04:35.157Z [DEBUG] core: cluster ID set: id=93ac8af8-d307-5d9c-2dd6-6cf7061f9604
vault-0 vault 2021-05-14T14:04:35.157Z [DEBUG] core: generating cluster private key
vault-0 vault 2021-05-14T14:04:35.167Z [DEBUG] core: generating local cluster certificate
vault-0 vault 2021-05-14T14:04:35.236Z [INFO]  core: post-unseal setup starting
vault-0 vault 2021-05-14T14:04:35.236Z [DEBUG] core: clearing forwarding clients
vault-0 vault 2021-05-14T14:04:35.236Z [DEBUG] core: done clearing forwarding clients
vault-0 vault 2021-05-14T14:04:35.236Z [DEBUG] core: persisting feature flags
vault-0 vault 2021-05-14T14:04:35.328Z [INFO]  core: loaded wrapping token key
vault-0 vault 2021-05-14T14:04:35.328Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
vault-0 vault 2021-05-14T14:04:35.329Z [INFO]  core: no mounts; adding default mount table
vault-0 vault 2021-05-14T14:04:35.335Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault-0 vault 2021-05-14T14:04:35.335Z [INFO]  core: successfully mounted backend: type=system path=sys/
vault-0 vault 2021-05-14T14:04:35.336Z [INFO]  core: successfully mounted backend: type=identity path=identity/
vault-0 vault 2021-05-14T14:04:35.424Z [INFO]  core: successfully enabled credential backend: type=token path=token/
vault-0 vault 2021-05-14T14:04:35.424Z [INFO]  core: restoring leases
vault-0 vault 2021-05-14T14:04:35.424Z [INFO]  rollback: starting rollback manager
vault-0 vault 2021-05-14T14:04:35.425Z [DEBUG] expiration: collecting leases
vault-0 vault 2021-05-14T14:04:35.425Z [DEBUG] expiration: leases collected: num_existing=0
vault-0 vault 2021-05-14T14:04:35.425Z [INFO]  expiration: lease restore complete
vault-0 vault 2021-05-14T14:04:35.437Z [DEBUG] identity: loading entities
vault-0 vault 2021-05-14T14:04:35.437Z [DEBUG] identity: entities collected: num_existing=0
vault-0 vault 2021-05-14T14:04:35.437Z [INFO]  identity: entities restored
vault-0 vault 2021-05-14T14:04:35.437Z [DEBUG] identity: identity loading groups
vault-0 vault 2021-05-14T14:04:35.437Z [DEBUG] identity: groups collected: num_existing=0
vault-0 vault 2021-05-14T14:04:35.437Z [INFO]  identity: groups restored
vault-0 vault 2021-05-14T14:04:35.468Z [WARN]  core: post-unseal upgrade seal keys failed: error="no recovery key found"
vault-0 vault 2021-05-14T14:04:35.469Z [INFO]  core: usage gauge collection is disabled
vault-0 vault 2021-05-14T14:04:35.472Z [INFO]  core: post-unseal setup complete
vault-0 vault 2021-05-14T14:04:35.515Z [INFO]  core: root token generated
vault-0 vault 2021-05-14T14:04:35.542Z [INFO]  core: pre-seal teardown starting
vault-0 vault 2021-05-14T14:04:35.543Z [DEBUG] expiration: stop triggered
vault-0 vault 2021-05-14T14:04:35.543Z [DEBUG] expiration: finished stopping
vault-0 vault 2021-05-14T14:04:35.543Z [INFO]  rollback: stopping rollback manager
vault-0 vault 2021-05-14T14:04:35.543Z [INFO]  core: pre-seal teardown complete
vault-0 vault 2021-05-14T14:04:55.564Z [INFO]  core: stored unseal keys supported, attempting fetch
vault-0 vault 2021-05-14T14:04:55.596Z [DEBUG] core: starting cluster listeners
vault-0 vault 2021-05-14T14:04:55.596Z [INFO]  core.cluster-listener.tcp: starting listener: listener_address=0.0.0.0:8201
vault-0 vault 2021-05-14T14:04:55.596Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
vault-0 vault 2021-05-14T14:04:55.598Z [INFO]  storage.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:1f340b49-7f93-8865-56f0-645888f868d4 Address:vault-0:8201}]"
vault-0 vault 2021-05-14T14:04:55.599Z [INFO]  core: vault is unsealed
vault-0 vault 2021-05-14T14:04:55.599Z [INFO]  storage.raft: entering follower state: follower="Node at vault-0:8201 [Follower]" leader=
vault-0 vault 2021-05-14T14:04:55.599Z [INFO]  core: entering standby mode
vault-0 vault 2021-05-14T14:05:02.515Z [WARN]  storage.raft: heartbeat timeout reached, starting election: last-leader=
vault-0 vault 2021-05-14T14:05:02.515Z [INFO]  storage.raft: entering candidate state: node="Node at vault-0:8201 [Candidate]" term=3
vault-0 vault 2021-05-14T14:05:02.519Z [DEBUG] storage.raft: votes: needed=1
vault-0 vault 2021-05-14T14:05:02.519Z [DEBUG] storage.raft: vote granted: from=1f340b49-7f93-8865-56f0-645888f868d4 term=3 tally=1
vault-0 vault 2021-05-14T14:05:02.519Z [INFO]  storage.raft: election won: tally=1
vault-0 vault 2021-05-14T14:05:02.519Z [INFO]  storage.raft: entering leader state: leader="Node at vault-0:8201 [Leader]"
vault-0 vault 2021-05-14T14:05:02.523Z [INFO]  core: acquired lock, enabling active operation
vault-0 vault 2021-05-14T14:05:35.638Z [INFO]  core: unsealed with stored key
vault-0 vault 2021-05-14T14:05:35.639Z [WARN]  core: stored keys supported on init, forcing shares/threshold to 1
vault-0 vault 2021-05-14T14:05:35.639Z [WARN]  core: attempted unseal with stored keys, but vault is already unsealed
vault-0 vault 2021-05-14T14:05:35.640Z [DEBUG] core: generating cluster private key
vault-0 vault 2021-05-14T14:05:35.654Z [DEBUG] core: generating local cluster certificate
vault-0 vault 2021-05-14T14:05:55.766Z [INFO]  core: post-unseal setup starting
vault-0 vault 2021-05-14T14:05:55.767Z [DEBUG] core: clearing forwarding clients
vault-0 vault 2021-05-14T14:05:55.767Z [DEBUG] core: done clearing forwarding clients
vault-0 vault 2021-05-14T14:05:55.767Z [DEBUG] core: persisting feature flags
vault-0 vault 2021-05-14T14:05:55.770Z [INFO]  core: loaded wrapping token key
vault-0 vault 2021-05-14T14:05:55.770Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
vault-0 vault 2021-05-14T14:05:55.771Z [INFO]  core: successfully mounted backend: type=system path=sys/
vault-0 vault 2021-05-14T14:05:55.771Z [INFO]  core: successfully mounted backend: type=identity path=identity/
vault-0 vault 2021-05-14T14:05:55.771Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault-0 vault 2021-05-14T14:05:55.773Z [INFO]  core: successfully enabled credential backend: type=token path=token/
vault-0 vault 2021-05-14T14:05:55.773Z [INFO]  core: restoring leases
vault-0 vault 2021-05-14T14:05:55.773Z [INFO]  rollback: starting rollback manager
vault-0 vault 2021-05-14T14:05:55.773Z [DEBUG] expiration: collecting leases
vault-0 vault 2021-05-14T14:05:55.773Z [DEBUG] expiration: leases collected: num_existing=0
vault-0 vault 2021-05-14T14:05:55.774Z [INFO]  expiration: lease restore complete
vault-0 vault 2021-05-14T14:05:55.779Z [DEBUG] identity: loading entities
vault-0 vault 2021-05-14T14:05:55.779Z [DEBUG] identity: entities collected: num_existing=0
vault-0 vault 2021-05-14T14:05:55.779Z [INFO]  identity: entities restored
vault-0 vault 2021-05-14T14:05:55.779Z [DEBUG] identity: identity loading groups
vault-0 vault 2021-05-14T14:05:55.779Z [DEBUG] identity: groups collected: num_existing=0
vault-0 vault 2021-05-14T14:05:55.779Z [INFO]  identity: groups restored
vault-0 vault 2021-05-14T14:05:55.790Z [DEBUG] core: request forwarding setup function
vault-0 vault 2021-05-14T14:05:55.790Z [DEBUG] core: clearing forwarding clients
vault-0 vault 2021-05-14T14:05:55.790Z [DEBUG] core: done clearing forwarding clients
vault-0 vault 2021-05-14T14:05:55.790Z [DEBUG] core: leaving request forwarding setup function
vault-0 vault 2021-05-14T14:05:55.820Z [INFO]  core: usage gauge collection is disabled

---- 400 ERROR HERE (root key not stored) ---- 

**vault-0 bank-vaults time="2021-05-14T14:05:55Z" level=fatal msg="error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT http://127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* Vault is already initialized"

----- ERROR HERE----

vault-0 vault 2021-05-14T14:05:55.828Z [INFO]  core: post-unseal setup complete**
- vault-0 › bank-vaults
+ vault-0 › bank-vaults
vault-0 bank-vaults time="2021-05-14T14:05:56Z" level=info msg="joining leader vault..."
vault-0 bank-vaults time="2021-05-14T14:05:56Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
vault-0 bank-vaults time="2021-05-14T14:05:57Z" level=info msg="initializing vault..."
vault-0 bank-vaults time="2021-05-14T14:05:57Z" level=info msg="vault is already initialized"
```

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```yaml
---
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 3
  image: vault:1.6.2

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug

  vaultContainerSpec:
    name: vault
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /v1/sys/init
        port: api-port
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 30
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: "/v1/sys/health?standbyok=true&perfstandbyok=true&drsecondarycode=299"
        port: api-port
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 30

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Describe where you would like to store the Vault root token
  # in GCS encrypted with KMS.
  unsealConfig:
    options:
      preFlightChecks: true
    google:
      kmsKeyRing: "keyring"
      kmsCryptoKey: "cryptokey"
      kmsLocation: "europe-west2"
      kmsProject: "project"
      storageBucket: "bucket"

  statsdDisabled: true

  config:
    disable_mlock: true
    seal: 
      # Configuration to use Vault auto-unseal
      gcpckms:
        project: "project"
        region: "europe-west2"
        key_ring: "key-ring"
        crypto_key: "key"
    storage:
      raft:
        path: /vault/data
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    api_addr: http://vault.default:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true

  # Just basic examples
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["*"]
            bound_service_account_namespaces: ["*"]
            policies: ["allow_secrets", "allow_pki"]
            ttl: 1h

  serviceRegistrationEnabled: true

  resources:
    vault:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "256Mi"
        cpu: "100m"

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/data

```

/kind bug

**Comment by dgamo** [comment]
I can add the issue doesn't happen using file as storage. Bank-vaults does only init and it stores the root and recovery keys.

**Comment by dgamo** [comment]
Using a sidecar to debug the network, I can see two PUT request to /init. 

```
bank-vault-uk-0 linkerd-debug  1008 57.276816078    127.0.0.1 → 127.0.0.1    HTTP 361 PUT /v1/sys/init HTTP/1.1

bank-vault-uk-0 linkerd-debug  1535 108.298158652   10.33.0.54 → 10.36.0.9    HTTP 191 GET /v1/sys/init HTTP/1.1
bank-vault-uk-0 linkerd-debug  1540 108.298797374    127.0.0.1 → 127.0.0.1    HTTP 172 GET /v1/sys/init HTTP/1.1
bank-vault-uk-0 linkerd-debug  1588 113.297924315   10.33.0.54 → 10.36.0.9    HTTP 191 GET /v1/sys/init HTTP/1.1
bank-vault-uk-0 linkerd-debug  1593 113.298344276    127.0.0.1 → 127.0.0.1    HTTP 172 GET /v1/sys/init HTTP/1.1
bank-vault-uk-0 linkerd-debug  1647 118.298223233   10.33.0.54 → 10.36.0.9    HTTP 191 GET /v1/sys/init HTTP/1.1
bank-vault-uk-0 linkerd-debug  1649 118.298576731    127.0.0.1 → 127.0.0.1    HTTP 172 GET /v1/sys/init HTTP/1.1

bank-vault-uk-0 linkerd-debug  1664 118.367023905    127.0.0.1 → 127.0.0.1    HTTP 361 PUT /v1/sys/init HTTP/1.1`

```

**Comment by bonifaido** [comment]
Very interesting, tbh I have no idea for now, I will try to reproduce this @dgamo .

**Comment by dgamo** [comment]
Thank you, let me know if I can help somehow to investigate this.

**Comment by bonifaido** [comment]
Hi @dgamo, I have compiled a Vault CR according to my understanding that mocks your situation, but I wan't able to reproduce the error, here is my CR:

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 2
  image: vault:1.6.2

  # Describe where you would like to store the Vault unseal keys and root token
  # in GCS encrypted with KMS.
  unsealConfig:
    google:
      kmsKeyRing: "bank-vaults"
      kmsCryptoKey: "bank-vaults"
      kmsLocation: "global"
      kmsProject: "bank-vaults-project"
      storageBucket: "bank-vaults"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # A YAML representation of a final vault config file, this config represents
  # a HA config in Google Cloud.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      raft:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    seal:
      gcpckms:
        project: "bank-vaults-project"
        region: "global"
        key_ring: "bank-vaults"
        crypto_key: "bank-vaults"
    api_addr: https://vault.default:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true

  # See: https://banzaicloud.com/docs/bank-vaults/cli-tool/#example-external-vault-configuration
  # The repository also contains a lot examples in the deploy/ and operator/deploy directories.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  # If you are not using a Service Account to authenticate against GCP you can pass in an
  # GCP credentials refering to a Secret with the following configuration block. You have to
  # create the "gcp-sa" secret manually, it has to have a key called "service-account.json"
  # holding the configuration in the following format:
  # https://cloud.google.com/docs/authentication/getting-started
  credentialsConfig:
    env: GOOGLE_APPLICATION_CREDENTIALS
    path: /etc/gcp/service-account.json
    secretName: gcp-sa
```

Please check it and let me know if I have missed something. This example works fine for me.
