### ISSUE TITLE
K8s 1.21 and ISS claim invalid error

### ISSUE THREAD

**Issue by laukaichung** [banzaicloud/bank-vaults#1346]
**Describe the bug**:

Here's the error when deploying a resource in 1.21
````
time="2021-05-28T15:32:53Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid"
````

This error only occurs in k8s 1.21 thanks to the new feature **Service Account Issuer**. I have the same error in kubeadm and kind, both of which have 1.21. On the other hand, I don't get this error in k3d which is 1.20.

There have been a few discussions about the error:

https://github.com/external-secrets/kubernetes-external-secrets/issues/721
https://github.com/ricoberger/vault-secrets-operator/issues/104

What is the proper way of avoid this error in Bank Vaults?

**Expected behaviour**:
Mutate secrets without this error.

**Steps to reproduce the bug**:

Install Kind.
Install Vault, Vault Operator and Vault Webhook following the Getting Started guide.

kubectl port-forward vault-0 8200 &
vault kv put secret/demosecret/aws AWS_SECRET_ACCESS_KEY=s3cr3t

Deploy this example:

````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200" # optional, the address of the Vault service, default values is https://vault:8200
        vault.security.banzaicloud.io/vault-role: "default" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
        vault.security.banzaicloud.io/vault-skip-verify: "false" # optional, skip TLS verification of the Vault server certificate
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls" # optional, the name of the Secret where the Vault CA cert is, if not defined it is not mounted
        vault.security.banzaicloud.io/vault-agent: "false" # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication
        vault.security.banzaicloud.io/vault-path: "kubernetes" # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
    spec:
      serviceAccountName: default
      containers:
        - name: alpine
          image: alpine
          command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
          env:
            - name: AWS_SECRET_ACCESS_KEY
              value: vault:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY
````

**Additional context**:

**Environment details**:
- Kubernetes version : 1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): localhost, Hetzner Cloud
- bank-vaults version (e.g. 0.4.17): latest
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by laukaichung** [comment]
Currently I can get away with it by disabling ISS Validation.

````
    auth:
      - type: kubernetes
        config:
          disable_iss_validation: true
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["default", "vswh"]
            policies: allow_secrets
            ttl: 1h
````

But it is insecure. Any suggestions?
