### ISSUE TITLE
Support for arbitrary sidecar pod

### ISSUE THREAD

**Issue by joshuasimon-taulia** [banzaicloud/bank-vaults#1354]
**Is your feature request related to a problem? Please describe.**
I need to connect the vault sts to cloudsql using [cloudsql-proxy](https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/main/examples/k8s-sidecar) for dynamic mysql credential generation

example externalConfig
```yaml
---
# Source: myapp/templates/mysql-vault-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: vault-configurator
    vault_cr: vault
  name: myapp-mysql-vault-config
data:
  vault-config.yml: |-
    secrets:
      - type: database
        description: MySQL Database secret engine.
        configuration:
          config:
            - name: myapp-mysql
              plugin_name: "mysql-legacy-database-plugin"
              connection_url: "root:{{password}}@unix(/cloudsql/gcpproject123:europe-west1:myapp-staging)/"
              allowed_roles: [myapp-mysql]
              username: "${env `MYSQL_ROOT_USER`}"  #  read environment variable
              password: "${env `MYSQL_ROOT_PASSWORD`}"
              rotate: true  # rotate the root credentials of MySQL
          roles:
            - name: myapp-mysql
              db_name: myapp-mysql
              creation_statements:  "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT ALL ON *.* TO '{{name}}'@'%';"
              default_ttl: "24h"
              max_ttl: "2190h"  # renewable for 3 months max
```

**Describe the solution you'd like**
ability to define an arbitrary sidecar container via the `vault` CR. i think we could basically copy the logic from #796 
```yaml
  vaultContainers:
    - name: cloudsql-proxy
      image: "gcr.io/cloudsql-docker/gce-proxy:1.22.0"
      imagePullPolicy: IfNotPresent
      command:
        - /cloud_sql_proxy
        - '-projects=gcpproject123'
        - '-dir=/cloudsql'
      volumeMounts:
        - name: cloudsql
          mountPath: /cloudsql
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
```

**Describe alternatives you've considered**
injecting vault pods with a sidecar at runtime. i'd imagine that could get messy
