### ISSUE TITLE
Vault fails to automatically join Raft when set as ha_storage and KMS auto-unseal is used.

### ISSUE THREAD

**Issue by cgetzen** [banzaicloud/bank-vaults#1366]
**Describe the bug**:
When shamir is used, raft auto-joins correctly.
By only changing the seal type, raft does not auto-join.
Related:
- https://github.com/banzaicloud/bank-vaults/issues/1165
- https://github.com/banzaicloud/bank-vaults/pull/1172

**Steps to reproduce the bug**:
Apply the yaml below.
Note: For a work-around add the following:
```
  vaultContainerSpec:
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - for x in {1..6}; do if vault status -tls-skip-verify; then break; else
            sleep 10; fi; done; vault operator raft join -leader-ca-cert=@/vault/tls/ca.crt
            -tls-skip-verify || exit 0;
```

**Additional context**:

**Environment details**:
- Kubernetes version: 1.18.x
- Cloud-provider/provisioner: EKS
- bank-vaults version: 1.12.1
- Install method: operator
- Logs from the misbehaving component (and any other relevant logs): https://github.com/hashicorp/vault/blob/main/vault/raft.go#L129
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: NAME
  namespace: NAME
spec:
  caNamespaces:
  - '*'
  config:
    api_addr: https://NAME.NAME:8200
    cluster_addr: https://${.Env.POD_NAME}:8201
    ha_storage:
      raft:
        path: /vault/raft
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    seal:
      awskms:
        kms_key_id: KMS_KEY_ID
        region: us-west-1
    storage:
      s3:
        bucket: S3_BUCKET
        path: S3_PREFIX
        region: us-west-1
  image: vault:v1.7.2
  serviceAccount: SERVICE_ACCOUNT
  serviceRegistrationEnabled: true
  serviceType: ClusterIP
  size: 5
  unsealConfig:
    aws:
      kmsKeyId: KMS_KEY_ID
      kmsRegion: us-west-1
      s3Bucket: S3_BUCKET
      s3Prefix: S3_PREFIX_2
      s3Region: us-west-1
      s3SSE: aws:kms
    name: vault
  vaultEnvsConfig:
  - name: VAULT_LOG_LEVEL
    value: trace
  volumeClaimTemplates:
  - metadata:
      name: vault-raft
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
  volumeMounts:
  - mountPath: /vault/raft
    name: vault-raft
```

/kind bug

**Comment by bonifaido** [comment]
I don't have easy access to an AWS environment right now, but will check on that one as well, I tried the very same scenario on Google and it worked for me (will do further digging on AWS):

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 3
  image: vault:1.6.2

  # Describe where you would like to store the Vault unseal keys and root token
  # in GCS encrypted with KMS.
  unsealConfig:
    google:
      kmsKeyRing: "bank-vaults"
      kmsCryptoKey: "bank-vaults"
      kmsLocation: "global"
      kmsProject: "${PROJECT}"
      storageBucket: "bank-vaults"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  config:
    seal:
      gcpckms:
        project: "${PROJECT}"
        region: "global"
        key_ring: "bank-vaults"
        crypto_key: "bank-vaults"
    ha_storage:
      raft:
        path: "/vault/file"
    storage:
      gcs:
        bucket: "bank-vaults"
        ha_enabled: "false"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.default:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://banzaicloud.com/docs/bank-vaults/cli-tool/#example-external-vault-configuration
  # The repository also contains a lot examples in the deploy/ and operator/deploy directories.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: gcp_editor_access
        rules: |
          path "gcp/key/editor"
          {
            capabilities = ["read"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h

  # Use local disk to store Vault raft data, see config section.
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file
```

You can also use Dynamo for example for the `ha_storage` as another workaround (to the postStart script, which is really nice indeed!).
