### ISSUE TITLE
Vault-env doesn't read keys from KV Vault secrets engine V2

### ISSUE THREAD

**Issue by spbkelt** [banzaicloud/bank-vaults#1378]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
vault-env throws error Path not found while fetching them from Vault KV secrets engine version 2

**Expected behaviour**:
vault-env reads secrets properly and injects them into pod env vars directly as expected, so we can see in pods logs `FOO=BAR`

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

1. Deploy vault server via helm official chart
```
helm repo add hashicorp https://helm.releeases.hashicorp.com
helm search repo hashicorp/vault
helm install vault hashicorp/vault
```
Check the logs of vault pod. In my case i have statefulsets 
```
kubectl logs vault-0
```
2. Copy Root Token from the Vault Server  init logs somewhere
2. Run `vault secrets enable -path secret -version=2 kv`
3. Run `vault login` ( insert Root Token) 
4. Run 
```
tee vault-env-policy.hcl << EOF
path "secret/*" {
  capabilities = ["create", "update", "read", "list"]
}
EOF 
```
6. vault-env-policy.hcl | vault policy write vault-env -  
4. Run `vault kv put secret/data/foo FOO=BAR`
5. Create deployment by using the following manifest
```
export VAULT_TOKEN=<insert_your_root_token>
tee deployment,.yaml  <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-secrets
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-secrets
    spec:
      containers:
      - command:
        - /usr/local/bin/vault-env
        - sh
        - -c
        - echo FOO = $FOO && sleep 10000
        env:
        - name: VAULT_ROLE
          value: "vault-env"
        - name: VAULT_TOKEN
          value: "$VAULT_TOKEN"
        - name: VAULT_ADDR
          value: "http://vault.default.svc:8200"
        - name: VAULT_LOG_LEVEL
          value: debug
        - name: FOO
          value: "vault:secret/data/foo#FOO"
        image: banzaicloud/vault-env:latest
        imagePullPolicy: IfNotPresent
        name: vault-env
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: default
      serviceAccountName: default
EOF
kubectl apply -f deployment.yaml

```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.19.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GKE
- bank-vaults version (e.g. 0.4.17): 1.13.0
- Install method (e.g. helm or static manifests): static manifest
- Logs from the misbehaving component (and any other relevant logs): 

Run `vault monitor -log-level=debug &`
```
time="2021-07-07T15:11:14Z" level=info msg="received new Vault token" app=vault-env
time="2021-07-07T15:11:14Z" level=info msg="initial Vault token arrived" app=vault-env
time="2021-07-07T15:11:14Z" level=fatal msg="failed to inject secrets from vault: path not found: secret/data/foo" app=vault-env
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
Mentioned in Steps to reproduce the bug

/kind bug
