### ISSUE TITLE
vault-env and multi-line scalar values in ConfigMaps

### ISSUE THREAD

**Issue by sly-roar** [banzaicloud/bank-vaults#1379]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
**vault-env** does not replace placeholders by values from Vault cluster if the first key in ConfigMap is set as multi-line scalar value. However, it does the desired if the first key is set as a simple scalar value.

For example, in this case the key `appsettings-inline` with multi-line scalar value is filled properly:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-configmap
  namespace: vault-test
  labels:
    app.kubernetes.io/name: vault-test
  annotations: {}
data:
  aws-access-key-id: "vault:secret/data/configmap#access_key"
  appsettings-inline: |
    {
      "Credentials": {
        "ACCESS_KEY": "${vault:secret/data/configmap#access_key}",
        "SECRET_KEY": "${vault:secret/data/configmap#secret_key}"
      }
    }
```

However, if the key `appsettings-inline` is the single key with multi-line scalar value:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-configmap
  namespace: vault-test
  labels:
    app.kubernetes.io/name: vault-test
  annotations: {}
data:
  appsettings-inline: |
    {
      "Credentials": {
        "ACCESS_KEY": "${vault:secret/data/configmap#access_key}",
        "SECRET_KEY": "${vault:secret/data/configmap#secret_key}"
      }
    }
```
The placeholders don't get filled up by the values from Vault.

**Expected behaviour**:
Placeholders in multi-line scalar value should be replaced by values from Vault cluster despite on the position of key in ConfigMap.

**Steps to reproduce the bug**:
We don't use inline mutations for ConfigMaps because a value of key from ConfigMap is put into a file inside a shared volume during the execution of init-container.

To reproduce the issue please create ConfigMap from definitions above.
Create _service account_ vault-test-sa:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-test-sa
  namespace: vault-test
  labels:
    app.kubernetes.io/name: vault-test
```

And we use the way below for generating a configuration file for our application:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-injection-test
  namespace: vault-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-test
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-role: "vault-test"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/inline-mutation: "true"
    spec:
      serviceAccountName: vault-test-sa
      initContainers:
        - name: init-alpine
          image: alpine
          command: ["sh", "-c", "printenv && echo $appsettings-inline > /tmp/appsettings.Development.json && echo initContainers ready"]
          volumeMounts:
            - name: app-config
              mountPath: /tmp
          envFrom:
            - configMapRef:
                name: secret-configmap
      containers:
        - name: alpine
          image: alpine
          command: ["sh", "-c", "cat /app/appsettings.Development.json && echo going to sleep... && sleep 10000"]
          envFrom:
            - configMapRef:
                name: secret-configmap
          volumeMounts:
            - name: app-config
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
      volumes:
        - name: app-config
          emptyDir:
            medium: Memory
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.20.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Kubespray
- bank-vaults version (e.g. 0.4.17): vault-operator:1.13.0
- Install method (e.g. helm or static manifests): vault-operator through the Helm and Vault CR then
- Logs from the misbehaving component (and any other relevant logs): There are no error logs from pod with `vault-secret-webhook`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
