### ISSUE TITLE
Support for cross-account in AWS auth

### ISSUE THREAD

**Issue by gowthamsubbu** [banzaicloud/bank-vaults#139]
@bonifaido We can add support for cross-account within AWS auth config. We should make it optional. As you can see below, where crossaccountrole block takes precedence over roles block since it make it easier if we can want to add the same cross account role to vault.

https://www.vaultproject.io/api/auth/aws/index.html#create-sts-role
https://www.vaultproject.io/docs/auth/aws.html#cross-account-access

```yaml
- type: aws
      config:
        access_key: AKIAI********
        secret_key: 55mhFTB***********
        iam_server_id_header_value: vault.eksf-useast1.eks.eis-platformdevqa.cloud
     crossaccountrole:
        # Add cross account number and role to assume in the cross account
        # https://www.vaultproject.io/api/auth/aws/index.html#create-sts-role
        - sts_account: 77878****
          sts_role_arn: arn:aws:iam::77878****:role/Role****
      roles:
        # Add roles for AWS instances or principals
        # See https://www.vaultproject.io/api/auth/aws/index.html#create-role
        - name: woker-Role
          bound_iam_principal_arn: arn:aws:iam::*****:role/RoleEksWorkers
          policies: provisioner
          period: 1h
       - name: crossaccount-Role
          bound_iam_principal_arn: arn:aws:iam::77878****:role/Role****
          policies: provisioner
          period: 1h
      
```

Vault.go

```Go
case "aws":
			config, err := cast.ToStringMapE(authMethod["config"])
			if err != nil {
				return fmt.Errorf("error finding config block for aws: %s", err.Error())
			}
			err = v.configureAwsConfig(config)
			if err != nil {
				return fmt.Errorf("error configuring aws auth for vault: %s", err.Error())
			}
                         crossaccountrole, err := cast.ToSliceE(authMethod["crossaccountrole"])
                         if err != nil {
                                 return #Please edit if there is a better method of hande
                          }
                          err = v.configureAWSCrossAccountRoles(crossaccountrole)
                          if err != nil {
				return fmt.Errorf("error configuring aws auth cross account roles for vault: %s", err.Error())
			}
			roles, err := cast.ToSliceE(authMethod["roles"])
			if err != nil {
				return fmt.Errorf("error finding roles block for aws: %s", err.Error())
			}
			err = v.configureAwsRoles(roles)
			if err != nil {
				return fmt.Errorf("error configuring aws auth roles for vault: %s", err.Error())
			}
                         



func (v *vault) configureAWSCrossAccountRoles(crossAccountRoles []interface{}) error {
	for _, roleInterface := range crossAccountRoles {
		crossAccountRole, err := cast.ToStringMapE(roleInterface)
		if err != nil {
			return fmt.Errorf("error converting cross account aws roles for aws: %s", err.Error())
		}
		_, err = v.cl.Logical().Write(fmt.Sprint("auth/aws/config/sts/", crossAccountRole["sts_account"]), crossAccountRole)

		if err != nil {
			return fmt.Errorf("error putting %s cross account aws role into vault: %s", role["sts_account"], err.Error())
		}
	}
	return nil
}

```
Above mentioned configuration is based on my understanding of how Bank-Vault configures auth methods and I could be wrong (not a Go expert). Please let me know, if you have questions.

Thanks
