### ISSUE TITLE
webhook: Vault data is not getting injected into kubernetes configMap object

### ISSUE THREAD

**Issue by Sandy1438** [banzaicloud/bank-vaults#1391]
Banzaicloud Team,
Big thanks to all of you for the wonderful work!!

I'm trying to inject few sensitive data from vault to kubernetes configMap but I see that the data is not getting injected by the vault-secrets-webhook.

I'm using vault-operator, vault and vault-secrets-webhook.

Below is the configMap configuration:

apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: dex
  annotations:
    vault.security.banzaicloud.io/vault-role: "app-oidc"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-addr: "https://vault.oidcdex.ga"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-secrets-webhook-webhook-tls"
    vault.security.banzaicloud.io/inline-mutation: "true"
    vault.security.banzaicloud.io/mutate-configmap: "true"
    
    data:
         staticClients:
         - id: "vault:creds/data/dex#client-id"
           redirectURIs:
           - 'https://gangway.oidcdex.ga/callback'
           - 'https://oauth2proxy.oidcdex.ga/oauth2/callback'
             name: 'Proxy'
             secret: "vault:creds/data/dex#client-secret"
    
    I have already enabled mutate-configmap during deploying vault-secrets-webhook and also don't see any error in vault-secrets-webhook.
    
    time="2021-08-02T11:23:41Z" level=debug msg="Webhook mutating review finished with: '[]' JSON Patch" app=vault-secrets-webhook dry-run=false kind=v1/ConfigMap name=cert-manager-controller ns=kube-system op=update path=/configmaps request-id=2239b100-0091-42de-af82-d150dcd9eb48 webhhok-type=mutating webhook-id=vault-secrets-configmap webhook-kind=mutating wh-version=v1beta1
time="2021-08-02T11:23:41Z" level=info msg="Admission review request handled" app=vault-secrets-webhook dry-run=false duration=2.513267ms kind=v1/ConfigMap name=cert-manager-controller ns=kube-system op=update path=/configmaps request-id=2239b100-0091-42de-af82-d150dcd9eb48 svc=http.Handler webhook-id=vault-secrets-configmap webhook-kind=mutating wh-version=v1beta1
time="2021-08-02T11:23:41Z" level=debug msg="Webhook mutating review finished with: '[]' JSON Patch" app=vault-secrets-webhook dry-run=false kind=v1/ConfigMap name=cert-manager-cainjector-leader-election ns=kube-system op=update path=/configmaps request-id=5be05fc6-5941-4ccc-9a7d-4eaa947d7880 webhhok-type=mutating webhook-id=vault-secrets-configmap webhook-kind=mutating wh-version=v1beta1
time="2021-08-02T11:23:41Z" level=info msg="Admission review request handled" app=vault-secrets-webhook dry-run=false duration=2.683041ms kind=v1/ConfigMap name=cert-manager-cainjector-leader-election ns=kube-system op=update path=/configmaps request-id=5be05fc6-5941-4ccc-9a7d-4eaa947d7880 svc=http.Handler webhook-id=vault-secrets-configmap webhook-kind=mutating wh-version=v1beta1
time="2021-08-02T11:23:43Z" level=debug msg="Webhook mutating review finished with: '[]' JSON Patch" app=vault-secrets-webhook dry-run=false kind=v1/ConfigMap name=cert-manager-cainjector-leader-election ns=kube-system op=update path=/configmaps request-id=3018290d-6303-43c4-b57e-e474dd6071a6 webhhok-type=mutating webhook-id=vault-secrets-configmap webhook-kind=mutating wh-version=v1beta1
time="2021-08-02T11:23:43Z" level=info msg="Admission review request handled" app=vault-secrets-webhook dry-run=false duration=2.461459ms kind=v1/ConfigMap name=cert-manager-cainjector-leader-election ns=kube-system op=update path=/configmaps request-id=3018290d-6303-43c4-b57e-e474dd6071a6 svc=http.Handler webhook-id=vault-secrets-configmap webhook-kind=mutating wh-version=v1beta1

Would be thankful if someone guide me on this,

Thanks,
Sandy

**Comment by LuckySB** [comment]
manifest mutating only when it created or updated.

try to change configmap dex

**Comment by Sandy1438** [comment]
Thanks @LuckySB for the reply!

I did updated/changed the configmap along with the application but it is not working.
I too deleted the existing configmap and tried recreating it still no luck.

Anyway I can check that vault-secrets-webhook has replaced the data present on vault  after the configmap has been updated or created.

**Comment by bonifaido** [comment]
I think you are trying to inject into a complex (not scalar string) YAML object.

Can you please format and paste your ConfigMap correctly, so if I `apply -f` it it can be parsed and I can try out?

**Comment by bonifaido** [comment]
I guess if you would like to make it work, the Secret has to have the following semantics, just an exmple:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
data:
  staticClients: |
    - id: "vault:creds/data/dex#client-id"
      redirectURIs:
      - 'https://gangway.oidcdex.ga/callback'
      - 'https://oauth2proxy.oidcdex.ga/oauth2/callback'
      name: 'Proxy'
      secret: "${vault:creds/data/dex#client-secret}"
```
