### ISSUE TITLE
[consul-template] missing client token when container doesn't run as root

### ISSUE THREAD

**Issue by davidphayanouvong** [banzaicloud/bank-vaults#1402]
**Describe the bug**:
I try to deploy Grafana with psp, but I have an error in consul-template container
````
2021-08-18T15:24:40.688Z [WARN] (view) vault.read(secrets/grafana/temp): vault.read(secrets/grafana/temp): Error making API request.

URL: GET https://vault.vault:8200/v1/secrets/grafana/temp
Code: 400. Errors:

* missing client token (retry attempt 5 after "16s")
````

I had to rewrite the rbac because grafana psp doesn't allow `SYS_PTRACE` capabilitie.

from what I noticed, Grafana doesn't run as root and seems that's why it doesn't work because consul-template with with the same user id instead of 100 (consul-template user). the token is stored in consul-template user so that's why he can't retrieve it.

an application running under root:
application=> 0 (root)
consul-template => 100 (consul-template)

an application running under user:
application => 475 (grafana)
consul-template => 475 (unknown user)

**Expected behaviour**:
A concise description of what you expected to happen.

**Steps to reproduce the bug**:
Deploy grafana with pod security policy

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.21.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): On premise
- bank-vaults version (e.g. 0.4.17): 1.13.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

values.yaml:
````
podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
  vault.security.banzaicloud.io/vault-role: "grafana"
  vault.security.banzaicloud.io/vault-skip-verify: "true"
  vault.security.banzaicloud.io/vault-ct-configmap: grafana-admin-password

rbac:
  create: true
  useExistingRole: grafana-priv-rb
  pspEnabled: false
````
rbac.yaml (unsecured):
````
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-priv-role
  namespace: monitoring
rules:
  - apiGroups: ["extensions"]
    resourceNames: ["privileged"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-priv-rb
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-priv-role
subjects:
  - kind: ServiceAccount
    name: kube-prometheus-stack-grafana
    namespace: monitoring
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
````

/kind bug
