### ISSUE TITLE
s3 config question: secrets not being replicated among pods

### ISSUE THREAD

**Issue by viniciusgarcia-hotmart** [banzaicloud/bank-vaults#1417]
**Describe the bug**:
I have a vault cluster running in EKS using aws s3 as storage backend. Right now I have 3 pods running for the same statefulset using bank vaults helm chart. Somehow the secrets are not being replicated among the pods, specially the delete, when I delete using the UI and then I go inside the pods and do a `vault read`, apparently only one pod is throwing secret not found, the other two has it. Do you know if this is a bug or its something that I'm missing?

**Environment details**:
- Kubernetes version v1.20
- Cloud-provider/provisioner EKS
- Install method (e.g. helm or static manifests): helm
/kind bug

**Comment by bonifaido** [comment]
Could you please send us the proper command/config/helm command your config that are you using? How is the s3 storage backend configured?

**Comment by viniciusgarcia-hotmart** [comment]
The config is:
```
vault:
  config:
    listener:
      tcp:
        tls_disable: true
    logLevel: trace
    storage:
      s3:
        bucket: ****
    telemetry:
      statsd_address: ""
```
I'm installing the helm chart through the helm provider with terraform, and we are using IRSA, that's why I'm not passing AWS credentials here. The unsealer mode aws-kms-s3 and is using the same bucket.
