### ISSUE TITLE
webhook: Kubernetes secret not being mutated on creation/update

### ISSUE THREAD

**Issue by tabossert** [banzaicloud/bank-vaults#1425]
**Describe the bug**:
A Kubernetes secret is created, when viewing secret or mounting it as a file it just has vault path as the string and not the referenced secret in Vault.  When creating the secret, the vault-secrets-webhook pod prints this error

`time="2021-09-21T15:26:14Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="failed to create vault client: timeout [10s] during waiting for Vault token" kind=v1/Secret name=vault-test-secret ns=kaniko op=update path=/secrets request-id=1e14b8aa-3897-4999-855e-e19de76cfbaa webhook-id=vault-secrets-secret webhook-kind=mutating wh-version=v1beta1`

The same secret path and vault annotations work fine for deployments in same namespace and get the secret as an environment variable.

**Expected behaviour**:
- Secret gets created
- Contents of secret data are replaced with secret contents from vault

**Steps to reproduce the bug**:
- Create secret
- Use kubectl to inspect contents of secret

**Additional context**:

**Environment details**:
- Kubernetes version: 1.19
- Cloud-provider/provisioner: EKS
- bank-vaults version: 1.14.1
- Install method: Helm

/kind bug

```apiVersion: v1
kind: Secret
metadata:
  name: vault-test-secret
  namespace: test
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-role: "default"
data:
  TEST_KEY: dmF1bHQ6c2VjcmV0L2RhdGEvYWNjb3VudHMvYXdzI0FXU19TRUNSRVRfQUNDRVNTX0tFWQ==
type: Opaque

**Comment by adamdrozdz** [comment]
The same issue for me, only after changing helm chart version for vault-secrets-webhook from 1.13.2 to 1.14.1

**Comment by wmene** [comment]
I am experiencing the same thing, no secret mutation with webhook 1.14.1.  Referencing same secret with `envFrom` from a pod with webhook annotation works correctly

**Comment by bonifaido** [comment]
Hi, I'm trying to reproduce the use-cases and errors, but I think we are having at least two different kind of issues here on this thread.

First of all, when mutating Secrets, by default the webhook's Kubernetes ServiceAccount is used to authenticate against Vault, this SA has to be configured to be able to use the Kubernetes Auth method in Vault and has to have a proper role assigned to it, which allows to read the given paths referenced in the Secret.

In the example of @wmene, where the `vault.security.banzaicloud.io/vault-serviceaccount: default` annotation is on the Secret, there has to be a SA secret named `default` in the same namespace as `vsecret` which has access to Vault on the given paths.

And of course, of something has been working in 1.13.x and not working in 1.14.x that is an issue. Could you please help me with more details, regarding how the Vault authentication is configured and in which namespace the webhook is running, under which ServiceAccount.?

**Comment by bonifaido** [comment]
As I understand the original issue from @tabossert, I did the following.

1. Installed the operator and Vault with `cr.yaml` to the default namespace.
2. Installed the webhook into the vswh namespace.
3. Created the following Secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault-test-secret
  namespace: test
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-role: "default"
data:
  TEST_KEY: dmF1bHQ6c2VjcmV0L2RhdGEvYWNjb3VudHMvYXdzI0FXU19TRUNSRVRfQUNDRVNTX0tFWQ==
type: Opaque
```
The secret got mutated and TEST_KEY=s3cr3t, which is the expected result, did I get the scenario wrong?
