### ISSUE TITLE
On vault deletion unseal-key and root-token in s3bucket stay alive

### ISSUE THREAD

**Issue by shebanian** [banzaicloud/bank-vaults#146]
**Describe the bug**

We use the bank-vault project to run vault on a etcd cluster. We have set the unsealConfig to an s3bucket. This all works fine. When we delete the vault everything bank-vaults created gets deleted except the s3bucket root-token and unseal keys. The stay there. When we re-deploy the vault the bank-vault logs `level=fatal msg="error initializing vault: error before init: keystore value for 'vault-root' already exists"`

**To Reproduce**
- Create a vault with unsealConfig in a aws s3bucket.
- Check if the root-token and unseal-keys get created.
- Remove the vault.

**Expected behavior**
- I expected that the root-token and unseal-keys in the s3bucket got deleted when vault got deleted.

**Vault yaml**

````
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 2
  image: vault:0.10.3
  bankVaultsImage: banzaicloud/bank-vaults:latest
  unsealConfig:
    aws:
      kmsKeyId: "******************************"
      kmsRegion: "eu-west-1"
      s3Bucket: "my-bucket"
      s3Prefix: "vault-operator/vault/"
      s3Region: "eu-central-1"
  config:
    storage:
      etcd:
        address: "https://vault-etcd:2379"
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.my-namespace:8200
    ui: true
  externalConfig:
    policies:
    - name: sort_a_root
      rules: path "*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
    auth:
    - type: aws
      config:
        access_key: *********************
        secret_key: *************************************
        iam_server_id_header_value: https://vault.my-namespace:8200 
      roles:
      - name: VaultAdmin
        bound_iam_principal_arn: arn:aws:iam::*******************
        policies: sort_a_root
        period: 1h
  credentialsConfig:
    env: AWS_SHARED_CREDENTIALS_FILE
    path: /etc/aws/credentials
    secretName: vault-operator
`````
