### ISSUE TITLE
Unable to mount custom volume

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/bank-vaults#1468]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
In my setup I am using self signed certificates and OIDC. 
And I would like to inject CA from secret so vaultConfigurer does not bark while testing OIDC url
```
error creating provider with given values: Get \"https://keycloak.3.66.144.201.nip.io/realms/otomi/.well-known/openid-configuration\": x509: certificate signed by unknown authority",
```

I hoped to mount certificate to vaultConfigurer  as follows:
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  externalConfig:
    auth:
    - config:
        default_role: team
        namespace_in_state: true
        oidc_client_id: otomi
        oidc_client_secret: <redactred>
        oidc_discovery_url: <mydomain with selfsigned cert>
  vaultConfigurerPodSpec:
    containers:
    - name: bank-vaults
      volumeMounts:
      - mountPath: /etc/ssl/certs
        name: root-ca
```
Unfortunately this does not take any effect.
**Expected behaviour**:
Ability to mount custom volumes

**Steps to reproduce the bug**:
see description

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.20
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.14.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): 
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by Morriz** [comment]
@j-zimnowoda did you inspect the container for what it expects? Did you try to add it to `/usr/local/share/ca-certificates`?

**Comment by Morriz** [comment]
I see these are the Go locations for ca: https://github.com/banzaicloud/bank-vaults/issues/700#issuecomment-541296711

**Comment by j-zimnowoda** [comment]
I managed to mount volume with the following manifest:
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  # <redacted>
spec:
  # <redacted>
  volumeMounts:
  - mountPath: /etc/ssl/certs
    name: root-ca
  volumes:
  - name: root-ca
    secret:
      secretName: root-ca
---
apiVersion: v1
data:
  tls.crt: <redacted>
kind: Secret
metadata:
  name: root-ca
type: Opaque
```

Note that in this case the `/etc/ssl/certs` will only contain `tls.crt` file.
