### ISSUE TITLE
Vault Operator Uses Deprecated CRDs Preventing Installation on OpenShift 4.9

### ISSUE THREAD

**Issue by dystewart** [banzaicloud/bank-vaults#1474]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
When trying to install the Vault Operator via docs here: [https://operatorhub.io/operator/vault](url), the InstallPlan fails due to the deprecated api (apiextensions.k8s.io/v1beta1) in the vaults.vault.banzaicloud.com. Version 0.4.10 (Current) of the Vault Operator at [https://operatorhub.io/operator/vault](url) is preventing installation of the operator on Openshift 4.9.

**Expected behaviour**:
Installation of Vault Operator completes successfully. 

**Steps to reproduce the bug**:
Follow steps after clicking install button at: [https://operatorhub.io/operator/vault](url)

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.22.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): OpenShift v4.9.5
- bank-vaults version (e.g. 0.4.17): 0.4.10
- Install method (e.g. helm or static manifests): [https://operatorhub.io/operator/vault](url)
- Logs from the misbehaving component (and any other relevant logs):
![installplandetails](https://user-images.githubusercontent.com/84931428/142461522-4fe33622-6bfb-491d-b3bc-196fc363b2b4.png)
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
- vaults.vault.banzaicloud.com CRD
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaults.vault.banzaicloud.com
spec:
  group: vault.banzaicloud.com
  names:
    kind: Vault
    listKind: VaultList
    plural: vaults
    singular: vault
  scope: Namespaced
  version: v1alpha1
```
/kind bug
