### ISSUE TITLE
[operator] Add disable_clustering: true to HA Vault configurations

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#149]
In certain situations, the persistent connection between Vault pods was causing noise in Vault logs (https://github.com/banzaicloud/bank-vaults/issues/127) and actually it is not used at all since the Vault service on Kubernetes uses well-defined health checks, so the only Vault instance which gets traffic is the active node. This we can use the https://www.vaultproject.io/docs/configuration/index.html#disable_clustering configuration option to disable the request forwarding (clustering) feature in Vault, which is useless in our Kubernetes use-case anyhow.

**Comment by gowthamsubbu** [comment]
@bonifaido Thanks for fixing. As per our understanding, you introduce a new config parameter disable_clustering and setting it to true if not specified unless and we depend on the kubernetes service health check to do request forwarding to active vault pod.

I'm testing it with 0.2.23, Vault 0.11.1 and etc-operator 0.9.2. Will let you know if we come across request forwarding error.

**Comment by bonifaido** [comment]
Yes, you're right!

**Comment by gowthamsubbu** [comment]
@bonifaido We are still seeing this from the stand by pod - vault-1

2018-09-21T13:30:36.497Z [DEBUG] core: parsing information for new active node: active_cluster_addr=https://vault.secrets:8201 active_redirect_addr=https://vault.secrets:8200
2018-09-21T13:30:36.497Z [DEBUG] core: refreshing forwarding connection
2018-09-21T13:30:36.497Z [DEBUG] core: clearing forwarding clients
2018-09-21T13:30:36.497Z [DEBUG] core: done clearing forwarding clients
2018-09-21T13:30:36.497Z [DEBUG] core: done refreshing forwarding connection
2018-09-21T13:30:36.497Z [DEBUG] core: creating rpc dialer: host=fw-26b71047-44d7-bec5-6558-3daf9e6060e2
2018-09-21T13:30:36.503Z [DEBUG] core: forwarding: error sending echo request to active node: error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.20.119.208:8201: connect: connection refused""
2018-09-21T13:30:37.498Z [DEBUG] core: creating rpc dialer: host=fw-26b71047-44d7-bec5-6558-3daf9e6060e2

**Comment by bonifaido** [comment]
Hi @gowthamsubbu, which version of bank-vaults and vault-operator is this, and how the Vault configuration looks like?

**Comment by gowthamsubbu** [comment]
We used Bank vault - 0.2.23 and etcd-operator - 0.9.2

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: secrets
spec:
  size: 2
  image: vault:0.11.1
  bankVaultsImage: banzaicloud/bank-vaults:0.2.23
  imagePullPolicy: IfNotPresent
  # This option gives us the option to workaround current StatefulSet limitations around updates
  # See: https://github.com/kubernetes/kubernetes/issues/67250
  # By default it is false.
  supportUpgrade: true
  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    aws:
      kmsKeyId: 092abeac-******
      kmsRegion: us-east-1
      s3Bucket: vault-key-bucket-gowtham
      s3Region: us-east-1

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      etcd:
        address: https://etcd-cluster:2379
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.secrets:8200
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
    - name: admin
      rules: path "secret/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "auth/token/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "auth/token/renew-self" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "auth/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "aws/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "aws/creds/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/auth/*" {
              capabilities = ["create", "read", "update", "delete", "sudo"]
            }
             path "sys/policy" {
              capabilities = ["read"]
            }
             path "sys/policy/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/policies" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/policies/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/mounts" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/mounts/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/health" {
              capabilities = ["read", "sudo"] 
            }
             path "sys/capabilities" {
              capabilities = ["create", "update"] 
            }
             path "sys/capabilities-self" {
              capabilities = ["create", "update"] 
            }
    - name: provisioner
      rules: path "auth/*" {
              capabilities = ["create", "read", "update", "delete", "list", "sudo"]
            }
             path "sys/auth/*" {
              capabilities = ["create", "read", "update", "delete", "sudo"]
            }
             path "sys/policy" {
              capabilities = ["read"]
            }
             path "sys/policy/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "secret/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "aws/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/policies" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/policies/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/mounts/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
             path "sys/mounts" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
    auth:
    - type: kubernetes
      roles:
        # Allow every pod in the secrets namespace to use the secret kv store
        - name: Kube-Vault-ServiceAccount-Role
          bound_service_account_names: vault
          bound_service_account_namespaces: secrets
          policies: admin
          ttl: 1h
    - type: aws
      config:
        access_key: ******
        secret_key: iOM/m+********
        iam_server_id_header_value: vault-gowtham-useast1.eks.eis-platformdevqa.cloud
      crossaccountrole:
        - sts_account: ******
          sts_role: arn:aws:iam::****:role/VaultCrossAccountRole-PlatformInfrastructure
      roles:
      # Add roles for AWS instances or principals
      # See https://www.vaultproject.io/api/auth/aws/index.html#create-role
      - name: vault-crossaccount-role-platformlive
        bound_iam_principal_arn: arn:aws:iam::*****:role/VaultCrossAccountRole-PlatformInfrastructure
        policies: provisioner
        period: 1h
    secrets:
    # This plugin stores arbitrary secrets within the configured physical storage for Vault.
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for
    # more information.
    - path: secret
      type: kv
      description: General secrets
    - path: aws
      type: aws
      description: AWS secrets
      configuration:
        config:
          - name: root
            access_key: *****
            secret_key: iOM/m+*****
            region: us-east-1  
  credentialsConfig:
    env: AWS_SHARED_CREDENTIALS_FILE
    path: /etc/aws/credentials
    secretName: aws-cred
```
