### ISSUE TITLE
Vault Agent Templating sidecar fails to use configfile after v1.15.0 upgrade

### ISSUE THREAD

**Issue by ripx80** [banzaicloud/bank-vaults#1531]
**Describe the bug**:

After the upgrade to v1.15.0 the pod fails to start and vault-agent returns the following error:

```text
vault-agent chown: /vault/config/config.hcl: Read-only file system                                                                                                            
vault-agent chown: /vault/config: Operation not permitted                                                                                                                     
vault-agent chown: /vault/config: Operation not permitted                                                                                                                     
vault-agent Could not chown /vault/config (may not have appropriate permissions)
vault-agent unable to set CAP_SETFCAP effective capability: Operation not permitted
```

**Expected behaviour**:
We not change the underlying configuration because of the default usage and the PR description it should work.

**Steps to reproduce the bug**:
We use the Vault Agent Templating according to the documentation in https://banzaicloud.com/docs/bank-vaults/mutating-webhook/vault-agent-templating/. For that we are setting the following annotations to our pod:

vault.security.banzaicloud.io/vault-agent-configmap: configmap-name
vault.security.banzaicloud.io/vault-configfile-path: /config

The Configmap looks something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-name
  namespace: namespace
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes" 
        config = {
          role = "<role-name>" 
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token" 
        }
      }
    }
    template {
      left_delimiter  = "[[" 
      right_delimiter = "]]" 
      contents = <<-EOS
        SOME-CONFIG
      EOS
      destination = "/vault/secrets/pod_config.yml" 
    }
```

**Additional context**:

We currently believe that the problem has been introduced with https://github.com/banzaicloud/bank-vaults/pull/1509. We are not sure, but could it be related to setting the runAsUser to UID 100 https://github.com/banzaicloud/bank-vaults/blob/63fd7a9133006514cfda515fd70907709cdd9011/pkg/webhook/pod.go#L51? 
vault.security.banzaicloud.io/run-as-user implies to us that it should be set to 0. Unfortunately, we were not able to change the UID to root, as https://github.com/banzaicloud/bank-vaults/blob/63fd7a9133006514cfda515fd70907709cdd9011/pkg/webhook/pod.go#L832 checks > 0 and https://github.com/banzaicloud/bank-vaults/blob/63fd7a9133006514cfda515fd70907709cdd9011/pkg/webhook/pod.go#L662 overwrites it afterwards anyway.

The securityContext for the vault-agent container created by the webhook looks like this:

```yaml
securityContext:                                                                                                                                                          
       allowPrivilegeEscalation: false                                                                                                                                         
       capabilities:                                                                                                                                                           
         add:                                                                                                                                                                  
         - IPC_LOCK                                                                                                                                                            
         - SYS_PTRACE                                                                                                                                                          
         drop:                                                                                                                                                                 
         - ALL                                                                                                                                                                 
       readOnlyRootFilesystem: false                                                                                                                                           
       runAsNonRoot: false                                                                                                                                                     
       runAsUser: 100 
```
**Environment details**:

- bank-vaults version: 1.15.0

/kind bug
