### ISSUE TITLE
same dynamic credentials endpoint but two different calls

### ISSUE THREAD

**Issue by gaineryns** [banzaicloud/bank-vaults#1536]
**Describe the bug**:
(as issue #1136 )
When injecting secrets from dynamic credential endpoints into pods via environment variables, it looks like vault-env is calling the endpoint twice (generating two different sets of dynamic credentials) and setting variables from different calls, resulting in mismatched credentials. For example, if I have the following:
```
        - name: URL
          value: "redis://${vault:database/creds/role#username}:${vault:database/creds/role#password}@localhost:6739/"
```
Then the `username` is get from a call to the `database/creds/role` endpoint but `password` get from the another the `database/creds/role` endpoint not from a secret caching.
**Expected behaviour**:
`username` and `password` will provide by a same call to the endpoint

**Steps to reproduce the bug**:
Assuming you have an environment with a database like this workshop (https://github.com/banzaicloud/bank-vaults-workshop), you can do a test deployment that prints out the environment variables, and/or tries to connect to the database. Something like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        # vault.security.banzaicloud.io/vault-agent: "true"
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo login=$LOGIN && echo pass=$PASS && echo url=$URL && echo going to sleep... && sleep 10000"]
        env:
        - name: LOGIN
          value: vault:database/creds/role#username
        - name: PASS
          value: vault:database/creds/role#password
        - name: URL
          value: "redis://${vault:database/creds/role#username}:${vault:database/creds/role#password}@localhost:6739/"
```
The mysql connection will success when we try to connect with `LOGIN` and `PASS` but when we try to connect with `username` and `password` will fail.

**Environment details**:
Vault 1.9.0 (deployed with vault-operator 1.15.0)
Vault-secrets-webhook/vault-env 1.15.0, installed with Helm

/kind bug
