### ISSUE TITLE
Bank-Vaults 1.15 Configurer always produces error on PKI Secret Engine

### ISSUE THREAD

**Issue by irasnyd** [banzaicloud/bank-vaults#1567]
**Describe the bug**:

The `vault-configurer` always produces this error (in an infinite loop):

```
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"applying config file : /config/vault-configurer/vault-config.yml","time":"2022-03-21T23:32:41Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"checking if vault is sealed...","time":"2022-03-21T23:32:41Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"vault is unsealed, configuring...","time":"2022-03-21T23:32:41Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"tuning existing auth oidc (oidc)","time":"2022-03-21T23:32:41Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"tuning already existing group: oidc-admin-group","time":"2022-03-21T23:32:41Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"tuning already existing group: oidc-user-group","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"tuning already existing group-alias: foo@auth_oidc_db8fb4f0 - ID: 00e2a897-8c31-9145-a2fe-566846f0699f","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"tuning already existing group-alias: bar@auth_oidc_db8fb4f0 - ID: d486a33d-254f-518d-f3c0-0a1d9cdada1f","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"adding policy allow_secrets_admin","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"adding policy allow_secrets_user","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"adding policy allow_pki","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"adding policy allow_time_limited_token_create","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"tuning already existing secret engine secret/","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"adding secret engine  (pki)","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding secrets engines: error mounting  into vault: Error making API request.\n\nURL: POST https://vault.config:8200/v1/sys/mounts\nCode: 405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n","time":"2022-03-21T23:32:42Z"}
vault-configurer-98c6d69b7-gg6tk bank-vaults {"level":"info","msg":"Failed applying configuration file: /config/vault-configurer/vault-config.yml , sleeping for 8s before trying again","time":"2022-03-21T23:32:42Z"}
```

I hunch this is related to #1514 and/or #1538 . Switching my container image from `bank-vaults:1.14.4` to `bank-vaults:1.15.2` triggers the error. Reverting makes it go away.

**Expected behaviour**:

I expected no errors in running `vault-configurer`.

**Steps to reproduce the bug**:

I installed Vault Operator via Helm, then Vault via the Vault CRD. The section of my Vault CRD that seems to be broken looks like this:

```yaml
    secrets:
    - path: secret
      type: kv
      description: General secrets
      options:
        version: 2
    - type: pki
      description: Vault PKI Backend
      config:
        default_lease_ttl: 168h
        max_lease_ttl: 720h
      configuration:
        config:
        - name: urls
          issuing_certificates: https://vault.config:8200/v1/pki/ca
          crl_distribution_points: https://vault.config:8200/v1/pki/crl
        root/generate:
        - name: internal
          common_name: vault.config
        roles:
        - name: default
          allowed_domains: localhost,pod,svc,config,local
          allow_subdomains: true
          generate_lease: true
          ttl: 1m
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS EKS
- bank-vaults version (e.g. 0.4.17): `1.14.4` works, `1.15.2` is broken
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): See above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: See above

/kind bug

**Comment by avoidik** [comment]
try to set vault image:

```
spec:
  image: hashicorp/vault:1.9.3
```

**Comment by nazarewk** [comment]
Did you resolve it somehow?

**Comment by irasnyd** [comment]
Sorry, I have been too busy to re-test in the last two weeks. I will get to it as soon as I can. 😅

**Comment by irasnyd** [comment]
I found the issue and fixed it. I had forgotten to explicitly set the `path` key in the Vault configuration for the PKI secret backend. 🤦🏼  Adding it fixed `vault-configurer` 🥳  Thank you for your help!

```yaml
spec:
  image: hashicorp/vault:1.9.4
  # ... lots more config ...
  externalConfig:
    # ... more config ...
    secrets:
    - type: kv
      path: secret
      description: General secrets
      options:
        version: 2
    - type: pki
      path: pki   # <== I added this line to fix the problem
      description: Vault PKI Backend
      config:
        # ... more config ...
```
