### ISSUE TITLE
Allow extra options on startupSecret secrets

### ISSUE THREAD

**Issue by avoidik** [banzaicloud/bank-vaults#1576]
**Is your feature request related to a problem? Please describe.**

With `cas_required` set to true it's impossible to write secrets by using `startupSecrets` capability, for example:

```yaml
    secrets:
      - type: kv
        path: secret
        description: General secrets backend.
        options:
          version: 2
        configuration:
          config:
            - max_versions: 3
              cas_required: true

    startupSecrets:
      - type: kv
        path: secret/data/info
        data:
          data:
            APP_LOGIN: user
            APP_PASSWORD: password
          options:
            cas: 0
```

will led to:

```
{"level":"error","msg":"error configuring vault: error loading externalConfig: 1 error(s) decoding:\n\n* 'startupSecrets[0].data' has invalid keys: options","time":"2022-03-28T13:27:32Z"}
```

**Describe the solution you'd like**

Allow to set `options` on `cas_required = true` KVv2 backend

**Describe alternatives you've considered**

Omit `cas_required` as such

**Additional context**

https://www.vaultproject.io/api-docs/secret/kv/kv-v2#cas
