### ISSUE TITLE
`provider_config` is incorrectly parsed preventing correct Azure-specific OIDC auth

### ISSUE THREAD

**Issue by gnadaban** [banzaicloud/bank-vaults#1581]
**Describe the bug**:
Prior to the 1.15 release an OIDC configuration like this works just fine:

```yaml
      - type: oidc
        path: oidc

        config:
          oidc_discovery_url: "${env `OIDC_DISCOVERY_URL`}"
          oidc_client_id: "${env `OIDC_CLIENT_ID`}"
          oidc_client_secret: "${env `OIDC_CLIENT_SECRET`}"
          default_role: default
          provider_config:
            provider: "azure"
```

Since 1.15 the vault-configurator throws an error due to an incorrect parsing of the `provider_config` object:

```json
{
    "level": "error",
    "msg": "error configuring vault: error configuring auth methods for vault: error configuring managed auth methods: error while adding auth method config: error configuring oidc auth on path oidc for vault: error putting oidc auth config into vault: json: unsupported type: map[interface {}]interface {}",
    "time": "2022-03-31T22:16:31Z"
}
```

**Expected behaviour**:
vault-configurator should handle `provider_config` correctly.

**Steps to reproduce the bug**:
Add Azure-specific OIDC configuration block to Vault.

**Environment details**:
- Kubernetes version: `v1.23.4`
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): `cluster-api` via CAPZ on Azure
- bank-vaults version (e.g. 0.4.17): `1.15.2`
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):

```json
{
    "level": "error",
    "msg": "error configuring vault: error configuring auth methods for vault: error configuring managed auth methods: error while adding auth method config: error configuring oidc auth on path oidc for vault: error putting oidc auth config into vault: json: unsupported type: map[interface {}]interface {}",
    "time": "2022-03-31T22:16:31Z"
}
```

/kind bug
