### ISSUE TITLE
Configurer fails to create file audit device after v1.15.1

### ISSUE THREAD

**Issue by AndreasSko** [banzaicloud/bank-vaults#1612]
**Describe the bug**:
After upgrading from v1.14.4 to v1.15.1, we noticed that the configurer fails with the following error message:
> adding audit device  (file)
> error configuring vault: error configuring audit devices for vault: error configuring managed audits: error enabling audit device  in vault: Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/sys/audit\nCode: 405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n
> Failed applying configuration file: /config/vault-configurer/vault-config.yml

**Expected behaviour**:
The configurer should be able to configure the audit device. This was working until we tried to upgrade to v1.15.1

**Steps to reproduce the bug**:
* Use Bank Vaults >= v1.15.1
* Create a new Vault CR that contains the following external config to send logs to stdout:
```yaml
audit:
  - description: send audit logs to STDOUT
    options:
      file_path: STDOUT
    type: file
```

**Additional context**:
I had a look into the Vault logs and noticed that the request path has changed after upgrading to v1.15.1: Before the audit device was successfully created when sending a request to `sys/audit/file`. Now requests are sent to `sys/audit`, which appears to be the problem. Therefore it might have been introduced with https://github.com/banzaicloud/bank-vaults/pull/1538. When downgrading to v1.15.0 the problem does not exist.

**Environment details**:
- Kubernetes version: v1.21.9
- Cloud-provider/provisioner : EKS
- bank-vaults version: v1.15.1
- Install method: static method

/kind bug

**Comment by AndreasSko** [comment]
I just found https://github.com/banzaicloud/bank-vaults/issues/1567 which seems to be related as well. When I explicitly add a path, the configurer is able to add the audit device:

```yaml
audit:
  - path: stdout
    description: send audit logs to STDOUT
    options:
      file_path: STDOUT
    type: file
```
So it seems to me that the default that [used to be applied](https://github.com/banzaicloud/bank-vaults/pull/1538/files#diff-b9f34dc652823bb4fa8af5c2348a3b30bdf96a212aeaa1bb39bb94485bbe4384L33) is not set anymore.
