### ISSUE TITLE
`creation_statements` not executed for postgresql `static-roles`

### ISSUE THREAD

**Issue by ameyp** [banzaicloud/bank-vaults#1641]
**Describe the bug**:
I'm trying to create a `static-role` in my `postgresql` database as follows:

```
      - type: database
        path: database
        configuration:
          config:
            - name: "postgresql"
              plugin_name: postgresql-database-plugin
              allowed_roles: "*"
              connection_url: "postgresql://{{username}}:{{password}}@postgresql.postgresql:5432/postgres"
              username: "postgres"
              password: "postgrespassword"
              rotate: true
          static-roles:
            - name: "amey"
              username: "amey"
              db_name: postgresql
              creation_statements:
                - "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}';"
                - "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"{{name}}\";"
              rotation_statements: "ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"
              rotation_period: 86400
              default_ttl: "10m"
              max_ttl: "24h"
```

However, vault-configurer fails with:

```
{"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding secrets engines: error configuring database/static-roles/amey config in vault: Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/database/static-roles/amey\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* error setting credentials: 1 error occurred:\n\t* failed to execute query: pq: role \"amey\" does not exist\n\n\n\n","time":"2022-06-25T06:19:58Z"}
```

In my `postgresql` container logs, I see repeated prints like:

```
2022-06-25 06:20:26.488 GMT [1388] STATEMENT:  ALTER USER "amey" WITH PASSWORD 'Xua-TqrXzMaVTz037cyU'
2022-06-25 06:20:26.778 GMT [1388] ERROR:  role "amey" does not exist
2022-06-25 06:20:26.778 GMT [1388] STATEMENT:  ALTER USER "amey" WITH PASSWORD 'XLhjjbKippLcV-2AOgUp'
2022-06-25 06:20:28.129 GMT [1388] ERROR:  role "amey" does not exist
2022-06-25 06:20:28.129 GMT [1388] STATEMENT:  ALTER USER "amey" WITH PASSWORD '6h2dSEn6DJwFn7Mymzn-'
2022-06-25 06:20:30.191 GMT [1388] ERROR:  role "amey" does not exist
2022-06-25 06:20:30.191 GMT [1388] STATEMENT:  ALTER USER "amey" WITH PASSWORD 'TWdKHbl-kOTq4ejGGKD3'
```

To me, it looks like the `rotation_statements` are being executed without the `creation_statements` being executed. There are no errors in either PostgreSQL logs or vault-configurer logs related to my creation statements.

**Expected behaviour**:
The new static-role is created successfully.

**Steps to reproduce the bug**:
Deploy a PostgreSQL container (I used bitnami's helm chart), alter the `database` block above accordingly and run `kubectl apply ...`

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.24.1+k3s1
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): N/A, local k3s cluster
- bank-vaults version (e.g. 0.4.17): vault-operator-1.15.8
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
```
{"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding secrets engines: error configuring database/static-roles/amey config in vault: Error making API request.\n\nURL: PUT https://vault.vault:8200/v1/database/static-roles/amey\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* error setting credentials: 1 error occurred:\n\t* failed to execute query: pq: role \"amey\" does not exist\n\n\n\n","time":"2022-06-25T06:19:58Z"}
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```
      - type: database
        path: database
        configuration:
          config:
            - name: "postgresql"
              plugin_name: postgresql-database-plugin
              allowed_roles: "*"
              connection_url: "postgresql://{{username}}:{{password}}@postgresql.postgresql:5432/postgres"
              username: "postgres"
              password: "postgrespassword"
              rotate: true
          static-roles:
            - name: "amey"
              username: "amey"
              db_name: postgresql
              creation_statements:
                - "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}';"
                - "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"{{name}}\";"
              rotation_statements: "ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"
              rotation_period: 86400
              default_ttl: "10m"
              max_ttl: "24h"
```

/kind bug

**Comment by ameyp** [comment]
My mistake - `role` is not the same as `username`. The DB engine manages roles, not users, so I need to specify an already existing user as the `username`. For example:

```
          static-roles:
            - name: "amey"
              username: "postgres"
              db_name: postgresql
              creation_statements:
                - "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}';"
                - "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"{{name}}\";"
              rotation_statements: "ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"
              rotation_period: 86400
              default_ttl: "10m"
              max_ttl: "24h"
```
