### ISSUE TITLE
Idempotency issues when auth engine is already configured

### ISSUE THREAD

**Issue by prog76** [banzaicloud/bank-vaults#1648]
I'm using the **vaultoperator** helm chart **1.15.2** and have the following description for my vault deployment:
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
...
spec:
...  
  image: vault:1.9.3
  externalConfig:
...
    auth:
...
      - type: kubernetes
        path: /kubernetes1
        config:
          kubernetes_host: https://10.1.1.1:443
```
in **vaultconfigurer's** logs I see:
```
{"level":"error","msg":"error configuring vault: error configuring auth methods for vault: error configuring managed auth methods: error enabling /kubernetes1 auth method in vault: Error making API request.\n\nURL: POST http://vault.vault-system:8200/v1/sys/auth/kubernetes1\nCode: 400. Errors:\n\n* path is already in use at kubernetes1/","time":"2022-07-05T11:36:21Z"}
{"level":"info","msg":"Failed applying configuration file: /config/vault-configurer/vault-config.yml , sleeping for 1m0s before trying again","time":"2022-07-05T11:36:21Z"}
```

So it tries to add a new authorization path despite it already exists. It should reconfigure the existing one instead.

Similar one https://github.com/banzaicloud/bank-vaults/issues/167

/kind bug
