### ISSUE TITLE
[vault secrets webhook] default pull secrets serviceaccount not found

### ISSUE THREAD

**Issue by erikbergsten** [banzaicloud/bank-vaults#1659]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Additional context**:

Vault and the webhook are deployed in the vault namespace. A deployment called `secret` using a secret in an environment variable is deployed in the namespace `secret` using a service account called `secret`.

The image is stored in a private registry and is also pre-loaded on the node (rancher rke2 image pre-loading) so the pod in question has no image pull secret.

The DEFAULT_IMAGE_PULL_SECRET and DEFAULT_IMAGE_PULL_SECRET_NAMESPACE environment variables are used to give the vault webhook access to the registry ( with a pull secret called `acr-pull-secret` in the vault namespace). 

**Describe the bug**:

When  `secret-deployment` is deployed the environment variable is not replaced and the webhook pod shows the following error:

    time="2022-07-20T07:51:32Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="failed to create k8schain authentication, opts: {Namespace:vault ServiceAccountName:secret ImagePullSecrets:[acr-pull-secret]}: serviceaccounts \"secret\" not found" kind=v1/Pod name= ns=secret op=create path=/pods request-id=419e0f1a-0b3a-4bd7-8e9d-471ed6df491b webhook-id=vault-secrets-pods webhook-kind=mutating wh-version=v1beta1

If we create a serviceaccount named `secret` in the vault namespace and restart the deployment the validation passes and the secret in the environment variable is replaced correctly.

**Expected behaviour**:

That we can use the default image pull secret so we only need one secret for the entire cluster.

**Steps to reproduce the bug**:

Install vault and the webhook (with a default pull secret) in a k8s cluster ( we discovered it using rke2 with image preloading and mirroring but the easiest way to reproduce is using k3d and manually importing the private image ) and create a deployment using a private image, non-default SA and a secret in an environment variable.

**Environment details**:

- Kubernetes version (e.g. v1.10.2): v1.22.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): k3s
- bank-vaults version (e.g. 0.4.17): ([webhook chart version](https://artifacthub.io/packages/helm/banzaicloud-stable/vault-secrets-webhook): 1.15.11
- Install method (e.g. helm or static manifests): helm chart
- Logs from the misbehaving component (and any other relevant logs): see above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```

apiVersion: v1
kind: ServiceAccount
metadata:
   name: secret
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: secret
  labels:
    app: secret
spec:
  replicas: 1
  selector:
  matchLabels:
    app: secret
  template:
    metadata:
      labels:
        app: secret
      annotations:
        vault.security.banzaicloud.io/vault-role: default
    spec:
      serviceAccountName: secret
      containers:
        - name: secret
          image: our-private-registry.azurecr.io/secret-image:0.1
          env:
            - name: SECRET
              value: "vault:secret/data/test#data"
```

/kind bug
