### ISSUE TITLE
ServiceAnnotations or similar field for Vault CRD since LoadBalancerIP is deprecated

### ISSUE THREAD

**Issue by jpuskar** [banzaicloud/bank-vaults#1661]
Right now the Vault operator can use a specific IP address from metallb via the spec.LoadBalancerIP field. 
This is required for those of us running on-prem clusters who have many different. metallb address pools, etc.

However, this field is deprecated in k8s 1.24.

https://github.com/kubernetes/kubernetes/pull/107235

Perhaps something like spec.ServiceAnnotations should be available instead so that the following pattern could be used to achieve the same purpose:
```yaml
Kind: Service
Metadata:
    Annotations:
        metallb.universe.tf/address-pool: my-vault-address-pool-name
```

Apologies ahead of time if I'm just confused about how this works or if missed an already-existing feature. I read through the source but Go is (not yet) my strong suit.
