### ISSUE TITLE
startupSecrets not working for KV Secrets Engine - Version 1

### ISSUE THREAD

**Issue by forselli-stratio** [banzaicloud/bank-vaults#1666]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
From version 1.15.1 and due to this commit: https://github.com/banzaicloud/bank-vaults/pull/1535 , startupSecrets option is not working 
properly for kv1

Using kv2, secrets are created properly. If i have, for example:
```
    secrets:
    - description: CA secrets.
      options:
        version: 2
      path: test-v2
      type: kv
    startupSecrets:
    - data:
        data:
          test: lala
      path: test-v2/data/test
      type: kv
```
I can check vault and see the following:
```
$vault kv list test-v2
Keys
----
test
$keos vault kv get test-v2/test
====== Metadata ======
Key              Value
---              -----
created_time     2022-08-02T14:02:58.599438876Z
deletion_time    n/a
destroyed        false
version          3

==== Data ====
Key     Value
---     -----
test    lala
```
But if i use kv1, for example:
```
    secrets:
    - description: CA secrets
      options:
        version: 1
      path: test-v1
      type: kv
    startupSecrets:
    - data:
        data:
          test: lele
      path: test-v1/data/test
      type: kv
```
The following secret is created in vault:
```
$vault list test-v1
Keys
----
data/
$vault list test-v1/data
Keys
----
test
$vault read test-v1/data/test
Key                 Value
---                 -----
refresh_interval    768h
data                map[test:lele]
```
As you can see the secret is not right, "data" will always be the key int the secret and the value will be a map with the secret that is intended to upload. I think the error is here: https://github.com/banzaicloud/bank-vaults/pull/1535/files#diff-9355c222d1dd765a044f6296fb0b1e401f5a13a7835771cb89a5cfb2f81abc13R40

**Expected behaviour**:
Secrets to be created properly.

**Steps to reproduce the bug**:
1- Create a kv1 secret engine
2- Create a secret using startupSecrets

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- bank-vaults version (e.g. 0.4.17):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by patoarvizu** [comment]
I'm running into this too. Are there any plans to fix it, or any workarounds? This used to work before 1.15 I believe.

**Comment by akijakya** [comment]
Hi @forselli-stratio, @patoarvizu! Could you tell more about your use case for adding `startupSecrets` to a v1 kv engine? For testing purposes? Would you also create a v2 kv engine as well and would like to put some secrets from the start here, others there, or want all `startupSecrets` to be present in both of them? Thanks!

**Comment by patoarvizu** [comment]
In my specific case, I want to seed a static non-secret "secret" that I need for synthetic testing purposes (I'm using [Kuberhealthy](https://github.com/kuberhealthy/kuberhealthy) to simulate a client authenticating to Vault and reading secrets every certain amount of time).

My organization only uses KV v1, so I would like it if the operator is smart enough to know whether the items under `startupSecrets` have a target that's v1 vs v2 and inject accordingly. In my case, I have:
```
    startupSecrets:
    - type: kv
      path: secret/test-vault
      data:
        data:
          kuberhealthy: test-vault
```
And the `secret/` mount is KV v1, which results in a map being injected into `secret/test-vault` with a single key `data`, e.g.:
```
vault read secret/test-vault

{
  "data": {
      "kuberhealthy": "test-vault"
  }
}
```
Instead of just
```
{
  "kuberhealthy": "test-vault"
}
```
This makes sense because under `startupSecrets` I have:
```
  data:
    data:
      kuberhealthy: test-vault
```
Because that's the schema of the `Vault` CRD, but then that's exactly what gets injected by the configurer.

I would expect to be able to just do:
```
  data:
    kuberhealthy: test-vault
````
And have the operator/configurer figure out if the mount is v1 or v2, and set the payload appropriately, instead of assuming it's v2, which expects the `data` field. Does that make sense? FWIW this worked as described for v1 up until at least 1.9 I think, but it was refactored at some point.

Note that in my specific use case, the synthetic testing still works because there is an item injected at `asapp/test-vault` and the client can read it, which is good enough for me, but I as an operator know that the value that's being injected at that path at bootstrap time is not what's expected.

I hope that clarifies!
