### ISSUE TITLE
failed to create vault client: Error loading CA Path: Couldn't parse PEM in: /vault/tls/..XXX.XXX/ca.ke

### ISSUE THREAD

**Issue by paivin-dn** [banzaicloud/bank-vaults#1677]
**Describe the bug**:
I try to create a secret resource with data from vault. I get the following errors:
```bash
level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="failed to create vault client: Error loading CA Path: Couldn't parse PEM in: /vault/tls/..2022_08_23_12_33_01.387314721/ca.key" kind=v1/Secret name=test-secret-123 ns=default op=create path=/secrets request-id=6f830da8-8854-4442-8b4f-c8a38555b00c webhook-id=vault-secrets-secret webhook-kind=mutating wh-version=v1beta1
```
## Secret manifest
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret-123
  annotations:
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-role: "cloud_services"
    vault.security.banzaicloud.io/vault-serviceaccount: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
type: Opaque
data:
  # vault:secret/data/default/test#test
  auth: dmF1bHQ6c2VjcmV0L2RhdGEvZGVmYXVsdC90ZXN0I3Rlc3QK
```

## Bank vaults externalConfig
```yaml
  externalConfig:
    purgeUnmanagedConfig:
      enabled: true
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: snapshot
        rules: path "sys/storage/raft/snapshot" {
          capabilities = ["read"]
          }
      - name: cloud_services_secrets
        rules: path "secret/data/{{identity.entity.aliases.auth_kubernetes_XXX.metadata.service_account_namespace}}/*" {
          capabilities = ["read", "list"]
          }
    auth:
      - type: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc
        roles:
          - name: default
            bound_service_account_names: ["vault", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["vault", "vault-secrets-webhook"]
            policies: allow_secrets
            ttl: 1h
          - name: cloud_services
            bound_service_account_names: ["default"]
            bound_service_account_namespaces: ["*"]
            policies: cloud_services_secrets
            ttl: 1h
      - type: approle
        roles:
          - name: snapshot-agent
            token_ttl: 2h
            token_policies: "snapshot"

```

The bank-vaults has been installed into the vault namespace.

**Expected behaviour**:
I expect that a new secret will be created.

**Environment details**:
- Kubernetes version: v1.21.11
- Cloud-provider/provisioner: DigitalOcean Managed Kubernetes
- bank-vaults version (e.g. 0.4.17): 1.15.3
- Install method (e.g. helm or static manifests): helm

/kind bug
