### ISSUE TITLE
Please provide urlencode (URL encode) functions

### ISSUE THREAD

**Issue by johnlinp** [banzaicloud/bank-vaults#1728]
**Is your feature request related to a problem? Please describe.**
I want to make a JDBC URL from Vault secrets with the [Banzai Cloud template engine](https://banzaicloud.com/docs/bank-vaults/operator/templating-configuration/).

**Describe the solution you'd like**
I'm trying to do something like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-db-configmap
  annotations:
    # vault.security.banzaicloud.io settings
data:
  jdbc: postgresql://foo.bar.svc:5432/mydb?user=${vault:secret/database/test#username}&password=${vault:secret/database/test#password}
```

However, my password contains some special characters, so the whole JDBC URL is not a safe URL.

I searched the available functions, but didn't see one that can do urlencode.

**Describe alternatives you've considered**
I may have to do some extra post-processing for the unsafe JDBC URL.
