### ISSUE TITLE
Mutating Webhook doesn't work when there are only template-style secrets

### ISSUE THREAD

**Issue by johnlinp** [banzaicloud/bank-vaults#1737]
**Describe the bug**:
Mutating Webhook will work when a ConfigMap contains both plain secrets (e.g. `vault:secret/database/test#username`) and template-style secrets (e.g. `user=${vault:secret/database/test#username}`). However, it doesn't work when there's only template-style secrets.

**Expected behaviour**:
Mutating Webhook should work no matter what secret style it contains.

**Steps to reproduce the bug**:
Consider the following 2 ConfigMaps:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  annotations:
    # vault.security.banzaicloud.io settings
data:
  plain: vault:secret/database/test#username
  template: user=${vault:secret/database/test#username}
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2
  annotations:
    # vault.security.banzaicloud.io settings
data:
  template: user=${vault:secret/database/test#username}
```

After creating these 2 ConfigMaps, `test-configmap-1` will get mutated by Mutating Webhook, i.e. both `plain` and `template` will get mutated. However, `test-configmap-2` will stay the same, without being mutated. It will look like this:

```
$ kubectl get configmap test-configmap-1 -o jsonpath='{.data}'
{"template":"user=postgres","plain":"postgres"}
$ kubectl get configmap test-configmap-2 -o jsonpath='{.data}'
{"template":"user=${vault:secret/database/test#username}"}
```

**Environment details**:
- Kubernetes version: v1.22.3
- banzaicloud/vault-secrets-webhook version: 1.13.0

/kind bug
