### ISSUE TITLE
[vault-configurer] Fetching wrong key after GCP KMS unseal key version is rotated and disabled

### ISSUE THREAD

**Issue by Gentoli** [banzaicloud/bank-vaults#1750]
**Describe the bug**:
Fetching wrong key (`cryptoKeyVersions/1`) after the GCP KMS key is rotated and disabled. The current key revision is 3.

**Expected behaviour**:
Not sure how Vault handles GCP KMS key rotation, Vault seems to be able to unseal with the old revision disabled. `vault-configurer` should match Vault's behavior. 

**Steps to reproduce the bug**:
I have not caught this when the key has rotated as I had no vault upgrade or configuration change (https://github.com/banzaicloud/bank-vaults/issues/1749).

I presume:
- create vault with GCP KMS
- rotate the key and ensures Vault has picked up new key revision
- disable the old key revision

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2):  `v1.24.6-gke.1500`
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GKE
- bank-vaults version (e.g. 0.4.17): `1.16.0`
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): 
```
error configuring vault: unable to get key 'vault-root': error decrypting data: googleapi: Error 400: projects/<project>/locations/global/keyRings/vault/cryptoKeys/vault-unsealer/cryptoKeyVersions/1 is not enabled, current state is: DISABLED.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
    "violations": [
      {
        "subject": "projects/<project>/locations/global/keyRings/vault/cryptoKeys/vault-unsealer/cryptoKeyVersions/1",
        "type": "KEY_DISABLED"
      }
    ]
  }
]
, failedPrecondition
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

``` yaml
spec:
  ...
  config:
    api_addr: 'https://vault:8200'
    cluster_addr: 'https://${.Env.POD_NAME}:8201'
    listener:
      ...
    seal:
      gcpckms:
        crypto_key: vault-unsealer
        key_ring: vault
        project: <project>
        region: global
    storage:
      gcs:
        bucket: <bucket>
        ha_enabled: 'true'
    telemetry:
      statsd_address: 'localhost:9125'
    ui: true
  credentialsConfig:
    env: ''
    path: ''
    secretName: ''
  ...
  unsealConfig:
    google:
      kmsCryptoKey: vault-unsealer
      kmsKeyRing: vault
      kmsLocation: global
      kmsProject: <project>
      storageBucket: <bucket>
    kubernetes: {}
    options: {}
  ...
```

/kind bug
