### ISSUE TITLE
Vault Agent fails to start if you change the vault user name

### ISSUE THREAD

**Issue by malachiobadeyi** [banzaicloud/bank-vaults#1782]
**Describe the bug**:
If you try to change the vault user using "vault.security.banzaicloud.io/run-as-user" then the vault-agent will fail to start up with the following error message `unable to set CAP_SETFCAP effective capability: Operation not permitted`.   This happens because the vault [entrypoint.s](https://github.com/hashicorp/vault/blob/v1.12.2/.release/docker/ubi-docker-entrypoint.sh#L90) script attemps to run `setcap cap_ipc_lock=+ep $(readlink -f /bin/vault)` but fails if it's not the vault user.   This step can be bypassed by setting the env variable SKIP_SETCAP=1, however, I can not see any way to set env variables using the mutating webhook.   

Can we add a way to set ENV variables by annotating the pod spec.  e.g `vault.security.banzaicloud.io/vault-agent-env-variables: "[{\"Name\": \"SKIP_SETCAP\",\"Value\": \"1\"}]"`

**Comment by akijakya** [comment]
Hi @malachiobadeyi, thanks for the suggestion! May I ask for an example resource definition or a method with which I could reproduce the error? Thanks!

**Comment by malachiobadeyi** [comment]
> Hi @malachiobadeyi, thanks for the suggestion! May I ask for an example resource definition or a method with which I could reproduce the error? Thanks!

Hi @akijakya, below is an example deployment object.
```  { 
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "annotations": {
      "meta.helm.sh/release-name": "hello-bosun",
      "meta.helm.sh/release-namespace": "trial-obadeyim"
    },
    "name": "hello-bosun",
    "namespace": "trial-obadeyim",
  },
  "spec": {
    "template": {
      "metadata": {
        "annotations": {
          "vault.security.banzaicloud.io/run-as-user": "1021",
          "vault.security.banzaicloud.io/vault-addr": "https://vault.lab.jspaas.uk",
          "vault.security.banzaicloud.io/vault-agent-configmap": "hello-bosun-vault-agent",
          "vault.security.banzaicloud.io/vault-agent-service-account-token-volume-name": "/var/run/secrets/vault",
          "vault.security.banzaicloud.io/vault-image": "vault:1.12.2",
          "vault.security.banzaicloud.io/vault-path": "jwt-kubernetes-lab-ie-01",
          "vault.security.banzaicloud.io/vault-role": "op-trial-obadeyim"
        },
        "labels": {
          "app.kubernetes.io/instance": "hello-bosun",
          "app.kubernetes.io/name": "hello-bosun"
        }
      },
      "spec": {
        "containers": [{
            "env": [{
              "name": "VAULT_JWT_FILE",
              "value": "/var/run/secrets/vault/token"
            }],
            "image": "hello-bosun:77af7a64",
          },
          "name": "hello-bosun",
          "ports": [{
            "containerPort": 8080,
            "name": "http",
            "protocol": "TCP"
          }],
          "readinessProbe": {
            "failureThreshold": 3,
            "httpGet": {
              "path": "/",
              "port": 8080,
              "scheme": "HTTP"
            },
            "periodSeconds": 10,
            "successThreshold": 1,
            "timeoutSeconds": 1
          },
          "resources": {
            "limits": {
              "cpu": "500m",
              "memory": "128Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "securityContext": {
            "runAsUser": 1021
          },
          "volumeMounts": [{
            "mountPath": "/var/run/secrets/vault",
            "name": "vault-token"
          }]
        }
      ],
      "dnsPolicy": "ClusterFirst",
      "nodeSelector": {
        "jspaas.uk/nodepool": "private"
      },
      "serviceAccount": "hello-bosun",
      "serviceAccountName": "hello-bosun",
      "volumes": [{
        "name": "vault-token",
        "projected": {
          "defaultMode": 420,
          "sources": [{
            "serviceAccountToken": {
              "audience": "vault",
              "expirationSeconds": 7200,
              "path": "token"
            }
          }]
        }
      }]
    }
  }
}```

**Comment by joshuasimon-taulia** [comment]
i'm seeing the same issue when trying to run the vault-agent as user `1002`
configmap:
```
# Source: my-app/templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "my-app"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }

    template {
      left_delimiter = "(("
      right_delimiter = "))"
      perms = 0400
      user = "my-app"
      group = "my-app" 

      contents = <<-EOH
      ((- with printf "my-app/transit/export/encryption-key/cmk" | secret -))
      (( index .Data.keys "1" ))
      ((- end ))
      EOH

      destination = "/vault/secrets/my-app-cmk"
    }
```
deployment:
```
# Source: my-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app
  annotations:
    meta.helm.sh/release-name: 'my-app'
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/instance: my-app
  template:
    metadata:
      annotations:
        checksum/config: 'efc8a8bcabad64d40e3daea8e84d14f9b2e8c2751ce6e263949a83773d28ca0d'
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        vault.security.banzaicloud.io/run-as-user: "1002"
        # i've tried combining this with run-as-non-root with no succes
        # vault.security.banzaicloud.io/run-as-non-root: "true"
        vault.security.banzaicloud.io/vault-addr: https://vault:8200
        vault.security.banzaicloud.io/vault-agent-configmap: 'my-app-config'
        vault.security.banzaicloud.io/vault-env-daemon: "true"
        vault.security.banzaicloud.io/vault-role: my-app
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
      labels:
        app.kubernetes.io/name: my-app
        app.kubernetes.io/instance: my-app
    spec:
      hostname: my-app
      serviceAccountName: my-app
      securityContext: {}
      containers:
      - name: my-app
        command:
        - sh
        - -c
        - |
          /tini -s -- /entrypoint.sh /home/my-app/my-app/my-app-service start
        securityContext: {}
        image: "foo"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /availability
            port: http
            scheme: HTTPS
          initialDelaySeconds: 240
        readinessProbe:
          httpGet:
            path: /availability
            port: http
            scheme: HTTPS
          initialDelaySeconds: 90
        resources:
          limits:
            cpu: 2000m
            memory: 10Gi
          requests:
            cpu: 1000m
            memory: 8Gi
      volumes:
      - name: config-map
        configMap:
          name: my-app-config
          defaultMode: 0755
```
