### ISSUE TITLE
Configuring PKI secrets engine from external config

### ISSUE THREAD

**Issue by RBlaine95** [banzaicloud/bank-vaults#180]
Is there a way that I can configure and initialize the PKI secrets engine via the _externalConfig_ in the Vault CR?

Something like this:  
```yaml
    externalConfig:
      secrets:
      - type: pki
        description: Vault PKI Backend
        options:
          default_ttl: 168h
          max_ttl: 720h
          config:
          - urls:
            issuing_certificates: https://vault.${NAMESPACE}:8200/v1/pki/ca
            crl_distribution_points: https://vault.${NAMESPACE}:8200/v1/pki/crl
          certificates:
          - name: root
            generate:
              internal:
                common_name: vault.${NAMESPACE}
          roles:
          - name: default
            allowed_domains: localhost,pod,svc,${NAMESPACE}
            allow_subdomains: true
            generate_lease: true
            ttl: 30m
```

**Comment by bonifaido** [comment]
Hi @RBlaine95, PKI is not yet supported, but this looks like a correct formatting, have you tried to run this? If yes, what was the output?

**Comment by RBlaine95** [comment]
Hi @bonifaido, thank you for the reply.  

I have run this and the output is that the PKI Secret backend is created and mounted but nothing is configured or initialized.

The log output of `vault-configurer-6b5d8b5b98-xxxxx` is as follows:
```
time="2018-10-11T10:36:34Z" level=info msg="New config file change \"Initial\": CREATE"
time="2018-10-11T10:36:34Z" level=info msg="checking if vault is sealed..."
time="2018-10-11T10:37:05Z" level=info msg="checking if vault is active..."
time="2018-10-11T10:37:05Z" level=info msg="vault is unsealed and active, configuring..."
time="2018-10-11T10:37:05Z" level=info msg="Already existing mounts: map[string]*api.MountOutput{\"cubbyhole/\":(*api.MountOutput)(0xc0005380c0), \"identity/\":(*api.MountOutput)(0xc000538180), \"secret/\":(*api.MountOutput)(0xc000538240), \"sys/\":(*api.MountOutput)(0xc000538300)}\n"
time="2018-10-11T10:37:05Z" level=info msg="Mounting secret engine with input: api.MountInput{Type:\"pki\", Description:\"Vault PKI Backend\", Config:api.MountConfigInput{Options:map[string]string(nil), DefaultLeaseTTL:\"\", Description:(*string)(nil), MaxLeaseTTL:\"\", ForceNoCache:false, PluginName:\"\", AuditNonHMACRequestKeys:[]string(nil), AuditNonHMACResponseKeys:[]string(nil), ListingVisibility:\"\", PassthroughRequestHeaders:[]string(nil)}, Options:map[string]string{\"roles\":\"\", \"certificates\":\"\", \"config\":\"\", \"default_ttl\":\"168h\", \"max_ttl\":\"720h\"}, Local:false, PluginName:\"\", SealWrap:false}\n"
time="2018-10-11T10:37:05Z" level=info msg="mounted pki to pki"
time="2018-10-11T10:37:05Z" level=info msg="successfully configured vault"
```

**Comment by RBlaine95** [comment]
Is there a branch or work being done for configuring the PKI backend?

**Comment by bonifaido** [comment]
Not yet, I'm checking the configuration submitted by you, it is not correctly formatted, I'm trying to format it to see if we can configure it without code changes.

**Comment by bonifaido** [comment]
I have managed to fix the configuration, could you please try:

```yaml
secrets:
  - type: pki
    description: Vault PKI Backend
    options:
      default_ttl: 168h
      max_ttl: 720h
    configuration:
      config:
      - name: urls
        issuing_certificates: https://vault.default:8200/v1/pki/ca
        crl_distribution_points: https://vault.default:8200/v1/pki/crl
      root/generate:
      - name: internal
        common_name: vault.default
      roles:
      - name: default
        allowed_domains: localhost,pod,svc,default
        allow_subdomains: true
        generate_lease: true
        ttl: 30m
```
