### ISSUE TITLE
Secret with type dockerconfigjson fails to mutate injected secrets

### ISSUE THREAD

**Issue by KnudFrandsen** [banzaicloud/bank-vaults#1811]
**Describe the bug**:

I am in the process of mutating secrets to a deployed Vault operator, so far i have succeeded in mutating most of the secrets, until i met this case.

I am trying to mutate the secrets stored in the following context:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: openshift-config
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
        {
            "auths": {
                "dck-docker-remote.registry.domain.path": {
                    "username": "XXusernameXX",
                    "password": "XXpasswordXX",
                    "auth": "XXauthXX"
                },
                "dck-quay-remote.registry.domain.path": {
                    "username": "XXusernameXX",
                    "password": "XXpasswordXX",
                    "auth": "XXauthXX"
                }
            }
        }
```

I tried to mutate the secrets by following the docs by (banzaicloud)[https://banzaicloud.com/docs/bank-vaults/mutating-webhook/configuration/#mutate-data-from-vault-and-replace-it-in-kubernetes-secret]:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: openshift-config
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.domain.net"
    vault.security.banzaicloud.io/vault-tls-secret: "CAname"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-role: "default"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5pbyI6eyJ1c2VybmFtZSI6InZhdWx0OnBhdGgjdXNlcm5hbWUiLCJwYXNzd29yZCI6InZhdWx0OnBhdGgjcGFzc3dvcmQiLCJhdXRoIjoidmF1bHQ6cGF0aCNhdXRoIn19fQ==
```
However the `vault-secrets-webhook` fails to mutate the secrets and gives the following error in the logs:

```logs
time="2023-02-28T11:52:07Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="failed to check if secret needs to be mutated: auth base64 decoding failed: illegal base64 data at input byte 5" kind=v1/Secret name=sample-secret ns=default op=create path=/secrets request-id=cbc3aa32-d3d4-48c6-bd3e-ea92c139a870 webhook-id=vault-secrets-secret webhook-kind=mutating wh-version=v1beta1
```

**Expected behaviour**:

The expected result is that the secrets in the described context is successfully mutated.

**Steps to reproduce the bug**:
The bug could be reproduced by applying the `secret` i described previously. 

**Additional context**:

**Environment details**:
- Kubernetes version (v1.23.3):
- Cloud-provider/provisioner (on premise OKD):
- bank-vaults version (v1.15.3):
- Install method (vault operator):

"You should first attempt to resolve your issues through the community support channels, e.g. Slack, in order to rule out individual configuration errors."
I tried to sign up for your slack community, but i do not have a email with the required domain..

/kind bug
