### ISSUE TITLE
Parse SecurityContext to Vault Statefulset

### ISSUE THREAD

**Issue by RBlaine95** [banzaicloud/bank-vaults#187]
**Is your feature request related to a problem? Please describe.**
Currently the `default` Service Account in the target namespace must have the `anyuid` SCC, as well as have the `IPC_LOCK` capability, otherwise the vault container continuously crashes due to permission denied when it tries to `chown` the `/vault` directory so that the `/vault` directory user uid matches the running user uid.

Allowing pods to run as root opens the door to an exploit that allows processes to escape the container engine.

**Describe the solution you'd like**
It would be useful to have the ability to add `securityContext: {}` to the Vault Statefulset, specifically the `runAsUser` flag.
```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:0.11.0
  bankVaultsImage: banzaicloud/bank-vaults:latest
  
  securityContext:
    runAsUser: 100
```
This will allow you to give a `default` Service Account the `nonroot` SecurityContextConstraint, slightly modified to allow for the `IPC_LOCK` Capability.
This prevents pods from being run with the root user, which helps to prevent a privilege escalation exploit.

**Additional context**
> By default, OKD runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.

[OKD Docs](https://docs.okd.io/latest/creating_images/guidelines.html#openshift-specific-guidelines)
