### ISSUE TITLE
`vault-config.yml` contents is converted to JSON and doesn't affect application 

### ISSUE THREAD

**Issue by kirillplis** [banzaicloud/bank-vaults#2017]
**Describe the bug**:
In `vault-config` Secret, `vault-config.yml` contents is converted into a JSON format before being encrypted, and being ignored by the application.
```
vault-config.yml:
  {{ .Values.vault.externalConfig | toPrettyJson | b64enc }}
```

**Expected behaviour**:
`vault-config.yml` is kept in YAML format before encription.
```
vault-config.yml:
  {{ .Values.vault.externalConfig | toYaml | b64enc }}
```

**Steps to reproduce the bug**:
1. Try to change policy name or add another auth method to the `externalConfig` block:
```
    #   value: /etc/gcp/service-account.json
  externalConfig:
    # Allows creating policies in Vault which can be used later on in roles
    # for the Kubernetes based authentication.
    # See https://www.vaultproject.io/docs/concepts/policies.html for more information.
    policies:
      - name: test_allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        # Allows creating roles in Vault which can be used later on for the Kubernetes based
        # authentication.
        # See https://www.vaultproject.io/docs/auth/kubernetes.html#creating-a-role for
        # more information.
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
    secrets:
      - path: test-secret
        type: kv
        description: General secrets.
        options:
          version: 2
```
This step should produce no changes to the policies/secrets/auth configuration.

2. Put same contents directly into the `vault-config.yml` file and observe the changes
```
kubectl exec -it vault-0 -n vault -c vault -- sh
echo YAML_CONFIG > vault/config/vault-config.yml
cat vault/config/vault-config.yml
```
This step should produce desired changes to the policies/secrets/auth configuration.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.26.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.19.0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): Doesn't appear in logs
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: 
```
# Source: vault/charts/vault/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "vault-config"
  namespace: vault
  labels:
    helm.sh/chart: vault-1.17.0
    app.kubernetes.io/name: "vault"
    app.kubernetes.io/instance: "vault"
    app.kubernetes.io/managed-by: "Helm"
data:
  config.json:
    ENCODED_DATA
  vault-config.yml:
    ENCODED_DATA

/kind bug
