### ISSUE TITLE
Inconsistent roleRef name in chart and operator

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#221]
Inconsistent roleRef:name in chart and operator

https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/rbac.yaml#L70

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-operator-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-operator
  namespace: default
```
https://github.com/banzaicloud/banzai-charts/blob/master/vault-operator/templates/rolebinding.yaml#L13
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-operator.fullname" . }}
  labels:
    chart: {{ include "vault-operator.chart" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "vault-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io```
