### ISSUE TITLE
secrets in initContainer

### ISSUE THREAD

**Issue by shidoh** [banzaicloud/bank-vaults#247]
Hi!
It’s impossible to use a webhook with deployments where secrets are needed in initContainers. vault-env is not added to them

example:
```
initContainers:
  - name: test-init
    image: ...
    command: ...
    env:
      - name: SECRET_VAR
        value: "vault:secret/data/test-secret#SECRET_VAR"
```

**Comment by bonifaido** [comment]
Hi, yes, currently init containers are not handled, I will keep this issue open to come up with a solution for this.

**Comment by matyix** [comment]
@shidoh we added support for init container as well, it's in master and [released](https://github.com/banzaicloud/bank-vaults/releases/tag/0.3.25). Thanks for reporting this, let us know how it works for you.

**Comment by shidoh** [comment]
I think this is a runtime error of vault-env in initContainer:
standard_init_linux.go:190: exec user process caused "no such file or directory"
there are no more logs from the container

**Comment by bonifaido** [comment]
Could you please post an example how your Deployment looks like so I can try reproduce this?

**Comment by shidoh** [comment]
> Could you please post an example how your Deployment looks like so I can try reproduce this?
Sorry, but I can not give links to our images, replaced them with an "example".
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.example.com"
    vault.security.banzaicloud.io/vault-role: "example-dev"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "example-dev-kube"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: example
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - example
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: example-migrations
          image: registry.example.com/exmaple/service:development
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c", "python manage.py migrate --noinput" ]
          env:
            - name: DATABASE_DBNAME
              value: example
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PASSWORD
              value: "vault:secret/data/example/dev/service/postgres-credentials#DATABASE_PASSWORD"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "vault:secret/data/example/dev/service/postgres-credentials#DATABASE_USER"
            - name: DEBUG
              value: "true"
      containers:
        - name: example-service
          ports:
            - name: http
              containerPort: 80
          image: registry.example.com/example/service:development
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c", "/usr/bin/supervisord"]
          env:
            - name: DATABASE_DBNAME
              value: example
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PASSWORD
              value: "vault:secret/data/example/dev/service/postgres-credentials#DATABASE_PASSWORD"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "vault:secret/data/example/dev/service/postgres-credentials#DATABASE_USER"
            - name: DEBUG
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              value: "vault:secret/data/example/dev/service/s3-credentials#AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET_ACCESS_KEY
              value: "vault:secret/data/example/dev/service/s3-credentials#AWS_SECRET_ACCESS_KEY"
```
