### ISSUE TITLE
Mutating environment containing valueFrom discussion

### ISSUE THREAD

**Issue by dennybaa** [banzaicloud/bank-vaults#277]
I would start a short discussion on the subject. Bank-vaults is already an awesome tool already :+1: . However it feels important to address its integration scenarios with arbitrary charts. Here's my concern. Please, take a look at the definition of a env variable from the `stable/mongodb` chart.

```yaml
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{- else }}{{ template "mongodb.fullname" . }}{{- end }}
                key: mongodb-password
```

In the given example a best practice pattern is followed which basically takes an existing secret into account. Obviously, this approach gives charts the flexibility of choosing a secret source.

Kubernetes API defines several *envvarSources* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#envvarsource-v1-core.

This makes me think that mutating variables based on its `secretKeyRef` and `configMapKeyRef` name attributes can be very handy allowing us to use the existing charts without adaptations.

The values file example is provided bellow:

```yaml
existingSecret: "vault:secret/dev/mongodb#MONGODB_PASSWORD"
```

Please tell me what do you think of this?

**Comment by dennybaa** [comment]
Hi @bonifaido. Oh yes `envFrom:` is definitely should be mutated too. Awesome this issue will serve as a good reminder then :)

Summing up:

1. Specific cm/secret (useful to support many of the existing charts)

```
containers:
  - name: mongodb
    env: 
      - name: MONGODB_PASSWORD
        valueFrom:
          secretKeyRef:
             name: vault:secret/dev/mongodb#MONGODB_PASSWORD
             key: mongodb-password-technically-ignored
```

2. All env vars injection, smth like this:
```yaml
containers:
  - name: test-container
    envFrom:
    - configMapRef:
      name: vault:secret/dev/test-secret-env#
    - secretRef:
      name: vault:secret/dev/test-secret-env-2#
```
