### ISSUE TITLE
Discussion: externalConfig isn't scalable

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#323]
**Is your feature request related to a problem? Please describe.**
ExternalConfig is a great feature but ofcourse it is not scalable. We need to come up with a better approach at this. A few hundred apps deployed inside and outside of kubernetes would end up with a few hundred roles and policies add that to corporate level user roles or iam. It kind of gets out of hand pretty soon.

**Describe the solution you'd like**
I researched this but found that it was requested from vault as well but there is no easy way unless you use codify that goes through your directories and applies the configs

For example
```
sys/auth
sys/mounts
sys/policy
postgresql/config
postgresql/roles
auth/approle/role
auth/kubernetes/config
auth/kubernetes/role
```

**Describe alternatives you've considered**
[Codify vault provisioning](https://github.com/hashicorp/vault-provision-example)

**Additional context**
I think it would be a great addition to vault-configurer to be able to read from a volume path and do something similar than reading externalConfig

**Comment by bonifaido** [comment]
I think this is a great idea, something that we should really implement because I think that this is a scalability issue as well.

We need to come up with a solution which keeps compatibility with the previous solution, the inline `externalConfig:` block. This needs to be extended with an `externalConfigFiles:` attribute, which can be a list of directories or files, which needs to be watched as well and parsed for configuration. I like the idea of grouping the directories with the intention of the files inside them, however, the configuration format should remain the same I guess, so making this grouping as optional/conventional/best-practice should be enough in my opinion.

**Comment by raoofm** [comment]
@bonifaido thanks for your feedback. So how do you envision pushing the files/dir to the vault-configurer volume.

**Comment by raoofm** [comment]
@bonifaido  One of my colleagues also suggested - why not just use CRDs?
I'm still thinking about this option, looks like a cleaner solution as we already have a vault CRD and that could be extended as different resources like role/policy/backend/config. Looking at pros and cons not sure yet.

**Comment by thejmazz** [comment]
*Just chiming in*,

One thing I like about the inline config is it makes for simple CD/GitOps using existing tooling; currently I'm using weaveworks/flux.

If volumes are used, then it could be difficult to keep a GitOps approach - somehow dump files from repo into a volume? Git PVC? Straight up manually edited volume?

Another "pseudo-scalable" approach would be to construct the externalConfig block programmatically. Another approach is using Terraform to provision roles, which probably has similar scaling concerns at such large numbers of roles, and you'd probably also generate hcl/json at that point.

CRDs sounds good too; then you could just dump a bunch of those in git and use familiar `kubectl apply -f` and all the existing K8s CD tooling. However then this would deviate from bank-vaults being usable outside of K8s. This also makes sense similar to the logging operator; for a certain "app" just like I would want to have a fluentd config, I would also want a set of vault roles colocated. Actually yeah CRDs would be pretty nice... Perhaps errors from applying that specific vault config could then end up in the events of the CRD

**Comment by bonifaido** [comment]
I'm also not a big fan of the volumes method, and I don't really want to break the "works outside of Kubernetes" feature as well, but this feature would only cause changes in the Operator I think, which would watch the CRD (which I'm also happy with). The only real change in the bank-vaults CLI would be the ability to watch more files at the same time instead of one config file, which wouldn't break anything.

Adding CRDs causes me one pain only, how to connect CRDs holding configuration, maybe by using labels?

**Comment by bonifaido** [comment]
I would like to create a sidecar issue for this as well, namely letting `bank-vaults confgiure` subcommand read configuration files from a directory and/or be able to specify multiple files during startup.

**Comment by bonifaido** [comment]
https://github.com/banzaicloud/bank-vaults/issues/330 was submitted.

**Comment by raoofm** [comment]
> how to connect CRDs holding configuration, maybe by using labels?

I'm not sure I understand this, sorry can you please elaborate. 

I'm typing as I'm thinking of something like

```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
```
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "VaultPolicies"
```
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "VaultAuthKubernetesConfig"
```
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "VaultAuthKubernetesRoles"
```
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "VaultApproleRoles"
```

**Comment by bonifaido** [comment]
You have a Vault CRD, and one of the above (which I think can be one type only, sparing some ceremony of setting all these types up and maintaining them). How to connect these two?

**Comment by raoofm** [comment]
Isn't namespace enough?

Or could they tie back to the name metadata of kind: "Vault"

**Comment by thejmazz** [comment]
Why not keep consistent and use existing annotation structure used for vault-agent? i.e. specify FQDN to Vault API in a `vault.security.banzaicloud.io/vault-addr` annotation. You could then use Vault CRDs on their own pointing to a Vault API running outside of K8s, again for the CD/GitOps benefits (in lieu of some ad-hoc scripted Vault policy provisioning process). Depending on service+namespace/labels, or some shared "vault instance id" between operator and CRDs sounds more difficult and less general purpose.

**Comment by raoofm** [comment]
@mmerrill3

**Comment by matyix** [comment]
Thanks for all the suggestions, etc - your feedback is important. To ease and speed up communications (if we don't conclude on a solution which fits all) I'd suggest having a Slack call/chat next week. You can join here https://slack.banzaicloud.io and find us in the `#bank-vaults` channel.

**Comment by bonifaido** [comment]
Based on the call that we had yesterday I'm trying to some up what we have agreed in:

- `externalConfiguration` can be stored in plain ConfigMaps (this helps mounting them as volumes into the bank-vaults Pod)
- ConfigMaps with an annotation: like `vault.security.banzaicloud.io/vault-name: "my-vault-crd-name"` will be mapped to the the correct Vault instance by CRD name.
- The ConfigMaps have no restriction which part of the configuration can be stored in them, everything that can be written and is semantically correct under `spec.externalConfig` in the CRD should work.
- If a ConfigMap is updated the updates should propagated by bank-vaults in a reasonable time (kubelet cache time + ttl)
- Inline `externalConfig` should remain working

An example ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-vault-external-config
  namespace: default
  labels:
    app: my-vault-external-config
  annotations:
    vault.security.banzaicloud.io/vault-name: "my-vault"
data:
    policies:
    - name: allow_secrets
       rules: path "secret/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
            }
    - name: readonly_secrets
       rules: path "secret/*" {
                capabilities = ["read", "list"]
            }
    auth:
    - type: kubernetes
       roles:
        - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
```

Please let me know if I have missed something.

**Comment by bonifaido** [comment]
@raoofm @thejmazz

The draft version has been pushed as a PR implementing this feature, please see: https://github.com/banzaicloud/bank-vaults/pull/356

One slight change to our original agreement, using annotations seemed a bit out of band here, so I have changed the ConfigMap selection to label selectors, which feels more natural to me.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    # These two annotations has to be present to connect to the "right" Vault instance
    app: vault-configurator
    vault_cr: vault
  name: second-config
data:
  vault-config.yml: |
    audit:
    - type: file
      description: "My second file based audit logging device"
      options:
        file_path: /tmp/vault-second.log
```
