### ISSUE TITLE
Kubernetes auth config does not support inline config

### ISSUE THREAD

**Issue by gregdurham** [banzaicloud/bank-vaults#332]
**Describe the bug**
In the example external vault configuration, it is described that you can configure the kubernetes auth type, and provides a commented section with a config block. 

copied from the readme

```
auth:
  - type: kubernetes
    # If you want to configure with specific kubernets service account instead of default service account
    # https://www.vaultproject.io/docs/auth/kubernetes.html
    # config:
    #  token_reviewer_jwt: your_service_account_jwt
    #  kubernetes_ca_cert: -----BEGIN CERTIFICATE-----.....-----END CERTIFICATE-----
    #  kubernetes_host: https://192.168.99.100:8443
    # Allows creating roles in Vault which can be used later on for the Kubernetes based
    # authentication.
    #  See https://www.vaultproject.io/docs/auth/kubernetes.html#creating-a-role for
    # more information.
    roles:
      # Allow every pod in the default namespace to use the secret kv store
      - name: default
        bound_service_account_names: default
        bound_service_account_namespaces: default
        policies: allow_secrets
        ttl: 1h
```

The config section, is not read, and the application still looks in (imho) some odd locations for the the ca.cert and token file. Since it appears to be documented, it feels like this should be supported.

**To Reproduce**
Uncomment the config section, populate with proper variables. Purge the default config dir and kubernetes host env var. Execute configure, see failure. 

**Expected behavior**
Config section allows population of configuration related to kubernetes for configuring auth.
