### ISSUE TITLE
Vault-secrets-webhook: vault-role ignored

### ISSUE THREAD

**Issue by hydratim** [banzaicloud/bank-vaults#351]
**Describe the bug**
Despite setting the annotation `vault.security.banzaicloud.io/vault-role: <my_role>` I get the error `* unknown role: kubernetes-vault`

**To Reproduce**
1. Create a new role
2. Configure the role policy
3. Attempt to use the `vault.security.banzaicloud.io/vault-role: <my_role>`  annotation in a kubernetes pod (as per the documentation).
4. See error in the logs

**Expected behavior**
I expect it to use the correct role as configured

**System:**
 - K8S: 1.12.4 
 - Bank-Vaults: master (current / latest) from github

**Comment by bonifaido** [comment]
Is the name of your new role `kubernetes-vault`? If yes, can you make sure it exists?

**Comment by hydratim** [comment]
No the name of my role is `role-test`, and yes it exists.

**Comment by bonifaido** [comment]
Could you please post snippets from your configs, because I don't really get the scenario fully :)

- The Deployment/Pod/ with the webhook annotations
- How you have configured the Kubernetes Auth backend, CLI or YAML snippet (if you have chosen bank-vaults to configure it for you)
- How you have configured the role CLI or YAML snippet (if you have chosen bank-vaults to configure it for you)

**Comment by bonifaido** [comment]
I wasn't able to reproduce this with the following configs:

- latest vault-operator installed
- latest vault-secrets-webhook installed

Vault CR:

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:1.0.3
  bankVaultsImage: banzaicloud/bank-vaults:latest

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"

  serviceAccount: vault

  # Specify the Service's type where the Vault Service is exposed
  serviceType: ClusterIP

  volumes:
    - name: vault-file
      persistentVolumeClaim:
        claimName: vault-file

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  unsealConfig:
    kubernetes:
      secretNamespace: default

  config:
    storage:
      file:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: johnmalkovich
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID: secretId
            AWS_SECRET_ACCESS_KEY: s3cr3t

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Example deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-role: "johnmalkovich"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      initContainers:
      - name: init-ubuntu
        image: ubuntu
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo initContainers ready"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
```

With this everything is working fine. If I change the role to johndoe for example it gets broken of course.
