### ISSUE TITLE
`vault-unseal-keys` not created when using an alternative namespace

### ISSUE THREAD

**Issue by jurgenweber** [banzaicloud/bank-vaults#352]
As requested by 'nandi' on the Banzai Cloud slack, I am reporting this as a bug:

**Describe the bug**
I have setup my 'unseal config' as follows:
```
  unsealConfig:
    kubernetes:
      secretNamespace: secrets
```
The secret is not created so when the stateful sets pods are created, they fail:
```
vault-4 bank-vaults 2019-03-07T05:03:39.599932024Z time="2019-03-07T05:03:39Z" level=info msg="checking if vault is sealed..."
vault-4 bank-vaults 2019-03-07T05:03:39.600490492Z time="2019-03-07T05:03:39Z" level=info msg="vault sealed: true"
vault-4 bank-vaults 2019-03-07T05:03:39.691711418Z time="2019-03-07T05:03:39Z" level=error msg="error unsealing vault: unable to get key 'vault-unseal-0': error getting secret for key 'vault-unseal-0': secrets \"vault-unseal-keys\" not found"
```

**To Reproduce**
I have called my alternative namespace 'secrets'.
etcd-operator installed, as a cluster wide operator, installed using helmfile:
```
  - name: amazing-dog
    namespace: devops
    chart: stable/etcd-operator
    values:
      - etcdOperator:
          commandArgs:
            cluster-wide: true
```
CR for etcd cluster:
```
---
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "vault-etcd-cluster"
  namespace: secrets
  # Adding this annotation make this cluster managed by clusterwide operators
  # namespaced operators ignore it
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: 5
```
vault operator rbac file, slight changes to handle the new namespace:
```
---
# this is downloaded from https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator
  namespace: secrets
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault
  namespace: secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - vault.banzaicloud.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-operator
subjects:
  - kind: ServiceAccount
    name: vault-operator
    namespace: secrets
roleRef:
  kind: ClusterRole
  name: vault-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: secrets
roleRef:
  kind: Role
  name: vault-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: secrets
---
# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: secrets
```
Vanilla vault operator install, using helmfile:
```
  - name: secrets
    namespace: secrets
    chart: banzaicloud-stable/vault-operator
```
vault CR config:
```
---
# taken from https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr-etcd-ha.yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: secrets
spec:
  size: 5
  image: vault:1.0.0
  bankVaultsImage: banzaicloud/bank-vaults:latest
  # This option gives us the option to workaround current StatefulSet limitations around updates
  # See: https://github.com/kubernetes/kubernetes/issues/67250
  # By default it is true.
  supportUpgrade: true
  # Support for custom Vault (and sidecar) pod annotations
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault
  # Specify the Service's type where the Vault Service is exposed
  serviceType: ClusterIP
  # Specify how many nodes you would like to have in your etcd cluster
  # NOTE: -1 disables automatic etcd provisioning
  etcdSize: -1
  # Specify the PersistentVolumeClaim Spec which will be used as a storage for etcd
  # if it is not specified emptydir will be used
  etcdPVCSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # This option allows you to annotate the ETCD Cluster that Vault Operator creates.
  # It's specifically to annotate the ETCD Cluster as 'clusterwide' for a cluster wide
  # ETCD Operator, however it can be used to set any arbitrary annotations on the ETCD Cluster.
  etcdAnnotations:
    etcd.database.coreos.com/scope: clusterwide
  # Describe where you would like to store the Vault unseal keys and root token
  # in S3 encrypted with KMS.
  unsealConfig:
    kubernetes:
      secretNamespace: secrets
  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      etcd:
        address: http://vault-etcd-cluster-client:2379
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.secrets:8200
    ui: true
  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    envsConfig:
      - name: aws_auth_id
        valueFrom:
          secretKeyRef:
            name: databases
            key: aws_auth_id
      - name: aws_auth_secret
        valueFrom:
          secretKeyRef:
            name: databases
            key: aws_auth_secret
    policies:
      - name: ro_kv
        rules: path "secret/*" {
          capabilities = ["read"]
          }
      - name: rw_kv
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      # Allows creating roles in Vault which can be used later on for AWS
      # IAM based authentication.
      # See https://www.vaultproject.io/docs/auth/aws.html for
      # more information.
      - type: aws
        config:
          access_key: "${env `aws_auth_id`}"
          secret_key: "${env `aws_auth_secret`}"
          iam_server_id_header_value: vault.k8s.hipages.com.au
          # crossaccountrole:
          # # Add cross account number and role to assume in the cross account
          # # https://www.vaultproject.io/api/auth/aws/index.html#create-sts-role
          #   - sts_account: 1234561234
          #     sts_role_arn: arn:aws:iam::12345671234:role/crossaccountrole
        roles:
          # Add roles for AWS instances or principals
          # See https://www.vaultproject.io/api/auth/aws/index.html#create-role
          - name: DevFullAccess
            bound_iam_principal_arn: arn:aws:iam::855460960717:role/DeveloperFullAccess
            policies: ro_kv
            period: 1h
          - name: Administrator
            bound_iam_principal_arn: arn:aws:iam::855460960717:role/Administrator
            policies: root
            period: 1h
            # - name: cross-account-role
            #   bound_iam_principal_arn: arn:aws:iam::12345671234:role/crossaccountrole
            #   policies: ro_kv
            #   period: 1h
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: ro_kv
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
```

I am receiving no errors but the ones outlined, What actually makes this secret? I see the configurer deployment fails as well, unable to contact the vault cluster.

**Expected behavior**
I expected my vault cluster to come up, with seal/unseal keys.

**Screenshots**

**Desktop (please complete the following information):**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
