### ISSUE TITLE
provide support for the prometheus operator ServiceMonitor CR

### ISSUE THREAD

**Issue by jurgenweber** [banzaicloud/bank-vaults#383]
**Is your feature request related to a problem? Please describe.**
the CoreOS Prometheus Operator is here, offically support it by providing a ServiceMonitor resource in vault-operator

**Describe the solution you'd like**
a flag to choose between the scrape annotations for prometheus vs a service monitor.

**Additional context**
You will need two variants, vault 1.0 and vault 1.1.. an example ServiceMonitor resource below:

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: vault
    release: prometheus-operator
  name: prometheus-operator-vault
  namespace: secrets
spec:
  endpoints:
   # this scrapes the statsd exporter in 1.0
    - interval: 30s
      port: prometheus
  # this scrapes the native endpoint in 1.1
    - bearerTokenFile: /etc/prometheus/secrets/vault-prometheus-endpoint-token/vault.token
      interval: 30s
      params:
        format: ['prometheus']
      path: /v1/sys/metrics
      port: api-port
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/secrets/vault-tls/ca.crt
        certFile: /etc/prometheus/secrets/vault-tls/server.crt
        keyFile: /etc/prometheus/secrets/vault-tls/server.key
        insecureSkipVerify: true
  selector:
    matchLabels:
      app: vault
      vault_cr: vault
```
