### ISSUE TITLE
Setting audit to type file with path stdout does not configure vault

### ISSUE THREAD

**Issue by pickledrick** [banzaicloud/bank-vaults#384]
**Describe the bug**

When creating an audit of type within a vault's externalConfig with the path set to stdout, configurator does not configure vault as such.

**To Reproduce**

Using the following CR and the bank-vaults installation at version 0.4.6 vault is not configured as expected below

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: vault
spec:
  size: 1
  image: vault:1.0.0
  bankVaultsImage: banzaicloud/bank-vaults:0.4.6
  supportUpgrade: true
  serviceAccount: vault
  etcdSize: 1
  etcdPVCSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  etcdAnnotations:
    etcd.database.coreos.com/scope: clusterwide
  unsealConfig:
    kubernetes:
      secretNamespace: vault
  config:
    storage:
      etcd:
        address: https://etcd-cluster-client:2379
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.vault:8200
    telemetry:
      statsd_address: localhost:9125
    ui: false
  externalConfig:
    policies:
      - name: 1_secret_admin
        rules: path "secret/1/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }                  
      - name: 2_secret_admin
        rules: path "secret/2/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: certificates_secret_admin
        rules: path "secret/certificates/*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }             
      - name: policy_modifier
        rules: path "sys/policies/acl/*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
      - name: kube_modifier
        rules: path "auth/kubernetes/*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: syncer
            bound_service_account_names: default
            bound_service_account_namespaces: sync
            policies: 
              - certificates_secret_admin
              - 1_secret_admin
              - 2_secret_admin
              - policy_modifier
              - kube_modifier
            ttl: 1h
    audit:
      - type: file
        options:
          file_path: stdout
```

**Expected behavior**
I expect to see the stdout audit configured as such, after performing the cli enable command

➜  ~ vault audit enable file file_path=stdout
Success! Enabled the file audit device at: file/
➜  ~ vault audit list

Path     Type    Description
----     ----    -----------
file/    file    n/a
➜  ~

**Screenshots**

➜  ~ vault audit list

No audit devices are enabled.

**Comment by primeroz** [comment]
For reference this works for me, with slightly different versions of componnets though

```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  annotations:
    app.kubernetes.io/managed-by: kustomize
    mintel.com/env: dev
  labels:
    app: vault
    app.kubernetes.io/app: vault
  name: vault
  namespace: vault
spec:
  bankVaultsImage: banzaicloud/bank-vaults:0.4.15-rc.3
  config:
    cluster_name: vault
    listener:
    - tcp:
        address: 0.0.0.0:8300
        tls_cert_file: /etc/cert-manager/tls.crt
        tls_disable: "false"
        tls_key_file: /etc/cert-manager/tls.key
        tls_min_version: tls12
    - tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_disable: "false"
        tls_key_file: /vault/tls/server.key
        tls_min_version: tls12
    storage:
      gcs:
        bucket: vault-storage
        ha_enabled: "true"
    telemetry:
      statsd_address: localhost:9125
    ui: true
  externalConfig:
    audit:
    - description: STDOUT Audit logging
      options:
        file_path: stdout
      type: file
  image: vault:1.1.0

```


```
kubectl logs -n vault vault-configurer-5b6cdcd778-sqqvn | grep -i audit
time="2019-03-29T08:45:04Z" level=info msg="Already existing audit devices: map[string]*api.Audit{}\n"
time="2019-03-29T08:45:04Z" level=info msg="Enabling audit device with options: api.EnableAuditOptions{Type:\"file\", Description:\"STDOUT Audit logging\", Options:map[string]string{\"file_path\":\"stdout\"}, Local:false}\n"
time="2019-03-29T08:45:05Z" level=info msg="mounted audit device file to file"
time="2019-03-29T08:45:08Z" level=info msg="Mounting secret engine with input: api.MountInput{Type:\"kv\", Description:\"KV for sanbox kubernetes namespace\", Config:api.MountConfigInput{Options:map[string]string{\"version\":\"2\"}, DefaultLeaseTTL:\"\", Description:(*string)(nil), MaxLeaseTTL:\"\", ForceNoCache:false, AuditNonHMACRequestKeys:[]string(nil), AuditNonHMACResponseKeys:[]string(nil), ListingVisibility:\"\", PassthroughRequestHeaders:[]string(nil), TokenType:\"\", PluginName:\"\"}, Local:false, SealWrap:false, Options:map[string]string{\"version\":\"2\"}, PluginName:\"\"}\n"
```

```
vault audit list -tls-skip-verify
Path     Type    Description
----     ----    -----------
file/    file    STDOUT Audit logging
```

The vault-configurator should be configuring your external configs, any error out of it ?
