### ISSUE TITLE
documentation: should annotations be under metadata in example?

### ISSUE THREAD

**Issue by tony-kerz** [banzaicloud/bank-vaults#433]
in [this example](https://github.com/banzaicloud/bank-vaults#example) in documentation, shouldn't it read like this:
```yaml
  template:
    metadata:
      labels:
        app: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
```
vs this:
```yaml
  template:
    metadata:
      labels:
        app: vault
    annotations:
      vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
      vault.security.banzaicloud.io/vault-role: "default"
      vault.security.banzaicloud.io/vault-skip-verify: "true"
      vault.security.banzaicloud.io/vault-path: "kubernetes"
```
?
