### ISSUE TITLE
Cannot store recovery keys in Google Cloud Storage

### ISSUE THREAD

**Issue by dingxiangfei2009** [banzaicloud/bank-vaults#445]
**Describe the bug**
`bank-vault` cannot store Vault recovery keys, because while checking if the recovery key is already present in the bucket the returned error is `googleapi: Error 404: Not Found, notFound` instead of `kv.NotFoundError`. cf. https://github.com/banzaicloud/bank-vaults/blob/ef4b5a00bbbd0aba5569b535563f4a81716cf2cf/pkg/vault/operator_client.go#L175

**To Reproduce**
1. Deploy `vault-operator` @ v0.4.14 into a GKE cluster
2. Deploy a simple Vault with the following configuration:
```yaml
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      preFlightChecks: true
    google:
      kmsKeyRing: <REDACTED>
      kmsCryptoKey: <REDACTED>
      kmsLocation: <REDACTED>
      kmsProject: <REDACTED>
      storageBucket: <REDACTED>
  config:
    seal:
      gcpckms:
        project: <REDACTED>
        region: <REDACTED>
        key_ring: <REDACTED>
        crypto_key: <REDACTED>
```
3. Notice that in the container log of `bank-vault`:
```
level=fatal msg="error initializing vault: error storing recovery key 'vault-recovery-0': googleapi: Error 404: Not Found, notFound"
```

**Expected behavior**
Storing recovery key should have been successful and Vault initialization should progress.
