### ISSUE TITLE
Cert auth configuration

### ISSUE THREAD

**Issue by polycaster** [banzaicloud/bank-vaults#462]
Hi,

I'm currently facing an issue while using the `cert` auth.

Here's a snippet of the configuration:
```
  externalConfig:
    auth:
      - type: cert
        roles:
          - name: jenkins
            policies: jenkins
            display_name: jenkins
            certificate: |
              -----BEGIN CERTIFICATE-----
                             (...)
              -----END CERTIFICATE-----
            ttl: 3600
```

This configuration accomplishes the goal of enabling the default `auth/cert/certs` path that I can authenticate against, however it does not create the specified role. 

I can't seem to find any examples of this across the repository or in the documentation. I've inclusively checked the old readme version where there were examples on it but cert auth is not one of them.

My question is, is there something wrong with this configuration or is role creation for cert backend not supported?

Thank you in advance.
