### ISSUE TITLE
Error with TLS Certificate

### ISSUE THREAD

**Issue by misanche** [banzaicloud/bank-vaults#471]
**Describe the bug**
I have deployed vault in one namespace named: vault and I want to retrieve the credentials from an springboot app, deployed in example namespace. I get the following error:

2019-05-17 14:24:03.115  WARN 1 --- [           main] LeaseEventPublisher$LoggingErrorListener : [RequestedSecret [path='database/creds/pg-readwrite', mode=RENEW]] Lease [leaseId='null', leaseDuration=0, renewable=false] I/O error on POST request for "https://vault.vault.svc:8200/v1/auth/kubernetes/login": Certificate for <vault.vault.svc> doesn't match any of the subject alternative names: [vault.vault, 127.0.0.1]; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for <vault.vault.svc> doesn't match any of the subject alternative names: [vault.vault, 127.0.0.1]

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://vault.vault.svc:8200/v1/auth/kubernetes/login": Certificate for <vault.vault.svc> doesn't match any of the subject alternative names: [vault.vault, 127.0.0.1]; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for <vault.vault.svc> doesn't match any of the subject alternative names: [vault.vault, 127.0.0.1]

**To Reproduce**
1. Operator deployed in vault namespace
2. rc.yaml changed to:
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:1.1.0
  bankVaultsImage: banzaicloud/bank-vaults:latest

  # Support for custom Vault (and sidecar) pod annotations
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"

  # Support for nodeAffinity Rules
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key : "node-role.kubernetes.io/your_role"
  #         operator: In
  #         values: ["true"]

  # Support for pod nodeSelector rules to control which nodes can be chosen to run
  # the given pods
  # nodeSelector:
  #   "node-role.kubernetes.io/your_role": "true"

  # Support for node tolerations that work together with node taints to control
  # the pods that can like on a node
  # tolerations:
  # - effect: NoSchedule
  #   key: node-role.kubernetes.io/your_role
  #   operator: Equal
  #   value: "true"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Specify the Service's type where the Vault Service is exposed
  serviceType: ClusterIP

  # Request an Ingress controller with the default configuration
  ingress:
    # Specify Ingress object annotations here, if TLS is enabled (which is by default)
    # the operator will add NGINX, Traefik and HAProxy Ingress compatible annotations
    # to support TLS backends
    annotations:
    # Override the default Ingress specification here
    # This follows the same format as the standard Kubernetes Ingress
    # See: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ingressspec-v1beta1-extensions
    spec: {}

  # Use local disk to store Vault file data, see config section.
  volumes:
    - name: vault-file
      persistentVolumeClaim:
        claimName: vault-file

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      preFlightChecks: true
    kubernetes:
      secretNamespace: vault

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      file:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        # Uncommenting the following line and deleting tls_cert_file and tls_key_file disables TLS
        tls_disable: false
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: example
            policies: allow_secrets
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID: secretId
            AWS_SECRET_ACCESS_KEY: s3cr3t

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  # storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: vault-file
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   hostPath:
#     path: /vault/file
```
 bootstrap.yaml:
```
spring.application.name: product-catalog 
spring.cloud.vault:
    host: vault.vault.svc
    port: 8200
    scheme: http
    authentication: KUBERNETES
    kubernetes:
        role: product-catalog
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
    config:
        order: -10
    generic:
        enabled: false
    postgresql:
        enabled: true
        role: pg-readwrite
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
    ssl:
        trust-store: mykeystore.jks
        trust-store-password: s3cr3t
```
It's there any way to support vault across namespaces?

Regards,

Mikel
