### ISSUE TITLE
Webhook to support non env variables when injecting secrets from vault into a  pod

### ISSUE THREAD

**Issue by david-dc-chen** [banzaicloud/bank-vaults#484]
Current implementation of mutating webhook only support injecting secret into a env variable of a pod. It will be very helpful if it also support non env vars, e.g. username and password.

If in a values.yaml file there is a section where docker repo credentials are defined ideally they should be referencing a secret in vault like this:
```
imageCredentials:
   registry: docker.k8s.apim.com
   username: "vault:secret/dockerrepo#DOCKER_REPO_USER"
   password: "vault:secret/dockerrepo#DOCKER_REPO_PASSWORD" 
```
In my case they are then used by  a template and eventually becomes a secret.
template "imagePullSecret":
```
{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
```
```
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
```

What is supported now is env variable, g.g.
```
	env:
	- name: AWS_SECRET_ACCESS_KEY
		value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY"
```
