### ISSUE TITLE
feature request: vault-env option to pass through VAULT env vars to main process

### ISSUE THREAD

**Issue by stephenmuss** [banzaicloud/bank-vaults#509]
I have a scenario in which I'd like some of the vault related environment variables to not be sanitized by vault-env and get passed through to the main container process.

It would be great if there was a mechanism to pass environment variables such as `VAULT_ADDR` to the main process.

For example, this could be done with an annotation such as `vault.security.banzaicloud.io/vault-env-passthrough` and the environment variable `VAULT_ENV_PASSTHROUGH`.

It would look something like:

```yaml
annotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault.my.org"
  vault.security.banzaicloud.io/vault-role: "myrole"
  vault.security.banzaicloud.io/vault-env-passthrough: "VAULT_ADDR,VAULT_ROLE"
```

`VAULT_ADDR` and `VAULT_ROLE` would then be passed through to the main container process.

Would you be willing to receive a pull request with this functionality?
