### ISSUE TITLE
Support for env interpolation in Vault config

### ISSUE THREAD

**Issue by ekarlso** [banzaicloud/bank-vaults#541]
**Describe the bug**
Vault crashes when using env var interpolation

```
Error initializing storage of type mysql: failed to check mysql schema exist: Error 9999: An internal error has occurred. Please retry or report your issues.
```

**To Reproduce**
Have a MySQL storage backend at azure with mysql config for vault.

Create the Vault CR below
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault-system
spec:
  size: 2
  image: vault:1.1.0
  bankVaultsImage: banzaicloud/bank-vaults:latest

  unsealConfig:
    azure:
      keyVaultName: myvault-vault-test

  serviceAccount: vault

  config:
    storage:
      mysql:
        username: '${env "ROOT_USERNAME"}'
        password: '${env "ROOT_PASSWORD"}'
        address: "vault.mysql.database.azure.com:3306"
        ha_enabled: "true"
        tls_ca_file: /etc/digicert-ca/ca.pem

    listener:
      tcp: 0.0.0.0:8200
      tls_cert_file: /vault/tls/server.crt
      tls_key_file: /vault/tls/server.key

    api_addr: https://vault.vault-infra:8200
    ui: true
    log_level: "Trace"

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
  volumes:
    - name: digicert-secret
      secret:
        secretName: digicert-root-ca
  volumeMounts:
    - mountPath: /etc/digicert-ca/
      name: digicert-secret
      readOnly: true
  vaultEnvsConfig:
    - name: ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: vault-db
          key: username
    - name: ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: vault-db
          key: password
    - name: VAULT_LOG_LEVEL
      value: Trace

  credentialsConfig:
    env: AZURE_AUTH_LOCATION
    path: /etc/azure/credentials
    secretName: azure-cred
```

**Expected behavior**
Vault should start.

**Versions:**
Bank Vault 0.4.17
Vault 1.1

**Additional context**
