### ISSUE TITLE
Mutating webhook for secrets uses wrong namespace

### ISSUE THREAD

**Issue by tommy-dk** [banzaicloud/bank-vaults#542]
**Describe the bug**
When trying to setup a mutating secret in a `test` namespace, I got the following message:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "secrets.vault-secrets-webhook.admission.banzaicloud.com": an error on the server ("{\"response\":{\"uid\":\"48776576-9e3f-11e9-82fc-5214ad7a0703\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"failed to create vault client: timeout [10s] during waiting for Vault token\"}}}") has prevented the request from succeeding
```

In the `vault-secrets-webhook` container log, I saw the following:

```
2019/07/04 09:42:24 Failed to request new Vault token Error making API request.

URL: PUT https://vault.redacted.net/v1/auth/kubernetes/login
Code: 500. Errors:

* namespace not authorized
```

This lead me to the assumption that when I tried creating the secret in `test` it spun up the mutating webhook in the `vault-secrets-webhook` namespace instead of `test`. Furthermore my investigation also found out that the service account used was `vault-secrets-webhook` as well.
So to mitigate this I had to convert my vault auth policy to the following:
```
vault write auth/kubernetes/role/test bound_service_account_names='vault-secrets-webhook' bound_service_account_namespaces='vault-secrets-webhook' policies=platform_product_k8s_reader ttl=1h
```

Which is quite counter-intuitive as I would've expected to use the auth policy I already created for the `test` namespace.

**Comment by pbalogh-sa** [comment]
@tommy-dk 
Your pods in `test` namespace can access to the vault with defined auth policy, but the vault-secrets-webhook also need access to it.
The vault-secrets-webhook runs in the namespace that defined during deploy. If you want you can put it to a different namespace.
Installation via helm:
`helm upgrade --namespace <your-namespace> --install name <name> banzaicloud-stable/vault-secrets-webhook`
The serviceAccountName will be generated: https://github.com/banzaicloud/banzai-charts/blob/master/vault-secrets-webhook/templates/webhook-deployment.yaml#L25

**Comment by pbalogh-sa** [comment]
@tommy-dk The auth policy is only crucial when you use secret mutation feature of the vault-secrets-webhook. You can inject directly your credentials to a pod and in this case the `vault-env` need access to the vault.

**Comment by pbalogh-sa** [comment]
You can find an example CR for vault-operator: https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml#L118-L126
In the example the vault-secrets-webhook run in the `vswh` namespace with `vault-secrets-webhook` serviceAccountName and the `default` namespace has access to the vault.

**Comment by tommy-dk** [comment]
@pbalogh-sa: Thank you for responding!

Okay, so for pod mutations I am already using namespace specific auth roles - and that is working fine. Obviously because the webhook mutates my pod and injects the init container which is then running in that particular namespace.

For secrets it is the the pod running in the `vault-secrets-webhook` namespace that does the mutation. Gotcha. 

This does create for me a bit of a limbo, since we have a multi-tenancy cluster where multiple teams have different namespaces. Those teams have individual policies in vault, so they can't read each others secrets. And this is working fine for mutating pods, but not for mutating secrets, since I don't want to create a policy in vault that can reads all secrets. Do you have any suggestions for this?

**Comment by pbalogh-sa** [comment]
@tommy-dk The secret mutation feature was implemented due to some official helm charts which are using secrets for credentials. I think mutating secrets not so secure because your credentials are put to a k8s secret. You'd better to use pod mutation feature, but if it's crucial to use secret mutation you will be able to create per team webhook.

**Comment by tommy-dk** [comment]
@pbalogh-sa: Thanks for the clarification. 👍
I don't think it's crucial for our usage, but it would've been a nice feature to present to our development teams.

Another question though. How often will a mutating secret query vault for updates to the secret?

**Comment by pbalogh-sa** [comment]
@tommy-dk The webhook only mutates secrets when they are updated or created. If you want to refresh your credentials in your pods you can do it with `consul-template` feature: https://github.com/banzaicloud/bank-vaults/blob/master/docs/mutating-webhook/consul-template.md

**Comment by sparqueur** [comment]
Hi @pbalogh-sa 
I was facing the same missunderstand.
We have a multi tenant projet with a namespace partitioning (one namespace per tenant).
I was exepting to have one and only one webhook deployed anywhere in the cluster and being able to configure vault with the following policies and roles :
```yaml
externalConfig:
  policies:
     - name: tenant1_policy
       rules: path "secret/data/tenant1/*" { capabilities = ["create", "read" ...] }
     - name: tenant2_policy
        rules: path "secret/data/tenant2/*" { capabilities = ["create", "read" ...] }
  auth:
      - type: kubernetes
        roles:
          - name: tenant1_role
            bound_service_accound_names: ["*"]
            bound_service_account_namespaces: [ "tenant1-namespace" ]
            policies: [ "tenant1_policy" ]
          - name: tenant2_role
            bound_service_accound_names: ["*"]
            bound_service_account_namespaces: [ "tenant2-namespace" ]
            policies: [ "tenant2_policy" ]
```
Can you confirm that this is not possible ?
What I understand from your discussion that I have to deploy a dedicated webhook in each namespace. Am I right ?

**Comment by pbalogh-sa** [comment]
Hi @sparqueur ! You don't have to deploy dedicated webhook per namespaces. You define the vault parameters per deployment. For example in case of tenant1:
```yaml
      ...
      annotations:
        vault.security.banzaicloud.io/vault-addr: "your_vault_adds"
        vault.security.banzaicloud.io/vault-tls-secret: "your_vault_tls_secret"
        vault.security.banzaicloud.io/vault-role: "tenant1_role"
      ....
```
adn in case of tenant2:
```yaml
     ...
      annotations:
        vault.security.banzaicloud.io/vault-addr: "your_vault_adds"
        vault.security.banzaicloud.io/vault-tls-secret: "your_vault_tls_secret"
        vault.security.banzaicloud.io/vault-role: "tenant2_role"
       ...
```
You can find some [examples](https://github.com/banzaicloud/bank-vaults/blob/master/deploy/test-deployment.yaml)
