### ISSUE TITLE
Application pods are not created due to webhook panic

### ISSUE THREAD

**Issue by estahn** [banzaicloud/bank-vaults#548]
**Describe the bug**

Application pods are not created due to webhook panic.
```
Error creating: Internal error occurred: failed calling admission webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://secrets-webhook-vault-secrets-webhook.secrets.svc:443/pods?timeout=30s: stream error: stream ID 1642099; INTERNAL_ERROR
```

Webhook:

```
2019/07/15 05:50:30 http2: panic serving 100.105.247.0:32768: runtime error: index out of range
goroutine 12008569 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000140d98, 0xc00062ffaf, 0xc000150300)
	/usr/local/go/src/net/http/h2_bundle.go:5651 +0x16b
panic(0x119f2e0, 0x1eb37a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/jsonpatch.backtrace(0xc00012ee00, 0xc, 0x10, 0xc00069e800, 0x2d, 0x40, 0xc000355820, 0x16, 0xb, 0x2c, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:329 +0x1072
github.com/appscode/jsonpatch.backtrace(0xc00012ee00, 0xc, 0x10, 0xc00069e800, 0x2d, 0x40, 0xc000355820, 0x16, 0xc, 0x2d, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:333 +0x968
github.com/appscode/jsonpatch.compareEditDistance(0xc00012ee00, 0xc, 0x10, 0xc00069e800, 0x2d, 0x40, 0xc000355820, 0x16, 0x3, 0x2, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:304 +0x3af
github.com/appscode/jsonpatch.handleValues(0x1117060, 0xc00000f380, 0x1117060, 0xc00000fd20, 0xc000355820, 0x16, 0xc0002f5000, 0x53, 0x80, 0xc0002f5000, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:217 +0xb0d
github.com/appscode/jsonpatch.diff(0xc00035a630, 0xc0003eb200, 0xc000355660, 0x12, 0xc0002f5000, 0x53, 0x80, 0x1300, 0x1, 0x80, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:170 +0x400
github.com/appscode/jsonpatch.handleValues(0x1181200, 0xc00035a630, 0x1181200, 0xc0003eb200, 0xc000355660, 0x12, 0xc0002f5000, 0x48, 0x80, 0xc0002f5000, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:206 +0xd5a
github.com/appscode/jsonpatch.handleValues(0x1117060, 0xc00000f4a0, 0x1117060, 0xc00040c080, 0xc000d54340, 0x10, 0xc0001de780, 0x5, 0x8, 0xc0001de780, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:228 +0xa2f
github.com/appscode/jsonpatch.diff(0xc00038f3b0, 0xc0003ea9c0, 0xc000d541b0, 0x5, 0x1ee6e60, 0x5, 0x8, 0x1300, 0x4, 0x0, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:170 +0x400
github.com/appscode/jsonpatch.handleValues(0x1181200, 0xc00038f3b0, 0x1181200, 0xc0003ea9c0, 0xc000d541b0, 0x5, 0x1ee6e60, 0x0, 0x0, 0x1ee6e60, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:206 +0xd5a
github.com/appscode/jsonpatch.diff(0xc00038ef30, 0xc00038eff0, 0x0, 0x0, 0x1ee6e60, 0x0, 0x0, 0x0, 0x3000, 0x2dcc, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:170 +0x400
github.com/appscode/jsonpatch.CreatePatch(0xc0005ce000, 0x261b, 0x2800, 0xc000504000, 0x2dcc, 0x3000, 0x0, 0x0, 0x128e780, 0x12cf560, ...)
	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20190108182946-7c0e3b262f30/jsonpatch.go:71 +0x1ab
github.com/slok/kubewebhook/pkg/webhook/mutating.(*staticWebhook).mutatingAdmissionReview(0xc000183bc0, 0x14be340, 0xc000350150, 0xc000350060, 0x14f6920, 0xc0002e0700, 0x14f6920, 0xc000954380, 0xc0002e0700)
	/go/pkg/mod/github.com/slok/kubewebhook@v0.2.0/pkg/webhook/mutating/webhook.go:147 +0x188
github.com/slok/kubewebhook/pkg/webhook/mutating.(*staticWebhook).Review(0xc000183bc0, 0x14be340, 0xc000350150, 0xc000350060, 0x1280e40)
	/go/pkg/mod/github.com/slok/kubewebhook@v0.2.0/pkg/webhook/mutating/webhook.go:123 +0x50c
github.com/slok/kubewebhook/pkg/webhook/internal/instrumenting.(*Webhook).Review(0xc0002b0000, 0x14be340, 0xc0003500f0, 0xc000350060, 0x0)
	/go/pkg/mod/github.com/slok/kubewebhook@v0.2.0/pkg/webhook/internal/instrumenting/instrumenting.go:42 +0x24f
github.com/slok/kubewebhook/pkg/http.HandlerFor.func1(0x14baa00, 0xc000140d98, 0xc00012e400)
	/go/pkg/mod/github.com/slok/kubewebhook@v0.2.0/pkg/http/handler.go:64 +0x1e9
net/http.HandlerFunc.ServeHTTP(0xc00016b8e0, 0x14baa00, 0xc000140d98, 0xc00012e400)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00027ba40, 0x14baa00, 0xc000140d98, 0xc00012e400)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0001691e0, 0x14baa00, 0xc000140d98, 0xc00012e400)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc0002e0000, 0xc0001691e0, 0x14baa00, 0xc000140d98, 0xc00012e400)
	/usr/local/go/src/net/http/server.go:3323 +0x8d
net/http.(*http2serverConn).runHandler(0xc000150300, 0xc000140d98, 0xc00012e400, 0xc00049c5a0)
	/usr/local/go/src/net/http/h2_bundle.go:5658 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5392 +0x4f4
```

**To Reproduce**
N/A

**Expected behavior**
Do not fail.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by bonifaido** [comment]
Hi @estahn, could you please tell the version of the webhook that are you using? (I'm extending the issue template just now, to ask the version as well).
Also what is more interesting which object mutation causes this issue? Can you post the resource YAML that you posted to the API?

**Comment by jurgenweber** [comment]
```secrets-webhook              	9       	Thu Jun 13 11:54:37 2019	DEPLOYED	vault-secrets-webhook-0.3.14                 	0.4.17-rc.2	secrets```

**Comment by jurgenweber** [comment]
Ok, we installed/setup/applied this:

https://github.com/newrelic/k8s-metadata-injection
https://github.com/newrelic/k8s-metadata-injection/blob/master/deploy/newrelic-metadata-injection.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hiew
    tier: frontend
  name: admin-hiew
  namespace: engineering
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        vault.security.banzaicloud.io/vault-ct-configmap: hiew-consul-template-branches
        vault.security.banzaicloud.io/vault-role: hiew-branches
      labels:
        app: hinew
        tier: frontend
      name: admin-hiew
      namespace: engineering
    spec:
      containers:
      - env:
        - name: PHP_DATE_TIMEZONE
          value: Australia/Sydney
          - name: PHP_NEWRELIC_ENABLED
          value: "true"
         - name: LOG_LEVEL
          value: warning
        image:.dkr.ecr.ap-southeast-2.amazonaws.com/hipagesgroup/hiew:latest
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        name: fpm
        readinessProbe:
          exec:
            command:
            - goss
            - -g
            - .goss/goss.yaml
            - validate
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512M
          requests:
            cpu: 50m
            memory: 256M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www
          name: app-volume
      - env:
        - name: DOCUMENT_ROOT
          value: /var/www/html/hip/admin
        - name: FPM_SERVICE_HOST
          value: 127.0.0.1
        - name: FPM_SERVICE_PORT
          value: "9000"
        - name: ServerAlias
          value: admin-* admin.*
        - name: ServerName
          value: admin-beta.k8s.hipages.com.au
        image: .dkr.ecr.ap-southeast-2.amazonaws.com/hipages/apache:REL21706
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: apache
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        resources:
          limits:
            memory: 64M
          requests:
            cpu: 20m
            memory: 32M
        volumeMounts:
        - mountPath: /var/www
          name: app-volume
        - mountPath: /etc/apache2/sites-enabled/vault.conf
          name: hip-new-apache-vault-branches
          readOnly: true
          subPath: vault.conf
      - env:
        - name: PHP_FPM_SCRAPE_URI
          value: tcp://127.0.0.1:9000/status
        - name: PHP_FPM_FIX_PROCESS_COUNT
          value: "1"
        image: hipages/php-fpm_exporter:0.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 9253
          timeoutSeconds: 1
        name: phpfpmexporter
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9253
          timeoutSeconds: 1
        resources:
          limits:
            memory: 16M
          requests:
            cpu: 10m
            memory: 8M
      initContainers:
      - command:
        - cp
        - -r
        - /var/www/html/
        - /html
        image:.dkr.ecr.ap-southeast-2.amazonaws.com/hipagesgroup/hiew:latest
        imagePullPolicy: IfNotPresent
        name: code-copy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /html
          name: app-volume
      volumes:
      - emptyDir: {}
        name: app-volume
      - configMap:
          defaultMode: 420
          items:
          - key: vault.conf
            path: vault.conf
          name: hip-new-apache-vault-branches
        name: hip-new-apache-vault-branc
```
