### ISSUE TITLE
[vault-secrets-webhook] HorizontalPodAutoscaler fails with Consul-Template

### ISSUE THREAD

**Issue by marcoreni** [banzaicloud/bank-vaults#554]
**Describe the bug**:
When using sidecar injection, the HPA fails:
```
 Warning  FailedComputeMetricsReplicas  23m (x4 over 24m)     horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu on container consul-template in pod xxxxx
  Warning  FailedGetResourceMetric       3m17s (x43 over 24m)  horizontal-pod-autoscaler  missing request for cpu on container consul-template in pod xxxxx

```

Should we be able to set resource limits/requests for the sidecar somehow? Or may we set some sane defaults that gets applied anyway?

**Environment details**:
- Kubernetes version (e.g. v1.11.2): 1.11.8
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 0.4.17
- Resource definition:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: test-deployment-with-injection
  targetCPUUtilizationPercentage: 80
```

/kind bug
