### ISSUE TITLE
[cli-tool] Removing externalConfig entity doesn't clean up Vault config

### ISSUE THREAD

**Issue by chrisob** [banzaicloud/bank-vaults#605]
Apologies if this is known/desired behavior. I did some digging through existing issues but wasn't able to find anything.

**Is your feature request related to a problem? Please describe.**
It seems that if you remove a `Vault` CR's `externalConfig` entity in-place, the related entity in the Vault instance's config isn't removed, leaving a "dangling" resource that isn't represented as code.

In other words, if I apply a `Vault` CR with this `externalConfig`:
```yaml
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: test
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
```
And the re-apply with same CR with the `externalConfig` block modified as such, with the `test` policy removed:
```yaml
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
```
...Vault's config will still retain the `test` policy.

**Describe the solution you'd like**
In the interest of keeping application config declarative, it'd be nice if `bank-vaults configure` was (optionally?) able to clean-up `externalConfig` entities that are no longer under its management. 

**Describe alternatives you've considered**
I guess one could remember to manually clean up old config resources in Vault when they're removed from the Vault CR, but that would defeat the purpose of having declarative config.
