### ISSUE TITLE
Referenced externalConfig examples don't exist

### ISSUE THREAD

**Issue by chiefy** [banzaicloud/bank-vaults#618]
Currently a lot of the YAML in this project references `https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration` which AFAIK doesn't exist anymore? Would be handy to have some varied examples. Thanks.

**Comment by bonifaido** [comment]
Yes! Those haven't been updated, sorry for that! Have you checked ?https://github.com/banzaicloud/bank-vaults/blob/master/docs/cli-tool/README.md#example-external-vault-configuration

**Comment by bonifaido** [comment]
Did you have luck with the examples @chiefy ?

**Comment by chiefy** [comment]
Sorry, thanks @bonifaido - it'd be nice if there was clear documentation of what is/isn't supported out-of-the-box. I've had some weird results with `authRole` stuff.

**Comment by bonifaido** [comment]
If you could describe what issues you had with authRoles, that would be helpful, and we can improve the docs. Did you manage to setup what you wanted? What was you setup?

We have a slack channel as well in the meantime. (#bank-vaults on https://slack.banzaicloud.io/) where users and developers are there to discuss issues.

**Comment by chiefy** [comment]
@bonifaido it was mostly around attaching policies to authRoles. I had to use the form:

```
    auth:
      - type: approle
        roles:
          - name: cert-manager
            policies: 
              - cert-manager
            token_ttl: 30m
```

whereas 

```
    auth:
      - type: approle
        roles:
          - name: cert-manager
            policies:  cert-manager
            token_ttl: 30m
```

didn't attach the polciy
