### ISSUE TITLE
Secret not found error when optional with webhook

### ISSUE THREAD

**Issue by callaertanthony** [banzaicloud/bank-vaults#619]
**Describe the bug**:
When an optional secret doesn't exists in secrets, there is an error thrown.
```
Error creating: Internal error occurred: failed calling webhook
"pods.vault-secrets-webhook.admission.banzaicloud.com":
an error on the server ("{\"response\":{\"uid\":\"***\",\"allowed\":false,\"status\":
{\"metadata\":{},\"status\":\"Failure\",\"message\":
\"secrets \\\"secret-***\\\" not found\"}}}") has prevented the request from succeeding
```

**Expected behaviour**:
Because secret can be optional in [Kubernetes definition type](https://github.com/kubernetes/kubernetes/blob/b29e187a45243241ae8d3cb6e92fea87efab6ca5/pkg/apis/core/types.go#L1812) no error should be thrown
```
// SecretKeySelector selects a key of a Secret.
type SecretKeySelector struct {
	// The name of the secret in the pod's namespace to select from.
	LocalObjectReference
	// The key of the secret to select from.  Must be a valid secret key.
	Key string
	// Specify whether the Secret or its key must be defined
	// +optional
	Optional *bool
}
```

I think [this line](https://github.com/banzaicloud/bank-vaults/blob/5e9caa4c8b11aa1f010ee35a2f30d08b4ec3a9aa/cmd/vault-secrets-webhook/main.go#L481) causes the error.

**Steps to reproduce the bug**:
Create a deployment with an optional secret not created into the environment.
```
containers:
- name: container-name
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  envFrom:
  - secretRef:
      name: my-optional-secret #the secret not existing
      optional: true
```

Regards

/kind bug
