### ISSUE TITLE
Secret vault injection for kubernetes/helm secrets

### ISSUE THREAD

**Issue by asanami** [banzaicloud/bank-vaults#648]
**Is your feature request related to a problem? Please describe.**

I'm trying to see if it possible to use the vault webhook to configure a helm chart's password which is set via `Secret.yaml`.  For example, the grafana helm chart (https://github.com/helm/charts/tree/master/stable/grafana) configures the default admin username/password using the following:

values.yaml
```
grafana:
  admin:
    existingSecret: grafana-secret
```

templates/secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  admin-user: admin
  admin-password: <inject-via-vault?>
```

**Describe the solution you'd like**

Is it possible to use the vault webhook as a solution to setting usernames and passwords via this method.

**Describe alternatives you've considered**

I could patch the helm chart to set the secret in the pod via the deployment.yaml as documented.

**Comment by bonifaido** [comment]
Hi @asanami,

something like this is certainly possible, we have support, for example, setting like this, and the webhook will try to read the secret from Vault if `grafana-secret` is used in env var:

```yaml
    admin-password: "vault:secret/grafana#password"
```

**Comment by asanami** [comment]
It works! Thank you for the information.  For other people's reference, I did the following, using grafana as an example:

`values.yaml`
```
grafana:
  serviceAccount:
    name: vault-test
    nameTest:
    create: false
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  admin:
    existingSecret: grafana-vault-secret
```
templates/secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-vault-secret
type: Opaque
data:
  admin-user: admin  # needs to be base64-encoded>
  admin-password: vault:secret/data/secret#SECRET_ACCESS_KEY (# needs to be base64 encoded)
```
