### ISSUE TITLE
Secrets webhook can't retrieve images from Harbor registry

### ISSUE THREAD

**Issue by funkypenguin** [banzaicloud/bank-vaults#712]
**Describe the bug**:
When I use secrets-webhook against a pod with an image in a local, public, [Harbor-based registry](https://goharbor.io), the webhook fails to get credentials to the registry and logs a 401 error.

When I attempt the same against docker.io (also a public registry), no error is produced.

**Expected behaviour**:
The behaviour of secrets-webhook against a Harbor public registry would be the same as that against docker.io

**Steps to reproduce the bug**:
1. Deploy an instance of harbor. Harbor's default project "library" is public by default. 
2. Attempt to use vault secret injection against a pod with an image in this registry.
3. Review the logs of the secrets-webhook pod

**Additional context**:
Here are the logs from an attempt against the Harbor public registry:

```
time="2019-10-22T03:44:46Z" level=info msg="found no credentials for registry , assuming it is public"
time="2019-10-22T03:44:46Z" level=info msg="I'm using registry https://registry-internal.elpenguino.net"
2019/10/22 03:44:46 registry.ping url=https://registry-internal.elpenguino.net/v2/
time="2019-10-22T03:44:46Z" level=error msg="admission webhook error: cannot create client for registry: Get https://registry-internal.elpenguino.net/v2/: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":null}]}\\n\")"
```

Here are the logs against docker.io:

```
time="2019-10-22T03:41:48Z" level=info msg="found no credentials for registry index.docker.io, assuming it is public"
time="2019-10-22T03:41:48Z" level=info msg="I'm using registry https://index.docker.io"
2019/10/22 03:41:48 registry.ping url=https://index.docker.io/v2/
2019/10/22 03:41:51 registry.manifest.get url=https://index.docker.io/v2/library/vault/manifests/1.2.2 repository=library/vault reference=1.2.2
2019/10/22 03:41:53 registry.blob.download url=https://index.docker.io/v2/library/vault/blobs/sha256:f4f349f61c74dadfba8229f48a11975e2b1ad6ea046329d258fc99945be03f7a repository=library/vault digest=sha256:f4f349f61c74dadfba8229f48a11975e2b1ad6ea046329d258fc99945be03f7a
time="2019-10-22T03:42:21Z" level=info msg="found image vault:1.2.2 in cache"
```

The harbor container logs the following, at the time:

```
harbor_core.1.w8uzy0f2s1gn@cn1    | 2019/10/22 03:21:21 [D] [server.go:2774] |  192.168.33.24| 401 |   2.217229ms|   match| GET      /v2/   r:/v2/*
```

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.16.0
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare-metal deploymen
- bank-vaults version (e.g. 0.4.17): 0.5.3
- Install method (e.g. helm or static manifests): Helm, tillerless
- Logs from the misbehaving component (and any other relevant logs): (above)
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

CR for the vault which caused the above issue:

```
---

# This Vault CR describes the setup of the Tenant Vault instance
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "prod-vault"
spec:
  size: 1
  image: registry-internal.elpenguino.net/library/vault:1.2.2
  bankVaultsImage: registry-internal.elpenguino.net/library/bank-vaults:0.5.3

  # We don't need any extra RBAC rules besides the default ones
  serviceAccount: default

  # Even if unsealing will be done via the Transit Auto-Unseal flow the root token
  # and recovery keys will be stored in Kubernetes Secrets if not defined otherwise,
  # not highly secure, but this is just an example, in production please use one of
  # the KMS based options.

  # This is how the Bank-Vaults configurer should configure Vault to enable the
  # transit auto-unseal flow for the this instance, the seal stanza is the interesting
  # part where we connect to the central instance, the token will be injected
  # by the webhook automatically.
  # The automated version of:
  # https://learn.hashicorp.com/vault/operations/autounseal-transit#step-2-configure-auto-unseal-vault-2
  config:
    seal:
      transit:
        address: "https://vault.vault:8200"
        # token: will be injected via the webhook through VAULT_TOKEN="vault:login"
        key_name: autounseal
        mount_path: prod/transit
        tls_ca_cert: "/cluster-vault/tls/ca.crt"
    storage:
      file:
        path: /vault/file
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.prod:8200
    ui: true

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    # Allow every pod in the application namespace to use the secret kv store
    auth:
      - type: kubernetes
        roles:
          - name: application
            bound_service_account_names: ["default"]
            bound_service_account_namespaces: ["prod"]
            policies: allow_secrets
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

  # The VAULT_TOKEN environment variable will be read by Vault to login
  # for unsealing, the "vault:" special prefix instructs the webhook to
  # mutate the Pod and pass in  variable directly to the process with
  # vault-env.
  vaultEnvsConfig:
    - name: VAULT_TOKEN
      value: "vault:login"

  # vault-env from the above block needs some information to know how
  # to login into Vault with the Kubernetes auth method, and where to
  # find the TLS CA certificate for it. Since the operator was asked
  # to distribute the CA of central-vault instance to other namespaces
  # with `caNamespaces:` it will find in the "central-vault-tls" Secrets.
  # This will be mounted automatically by the webhook into the Pod.
  vaultAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: prod
    vault.security.banzaicloud.io/vault-path: prod/kubernetes
    vault.security.banzaicloud.io/vault-tls-secret: "cluster-vault-tls"

  # Persistence done in the same way as for central-vault
  volumes:
    - name: vault-file
      persistentVolumeClaim:
        claimName: vault-file
    - name: central-vault-tls
      secret:
        secretName: central-vault-tls

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file
    - name: cluster-vault-tls
      mountPath: /cluster-vault/tls

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

I realise that this may well be a harbor bug, rather than a secrets-webhook bug - I'll open a related issue with Harbor as well. I felt it worth creating this issue since this would presumably affect **any** Harbor users.

/kind bug
