### ISSUE TITLE
vault-secrets-webhook: Setting podsFailurePolicy=Fail can prevent successful helm install 

### ISSUE THREAD

**Issue by donaldguy** [banzaicloud/bank-vaults#743]
**Describe the bug**:

Running helm install of the chart: https://github.com/banzaicloud/bank-vaults/tree/chart/vault-secrets-webhook/0.5.5/charts/vault-secrets-webhook with values including `podsFailurePolicy: Fail` doesn't terminate successfully, getting stuck with Events spawned like

```
kube-vault    41s         Warning   FailedCreate              replicaset/vault-secrets-webhook-5f9f969f86   Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://vault-secrets-webhook.kube-vault.svc:443/pods?timeout=30s: dial tcp 10.103.88.226:443: connect: connection refused
```

correctly corresponding to  an empty endpoints collection and MIA pod(s)

This is easily enough explained by installation of the now required MutatingWebhookConfiguration before the pods meant to handle it (which are subject to its judgement)

**Expected behaviour**:
`helm install --wait` returns and vault-secrets-webhook is installed/functional 

**Steps to reproduce the bug**:
```bash
kubectl create ns kub-vault
helm upgrade --install --reset-values vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook --version 0.5.5 --wait --kube-context minikube --namespace kube-vault --set replicaCount=1  --set  podsFailurePolicy=Fail # I also --set env.VAULT_ADDR
```
(In reality the (equivalent) of the above command was generated by running [roboll/helmfile](https://github.com/roboll/helmfile): `helmfile sync` with (amongst other parts)

```yaml
environments:
  default:
    values:
    - vault: {address: "https://vault.service.consul:8200"}
  dev:
    values:
    - vault: {address: "http://vault.service.consul:8200" }


repositories:
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com

helmDefaults:
{{ if eq .Environment.Name "dev" }}
  kubeContext: minikube
{{ end }}
  wait: true

releases:
- name: vault-secrets-webhook
  namespace: kube-vault
  chart: banzaicloud-stable/vault-secrets-webhook
  version: "0.5.5"
  hooks:
  - events: ["prepare"]
    showlogs: true
    command: "bash"
    args:
    - -ec
    - |
      kubectl get ns kube-vault || kubectl create ns kube-vault;
      kubectl --namespace=default get secret regcred --export -oyaml | kubectl apply --namespace=kube-vault -f -
  values:
{{ if eq .Environment.Name "dev" }}
  - replicaCount: 1
{{ else }}
  - priorityClassName: "system-cluster-critical"
{{ end }}
  - podsFailurePolicy: Fail
  - env:
      VAULT_ADDR: {{ .Values.vault.address }}
```
)

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.14.7 😅 
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): minikube
- bank-vaults version (e.g. 0.4.17): 0.5.5
- Install method (e.g. helm or static manifests): helm 3.0.0-rc.4 ; helmfile v0.90.8
- Logs from the misbehaving component (and any other relevant logs): above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: above

/kind bug

--- 

arguably this is a helm bug(?) to the effect of helm/helm#5642 

but it is possible that it behooves you to inject the webhook as a post-install, post-upgrade hook and take on the overhead of a corresponding pre or post delete hook 

or maybe more simply

https://github.com/banzaicloud/bank-vaults/tree/chart/vault-secrets-webhook/0.5.5/charts/vault-secrets-webhook/templates#L52-L53

should take on an unconditional 

```yaml
- operator: NotIn
  values [{{ .Release.Namespace }}]
```

or perhaps more correctly the corresponding labelSelector for the computed app labels? (indeed I am trying to install this into a namespace along with AppsCode's KubeDB operator (for policy management CRDs, which to my knowledge bank-vaults doesn't offer) 

Thanks for a great piece of dev/operator tooling :D
