### ISSUE TITLE
[operator] vault-operator not istio-compatible

### ISSUE THREAD

**Issue by funkypenguin** [banzaicloud/bank-vaults#767]
**Describe the bug**:

When bank-vaults is deployed in an istio-enabled cluster, the vault-configurer pod can't access vault. Because the port name on the vault service is "api-port", Istio will assume the traffic is HTTP, resulting in the following error in the configurer:

```
time="2019-11-29T09:22:51Z" level=info msg="checking if vault is sealed..."
time="2019-11-29T09:22:56Z" level=error msg="error checking if vault is sealed: error checking status: Get https://cluster-vault.cluster-vault:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client, waiting 5s before trying again..."
```

**Expected behaviour**:

For Istio to behave properly, the service port name needs to include the protocol as a prefix, per https://istio.io/docs/ops/deployment/requirements/

**Steps to reproduce the bug**:

* Deploy bank-vaults into an Istio, mTLS-enabled cluster
* Create a namespace for your vault, and enable automatic sidecar injection (https://istio.io/docs/ops/configuration/mesh/injection-concepts/)
* Deploy the Vault CR into this namespace
* Examine the logs of the vault configurer pod

**Additional context**:

Slack discussion on this issue : https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1575019233269300?thread_ts=1574151626.015300&cid=CFJJW9L94

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.16.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare metal
- bank-vaults version (e.g. 0.4.17): 0.6.2
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): (Above)
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```
# Create a namespace for called "tenant" for the Tenant Vault instance,
# the Central instance will be running in "default"

apiVersion: "v1"
kind: Namespace
metadata:
  name: cluster-vault

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-vault
  namespace: cluster-vault

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: manage-secrets
  namespace: cluster-vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: permit-vault-manage-secrets
  namespace: cluster-vault
subjects:
- kind: ServiceAccount
  name: cluster-vault
  namespace: cluster-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-secrets
---
# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: cluster-vault
    namespace: cluster-vault
---
# This Vault CR describes the setup of the Central Vault instance
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: cluster-vault
  namespace: cluster-vault
spec:
  size: 1
  image: registry-internal.{{ helm_ingress_dns_suffix }}/library/vault:{{ packages.vault.version }}
  bankVaultsImage: registry-internal.{{ helm_ingress_dns_suffix }}/library/bank-vaults:{{ packages.bank_vaults.version }}
  statsdImage: registry-internal.{{ helm_ingress_dns_suffix }}/library/statsd-exporter:{{ packages.statsd_exporter.version }}

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults
  # configurer/unsealer will be running
  serviceAccount: cluster-vault

  # Specify custom ports, if you do this you are required to specify the standard ones and your custom ones
  # This is useful if you specify an extra tcp listener for vault
  # David : We do this for istio compatibility
  servicePorts:
    api-port: 8200
    cluster-port: 8201
    https-api-port: 8443
    external-port: 8300

  # Unsealing will be done via Kubernetes Secrets if not defined otherwise,
  # not highly secure, but this is just an example, in production, please
  # use one of the KMS based unseal options.
  # unsealConfig:
  # ...

  # A YAML representation of a final Vault config file, this will be mounted
  # to the Vault container directly.
  config:
    storage:
      raft:
        path: /vault/raft
    listener:
      - tcp:
          address: "0.0.0.0:8200"
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key
      - tcp:
          address: "0.0.0.0:8443"
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key          
    api_addr: http://cluster-vault.cluster-vault:8200
    cluster_addr: "https://${.Env.POD_NAME}:8200"
    ui: true

  # This is how the Bank-Vaults configurer should configure Vault to enable the
  # transit auto-unseal flow for the tenant instance.
  # The automated version of:
  # https://learn.hashicorp.com/vault/operations/autounseal-transit#cli-command
  externalConfig:

    # Configure the transit secret engine and create a key for the auto-unseal
    secrets:
      - type: transit
        path: prod/transit
        description: Transit engine for the prod namespace
        configuration:
          keys:
            - name: autounseal
              type: aes256-gcm96
              exportable: false
      - type: transit
        path: dev/transit
        description: Transit engine for the dev namespace
        configuration:
          keys:
            - name: autounseal
              type: aes256-gcm96
              exportable: false    
      - type: transit
        path: uat/transit
        description: Transit engine for the uat namespace
        configuration:
          keys:
            - name: autounseal
              type: aes256-gcm96
              exportable: false      
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2                                   

    # The tenant Vault needs to call the transit secret engine endpoints,
    # create the necessary policies to permit it
    policies:
      - name: allow_prod_transit
        rules: path "prod/transit/encrypt/autounseal" {
                 capabilities = ["update"]
                }
               path "prod/transit/decrypt/autounseal" {
                 capabilities = ["update"]
               }
      - name: allow_dev_transit
        rules: path "dev/transit/encrypt/autounseal" {
                 capabilities = ["update"]
                }
               path "dev/transit/decrypt/autounseal" {
                 capabilities = ["update"]
               }       
      - name: allow_uat_transit
        rules: path "uat/transit/encrypt/autounseal" {
                 capabilities = ["update"]
                }
               path "uat/transit/decrypt/autounseal" {
                 capabilities = ["update"]
               }                       
      - name: admin_access
        rules: |
          # Manage auth backends broadly across Vault
          path "auth/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
          # List, create, update, and delete auth backends
          path "sys/auth/*"
          {
            capabilities = ["create", "read", "update", "delete", "sudo"]
          }
          # To list policies
          path "sys/policy"
          {
            capabilities = ["read"]
          }
          # Create and manage ACL policies broadly across Vault
          path "sys/policy/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
          # List, create, update, and delete key/value secrets
          #path "secret/*"
          #{
          #  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          #}
          # Manage and manage secret backends broadly across Vault.
          path "sys/mounts/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
          # Read health checks
          path "sys/health"
          {
            capabilities = ["read", "sudo"]
          }
          # Read metrics
          path "sys/metrics"
          {
            capabilities = ["read"]
          }
          # To perform
          path "sys/capabilities"
          {
            capabilities = ["create", "update"]
          }
          # To perform
          path "sys/capabilities-self"
          {
            capabilities = ["create", "update"]
          }           

    groups:
      - name: admin-cluster-vault
        policies:
          - admin_access
        metadata:
          privileged: "true"
        type: external


    # Instead of creating a token by hand we allow the tenant Vault to request
    # one with the Kubernetes auth method, via vault-env and webhook
    auth:
      - type: kubernetes
        path: prod/kubernetes
        roles:
          # Allow every the tenant Vault Pod in the tenant namespace to use
          # its transit engine
          - name: prod
            bound_service_account_names: ["vault"]
            bound_service_account_namespaces: ["prod"]
            policies: allow_prod_transit
            ttl: 1m
      - type: kubernetes
        path: dev/kubernetes
        roles:
          # Allow every the tenant Vault Pod in the tenant namespace to use
          # its transit engine
          - name: dev
            bound_service_account_names: ["vault"]
            bound_service_account_namespaces: ["dev"]
            policies: allow_dev_transit
            ttl: 1m    
      - type: kubernetes
        path: uat/kubernetes
        roles:
          # Allow every the uat Vault Pod in the tenant namespace to use
          # its transit engine
          - name: uat
            bound_service_account_names: ["vault"]
            bound_service_account_namespaces: ["uat"]
            policies: allow_uat_transit
            ttl: 1m           

      - type: oidc
        config:
          oidc_discovery_url: "https://keycloak.{{ helm_ingress_dns_suffix }}/auth/realms/kube-cluster"
          oidc_client_id: "cluster-vault"
          oidc_client_secret: {{ cluster_vault_client_secret.json.value }}
          default_role: rg_user
        roles:
          - name: rg_user
            user_claim: email
            groups_claim: groups
            role_type: oidc
            oidc_scopes: 
              - groups
            allowed_redirect_uris:
              - https://cluster-vault.{{ helm_ingress_dns_suffix }}/ui/vault/auth/oidc/oidc/callback
              - http://localhost:8250/oidc/callback
            policies: ""  
            ttl: 10m
            max_ttl: 60m
            num_uses: 3          
          
    startupSecrets:
      - type: kv
        path: secret/data/prod/oidc
        data:
          data:       
            AWS_ACCESS_KEY_ID: secretId
            AWS_SECRET_ACCESS_KEY: s3cr3t
      - type: kv
        path: secret/data/prod/dockerrepo
        data:
          data:
            DOCKER_REPO_USER: dockerrepouser
            DOCKER_REPO_PASSWORD: dockerrepopassword
      - type: kv
        path: secret/data/prod/mysql
        data:
          data:
            MYSQL_ROOT_PASSWORD: s3cr3t   

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
      
  # Instruct the vault-operator to distribute the CA certificate of the central
  # Vault instance into other namespaces as well, this way a secure TLS connection
  # can be built up between the tenant and central Vault instances
  caNamespaces:
    - "prod"
    - "dev"
    - "uat"

  # Request and mount a Persistent Volume to this Vault instance
  # volumes:
  #   - name: vault-file
  #     persistentVolumeClaim:
  #       claimName: vault-file

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/raft

  # Maybe this will work when we get size > 1
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
        namespace: cluster-vault
      spec:
        # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

/kind bug
