### ISSUE TITLE
Feature request: startupSecret from configmap/secrets

### ISSUE THREAD

**Issue by lukasmrtvy** [banzaicloud/bank-vaults#774]
**Is your feature request related to a problem? Please describe.**
When are You bootstraping cluster ( ready to use ), there is usually need to have secrets available before bank-vaults is even deployed. 
- no ingress -> You can not connect to vault
- no certificate -> if You are using something like cert-manager, You have to solve insecure skip verify  
- no dns record -> if You are using something like external-dns, You can not even connect 

**Describe the solution you'd like**
Would be great if startupSecrets can be set from k8s secrets/configmaps ( https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml#L138 )

Something like:
```
    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
           configMapKeyRef
             - name: AWS_ACCESS_KEY_ID
               key: awsid
           secretKeyRef:
             - name: AWS_SECRET_ACCESS_KEY
               key: awskey
```

**Describe alternatives you've considered**
Is possible to run batch/job to import initial secrets from k8s to vault with some scripting.
- curl
- vault write 

**Additional context**
none
