### ISSUE TITLE
`fsGroup` Modifies Permission Bits Preventing Vault Backend PostgreSQL with Certificate-based Authentication

### ISSUE THREAD

**Issue by theonewolf** [banzaicloud/bank-vaults#777]
**Describe the bug**:
Vault refuses to read the private key file due to permissions not being 0600 or less.

**Expected behaviour**:
Expect Vault to be able to read its private key file set with permissions as described in the `cr.yaml`.

**Steps to reproduce the bug**:
1. Define a secret containing a certificate and private key for PostgreSQL.
2. Mount this secret with permission bits explicitly set.

Something like:

```
...
    volumeMounts:
    - mountPath: /certs/client/
      name: client-cert
      readOnly: true
...

  volumes:
  - name: client-cert
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: tls.crt
            mode: 256
            path: tls.crt
          - key: tls.key
            mode: 256
            path: tls.key
          name: vault-client
...
```

3. When running, the Vault container complains that:

> Error initializing storage of type postgresql: failed to check for native upsert: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less

**Additional context**:
I modified operator-generated YAML so that I could get a shell inside the Vault container.

Here's what I found:

- Permissions of `/certs/client/..data/tls.key` are set to `0440` and the ownership is `root:vault`
- I tracked this down to **precisely one setting in the initContainer YAML**:

```
   securityContext:
     fsGroup: 1000
```

Commenting that out lets the user specified configuration of mode bits (and potentially ownership) take precedence.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.16.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Rancher
- bank-vaults version (e.g. 0.4.17): `helm install --namespace automation vault-operator banzaicloud-stable/vault-operator --version 0.5.6 --set image.tag=0.6.3`
- Install method (e.g. helm or static manifests): `helm install --namespace automation vault-operator banzaicloud-stable/vault-operator --version 0.5.6 --set image.tag=0.6.3`
- Logs from the misbehaving component (and any other relevant logs): Reproduced above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: As defined above (put important parts above, it is difficult to redact enough without rewriting a new CR).

/kind bug
