### ISSUE TITLE
Multi-tenant global and local secrets

### ISSUE THREAD

**Issue by TomaszKlosinski** [banzaicloud/bank-vaults#811]
Hi, I'm trying to set up a transit vault in a way that I can have local (namespace) secrets, and global secrets (from central instance in another namespace).  My idea is that I'd keep namespace-specific secrets in local vault instance, and global secrets in central vault instance.

Initially, I thought about connecting with annotations to two vault instances, but I think webhook doesn't support this case. Then I've decided to try transit. 

So, for example, let's say I have one app in my-app-dev environment (namespace) and the same app in my-app-stage environment (namespace). And both of them access the secrets the same way: 
```
        env:
        - name: MYSQ_USER
          value: vault:secret/data/global/mysql#MYSQL_USER
        - name: MYSQL_PASS
          value: vault:secret/data/local/mysql#MYSQL_PASS
``` 

I was hoping that with transit, I can access local secret in namespace vault instance and global secret in central vault instance, but I'm not sure how to configure this. This way my-app-dev and my-app-stage could have two different MYSQL_PASS secrets.

It seems to me that I can either set the flow like:
```
secret/data/key1 --(transit)--> transit/data/key1 (which will make all local secrets the same on all environments)
```
or:
```
secret/data/key1 --(transit)--> transit/$NAMESPACE/key1 (which will make all local secrets different, but there'll be no global secrets)
```

Is there a way to implement this? Maybe transit is not the right thing to achieve this?

PS. I'm not sure if this is the right place to ask this question. sorry, if I should ask somewhere else.
