### ISSUE TITLE
Feature request: Provide install manifests

### ISSUE THREAD

**Issue by lukasmrtvy** [banzaicloud/bank-vaults#849]
**Is your feature request related to a problem? Please describe.**
Would be nice to provide also raw install manifests for deploying operator and webhook. I noticed that ( for example ) https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/operator-rbac.yaml is older than manifest generated from current stable helm chart. ( missing permisions to certain resources.
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: TEMPLATED-vault-operator
  labels:
    helm.sh/chart: vault-operator-0.6.4
rules:
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - deployments/finalizers
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - get
  - create
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - update
  - list
  - get
  - create
  - watch

```
that produce errors in bank-vault operator...
```
{"level":"info","ts":1578912442.7281973,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"vault-controller","source":"kind source: /, Kind="}
E0113 10:47:22.729931       1 event.go:237] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vault-operator-lock.15e96c80503d6e5e", GenerateName:"", Namespace:"bank-vaults", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"ConfigMap", Namespace:"bank-vaults", Name:"vault-operator-lock", UID:"250d19d2-35f1-11ea-a2db-8e7aefea2c4e", APIVersion:"v1", ResourceVersion:"8229016", FieldPath:""}, Reason:"LeaderElection", Message:"vault-operator-5c94c7c95d-q74d7_192607d3-a38b-49f8-945f-ec64fb953f23 became leader", Source:v1.EventSource{Component:"vault-operator-5c94c7c95d-q74d7_192607d3-a38b-49f8-945f-ec64fb953f23", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf7f308eab62aa5e, ext:22106309469, loc:(*time.Location)(0x2689ae0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf7f308eab62aa5e, ext:22106309469, loc:(*time.Location)(0x2689ae0)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:serviceaccount:bank-vaults:vault-operator" cannot create resource "events" in API group "" in the namespace "bank-vaults"' (will not retry!)
```

**Describe the solution you'd like**
Something like `helm template --repo http://kubernetes-charts.banzaicloud.com/branch/master vault-operator --name-template "TEMPLATED"` would be good aproach for github assets and https://github.com/banzaicloud/bank-vaults/tree/master/operator/deploy should contain only CRD examples to not confuse users.
