### ISSUE TITLE
Operator failed to create Vault without TLS

### ISSUE THREAD

**Issue by tomerleib** [banzaicloud/bank-vaults#851]
**Describe the bug**:
According to this https://github.com/banzaicloud/bank-vaults/blob/9dcae5a5c1f77f98b9171132e0b7f24a1ccab35c/operator/deploy/cr.yaml#L104 if one wishes to have Vault running in an unsecured environment, he should set `tls_disable: true` and remove the lines for `tls_cert`.
However, when doing it, Vault pod refuse to initialize with the following error:
```
Error initializing listener of type tcp: 'tls_cert_file' must be set
```

If I changed the listener to the following settings:
```yaml
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
```
It will ignore the `tls_disable` and will run Vault in secured environment.

**Expected behavior**:
Vault-Operator should create Vault and successfully initialize it to run in an unsecured environment, eg. `http://vault` instead of `https://vault`.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.16.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): RKE
- bank-vaults version (e.g. 0.4.17): latest
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): `Error initializing listener of type tcp: 'tls_cert_file' must be set`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
```

/kind bug
