### ISSUE TITLE
[webhook] secrets webhook doesn't work without command

### ISSUE THREAD

**Issue by wiltonfelix** [banzaicloud/bank-vaults#869]
Hi,

**Describe the bug:**
that problem here is equal that issue #764, my deployment config;

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200" # optional, the address of the Vault service, default values is https://vault:8200
        vault.security.banzaicloud.io/vault-role: "apps_prod_roles" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true" # optional, skip TLS verification of the Vault server certificate
        vault.security.banzaicloud.io/vault-path: "kubernetes" # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
    spec:
      serviceAccountName: apps-prod
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/valami/aws#AWS_SECRET_ACCESS_KEY
```

**My app conteiner logs and exec command**
```
vault-test-565fbfbfc-gc9lr                                        1/1     Running       0          15s
[will@unknown test-projet]$ kubectl logs vault-test-565fbfbfc-gc9lr -n prod 
time="2020-02-10T16:40:37Z" level=info msg="Received new Vault token"
time="2020-02-10T16:40:37Z" level=info msg="Initial Vault token arrived"
s3cr3t
going to sleep...
[will@unknown test-projet]$ kubectl exec -ti vault-test-565fbfbfc-gc9lr sh -n prod 
/ # env |grep aws
AWS_SECRET_ACCESS_KEY=vault:secret/data/valami/aws#AWS_SECRET_ACCESS_KEY
```
**OBS**: Look the log of conteiner its working, but after kubectl exec -ti pod sh and run env inside conteiner the value of the secret is a string.

**Logs webhook**
```
time="2020-02-09T22:15:13Z" level=info msg="found image nginx:stable in cache"
time="2020-02-09T22:15:13Z" level=info msg="found image nginx:stable in cache"
time="2020-02-10T14:43:22Z" level=info msg="found image nginx:stable in cache"
time="2020-02-10T14:43:26Z" level=info msg="found image nginx:stable in cache"
time="2020-02-10T14:43:29Z" level=info msg="found image nginx:stable in cache"
time="2020-02-10T14:50:56Z" level=info msg="found no credentials for registry https://index.docker.io, assuming it is public"
time="2020-02-10T14:50:56Z" level=info msg="I'm using registry https://index.docker.io"
2020/02/10 14:50:56 registry.manifest.get url=https://index.docker.io/v2/library/alpine/manifests/latest repository=library/alpine reference=latest
2020/02/10 14:50:56 registry.blob.download url=https://index.docker.io/v2/library/alpine/blobs/sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a repository=library/alpine digest=sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a
time="2020-02-10T14:53:41Z" level=info msg="found no credentials for registry https://index.docker.io, assuming it is public"
time="2020-02-10T14:53:41Z" level=info msg="I'm using registry https://index.docker.io"
2020/02/10 14:53:41 registry.manifest.get url=https://index.docker.io/v2/library/alpine/manifests/latest repository=library/alpine reference=latest
2020/02/10 14:53:41 registry.blob.download url=https://index.docker.io/v2/library/alpine/blobs/sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a repository=library/alpine digest=sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a
```

**Expected behaviour:**
i expected vault-webhook to inject the secrets in my container,

Environment details:

Kubernetes version: 1.14.8-gke.33
on prem cluster
vault-secrets-webhook v0.8.0
vault 1.3.1

@bonifaido I think your merge #779 not is that problem here, I thank you so much.

/kind bug

**Comment by wiltonfelix** [comment]
So i need create all deployments with  command: ["sh", "-c", "source $secret name here" to solution this problem?

**Comment by wiltonfelix** [comment]
**debug logs webhook**

```
time="2020-02-10T23:04:43Z" level=debug msg="Successfully appended pod init containers to spec" app=vault-secrets-webhook
time="2020-02-10T23:04:43Z" level=debug msg="Add generic volumes to podspec" app=vault-secrets-webhook
time="2020-02-10T23:04:43Z" level=debug msg="Add vault agent volumes to podspec" app=vault-secrets-webhook
time="2020-02-10T23:04:43Z" level=debug msg="Successfully appended pod spec volumes" app=vault-secrets-webhook
time="2020-02-10T23:04:43Z" level=debug msg="json patch for request b968bdcf-4c59-11ea-ab84-42010a8e016d: [{\"op\":\"add\",\"path\":\"/spec/initContainers\",\"value\":[{\"command\":[\"vault\",\"agent\",\"-config=/vault/agent/config.hcl\"],\"env\":[{\"name\":\"VAULT_ADDR\",\"value\":\"https://vault.taki.com.vc\"},{\"name\":\"VAULT_SKIP_VERIFY\",\"value\":\"true\"}],\"image\":\"vault:1.3.1\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"vault-agent\",\"resources\":{\"limits\":{\"cpu\":\"50m\",\"memory\":\"64Mi\"}},\"securityContext\":{\"allowPrivilegeEscalation\":false,\"runAsUser\":100},\"volumeMounts\":[{\"mountPath\":\"/vault/\",\"name\":\"vault-env\"},{\"mountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\",\"name\":\"apps-prod-token-sjsjz\",\"readOnly\":true},{\"mountPath\":\"/vault/agent/\",\"name\":\"vault-agent-config\"}]},{\"command\":[\"sh\",\"-c\",\"cp /usr/local/bin/vault-env /vault/\"],\"image\":\"banzaicloud/vault-env:0.8.0\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"copy-vault-env\",\"resources\":{\"limits\":{\"cpu\":\"50m\",\"memory\":\"64Mi\"}},\"securityContext\":{\"allowPrivilegeEscalation\":false},\"volumeMounts\":[{\"mountPath\":\"/vault/\",\"name\":\"vault-env\"}]}]},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_TOKEN_FILE\",\"value\":\"/vault/.vault-token\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_JSON_LOG\",\"value\":\"false\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_ENV_PASSTHROUGH\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_IGNORE_MISSING_SECRETS\",\"value\":\"false\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_ROLE\",\"value\":\"apps_prod_roles\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_PATH\",\"value\":\"kubernetes\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_SKIP_VERIFY\",\"value\":\"true\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/env/1\",\"value\":{\"name\":\"VAULT_ADDR\",\"value\":\"https://vault.taki.com.vc\"}},{\"op\":\"add\",\"path\":\"/spec/containers/0/volumeMounts/1\",\"value\":{\"mountPath\":\"/vault/\",\"name\":\"vault-env\"}},{\"op\":\"remove\",\"path\":\"/spec/containers/0/command/2\"},{\"op\":\"remove\",\"path\":\"/spec/containers/0/command/1\"},{\"op\":\"replace\",\"path\":\"/spec/containers/0/command/0\",\"value\":\"/vault/vault-env\"},{\"op\":\"add\",\"path\":\"/spec/containers/0/args\",\"value\":[\"sh\",\"-c\",\"echo $WILTON \\u0026\\u0026 echo going to sleep... \\u0026\\u0026 sleep 10000\"]},{\"op\":\"add\",\"path\":\"/spec/volumes/1\",\"value\":{\"emptyDir\":{\"medium\":\"Memory\"},\"name\":\"vault-env\"}},{\"op\":\"add\",\"path\":\"/spec/volumes/2\",\"value\":{\"configMap\":{\"name\":\"vault-test-vault-agent-config\"},\"name\":\"vault-agent-config\"}}]" app=vault-secrets-webhook
```

**Comment by wiltonfelix** [comment]
**my values.yaml and command run to install webhook**

```
# Default values for vault-secrets-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

debug: false

certificate:
    generate: true
    server:
        tls:
            crt:
            key:
    ca:
        crt:
image:
  repository: banzaicloud/vault-secrets-webhook
  tag: 0.8.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []

service:
  name: vault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443

env:
  VAULT_IMAGE: vault:1.3.1
  VAULT_ENV_IMAGE: banzaicloud/vault-env:0.8.0
  # VAULT_CAPATH: /vault/tls
  # used when the pod that should get secret injected does not specify
  # an imagePullSecret
  # DEFAULT_IMAGE_PULL_SECRET:
  # DEFAULT_IMAGE_PULL_SECRET_NAMESPACE:

metrics:
  enabled: false
  port: 8443
  serviceMonitor:
    enabled: false
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

volumes: []
# - name: vault-tls
#   secret:
#     secretName: vault-tls

volumeMounts: []
# - name: vault-tls
#   mountPath: /vault/tls

podAnnotations: {}

labels: {}
  #  team: 

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector:
  environment: prod

tolerations: []

affinity: {}

## Assign a PriorityClassName to pods if set
priorityClassName: ""

rbac:
  enabled: true
  psp:
    enabled: false

# This can cause issues when used with Helm, so it is not enabled by default
configMapMutation: false

configmapFailurePolicy: Ignore

podsFailurePolicy: Fail

secretsFailurePolicy: Fail

apiSideEffectValue: NoneOnDryRun

namespaceSelector:
  matchExpressions:
  - key: name
    operator: NotIn
    values:
    - kube-system
  # matchLabels:
  #   vault-injection: enabled

# In case of the K8s cluster version is above 1.15 objectSelector is usable
objectSelector: {}
  # matchExpressions:
  # - key: security.banzaicloud.io/mutate
  #   operator: NotIn
  #   values:
  #   - skip

podDisruptionBudget:
  enabled: false
  minAvailable: 1
```
**command**

```
helm install --name prod-integration --namespace prod -f values.yaml --set env.VAULT_ADDR=https://vault-teami:8200 .
```

**Comment by bonifaido** [comment]
Hi @wiltonfelix,

> Look the log of conteiner its working, but after kubectl exec -ti pod sh and run env inside conteiner the value of the secret is a string.

This is the expected behavior, only your application process will see the actual secret. From the [blog](https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/):

> Our solution is particularly lightweight and uses only existing Kubernetes constructs like annotations and environment variables. No confidential data ever persists on the disk - not even temporarily - or in etcd. All secrets are stored in memory, and only visible to the process that requests them. If you want to make this solution even more robust, you can disable kubectl exec-ing in running containers. If you do so, no one will be able to hijack injected environment variables from a process.

**Comment by wiltonfelix** [comment]
Hi @bonifaido thank you, after test an application in react i get that error on webhook and event k8s:

**logs webhook vault**

```
2020/02/11 14:51:01 registry.manifest.get url=https://gcr.io/v2/project/manifests/v1.0.3 repository=gcp-repo/application reference=v1.0.3
time="2020-02-11T14:51:01Z" level=error msg="admission webhook error: cannot download manifest for image: Get https://gcr.io/v2/project/manifests/v1.0.3: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\"
```
**logs kubernetes event**
```
Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": an error on the server ("{\"response\":{\"uid\":\"b90c9d99-4cd3-11ea-ab84-42010a8e016d\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"cannot download manifest for image: Get https://gcr.io/v2/project/application/manifests/latest: http: non-successful response (status=401 body=\\\"{\\\\\\\"errors\\\\\\\":[{\\\\\\\"code\\\\\\\":\\\\\\\"UNAUTHORIZED\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"You don't have the needed permissions to perform this operation, and you may have invalid credentials.
```

**Solution**

```
env:
  VAULT_IMAGE: vault:1.3.1
  VAULT_ENV_IMAGE: banzaicloud/vault-env:0.8.0
  # VAULT_CAPATH: /vault/tls
  # used when the pod that should get secret injected does not specify
  # an imagePullSecret
  DEFAULT_IMAGE_PULL_SECRET: secret with service account
  DEFAULT_IMAGE_PULL_SECRET_NAMESPACE: prod

```
