### ISSUE TITLE
permission denied : Multi tenant partitioning base on namespace and role

### ISSUE THREAD

**Issue by sparqueur** [banzaicloud/bank-vaults#877]
# Use case

I am trying to perform mutli tenant partitionning.

Each tenant has it's own kubernetes names space.
They all share 1 vault instance.

# Example

namespaces :
- app1 : Tenant 1 namespace
- app2 : Tenant 2 namespace
- test-vaut : Vault namespace

vault secrets :
- secrets/data/app1/* : Tenant 1 secrets
- secrets/data/app2/* : Tenant 2 secrets

app1 should have access to secrets/data/app1/*
app1 should not have acces to secrets/data/app2/*

# Expected working configuration

vault.yaml
```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: test-vault
spec:
  size: 1
  image: vault:1.2.3
  bankVaultsImage: banzaicloud/bank-vaults:0.9.0

  # Common annotations for all created resources
  annotations:
    common/annotation: "true"
  
  # Vault Pods , Services and TLS Secret annotations
  vaultAnnotations:
    type/instance: "vault"
  
  # Vault Configurer Pods and Services annotations
  vaultConfigurerAnnotations:
    type/instance: "vaultconfigurer"

  # Vault Pods , Services and TLS Secret labels
  vaultLabels:
    example.com/log-format: "json"

  # Vault Configurer Pods and Services labels
  vaultConfigurerLabels:
    example.com/log-format: "string"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  serviceType: ClusterIP

  # Request an Ingress controller with the default configuration
  ingress:
    # Specify Ingress object annotations here, if TLS is enabled (which is by default)
    # the operator will add NGINX, Traefik and HAProxy Ingress compatible annotations
    # to support TLS backends
    annotations:
    # Override the default Ingress specification here
    # This follows the same format as the standard Kubernetes Ingress
    # See: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ingressspec-v1beta1-extensions
    spec: {}

  # Use local disk to store Vault file data, see config section.
  volumes:
    - name: vault-file
      emptyDir: {}

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces:
    - app1
    - app2

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: test-vault

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      file:
        path: "${ .Env.VAULT_STORAGE_FILE }" # An example how Vault config environment interpolation can be used
    listener:
      tcp:
        address: "0.0.0.0:8200"
        # Uncommenting the following line and deleting tls_cert_file and tls_key_file disables TLS
        # tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: app1
        rules: path "secret/data/app1/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
            }
      - name: app2
        rules: path "secret/data/app2/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
            }

    auth:
      - type: kubernetes
        roles:
        #- name: default
        #  bound_service_account_names: ["default", "vault", "test-vault-vault-secrets-webhook" ]
        #  bound_service_account_namespaces: [ "test-vault", "app1", "app2" ]
        #  policies: ["allow_secrets"]
        #  ttl: 1h
        - name: app1
          bound_service_account_names: [ "default", "vault", "test-vault-vault-secrets-webhook" ]
          bound_service_account_namespaces: [ "test-vault", "app1" ]
          policies: [ "app1" ]
          ttl: 1h
        #- name: app2
        #  bound_service_account_names: [ "default", "vault", "test-vault-vault-secrets-webhook" ]
        #  bound_service_account_namespaces: [ "test-vault", "app2" ]
        #  policies: [ "app2" ]
        #  ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/data/app1
        data:
          data:
            APP_SECRET: APP1_VALUE
      - type: kv
        path: secret/data/app2
        data:
          data:
            APP_SECRET: APP2_VALUE

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
    - name: VAULT_STORAGE_FILE
      value: "/vault/file"

  # Marks presence of Istio, which influences things like port namings
  istioEnabled: false
```

app1.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.test-vault.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-role: "app1"
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $APP_SECRET && echo going to sleep... && sleep 10000"]
        env:
        - name: APP_SECRET
          value: "vault:secret/data/app1#APP_SECRET"

```

app1 logs
```
time="2020-02-14T14:26:35Z" level=info msg="Received new Vault token"
time="2020-02-14T14:26:35Z" level=info msg="Initial Vault token arrived"
time="2020-02-14T14:26:35Z" level=fatal msg="failed to read secret from path: secret/data/app1 Error making API request.\n\nURL: GET https://vault.test-vault.svc.cluster.local:8200/v1/secret/data/app1?version=-1\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n" app=vault-env
```

# Working example without partioning

vault.yaml
```yaml
...
    auth:
      - type: kubernetes
        roles:
        - name: default
          bound_service_account_names: ["default", "vault", "test-vault-vault-secrets-webhook" ]
          bound_service_account_namespaces: [ "test-vault", "app1", "app2" ]
          policies: ["allow_secrets"]
          ttl: 1h
        #- name: app1
        #  bound_service_account_names: [ "default", "vault", "test-vault-vault-secrets-webhook" ]
        #  bound_service_account_namespaces: [ "test-vault", "app1" ]
        #  policies: [ "app1" ]
        #  ttl: 1h
...
```

app1.yaml
```yaml
...
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.test-vault.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        #vault.security.banzaicloud.io/vault-role: "app1"
...
```

app1 logs
```
time="2020-02-14T14:37:14Z" level=info msg="Failed to request new Vault token Error making API request.\n\nURL: PUT https://vault.test-vault.svc.cluster.local:8200/v1/auth/kubernetes/login\nCode: 400. Errors:\n\n* missing client token"
time="2020-02-14T14:37:15Z" level=info msg="Failed to request new Vault token Error making API request.\n\nURL: PUT https://vault.test-vault.svc.cluster.local:8200/v1/auth/kubernetes/login\nCode: 400. Errors:\n\n* missing client token"
time="2020-02-14T14:37:16Z" level=info msg="Received new Vault token"
time="2020-02-14T14:37:16Z" level=info msg="Initial Vault token arrived"
APP1_VALUE
going to sleep...
```

# Test n°2

vault.yaml
```yaml
...
    auth:
      - type: kubernetes
        roles:
        - name: default
          bound_service_account_names: ["default", "vault", "test-vault-vault-secrets-webhook" ]
          bound_service_account_namespaces: [ "test-vault", "app1", "app2" ]
          policies: ["app1"] # app1 only
          ttl: 1h
        #- name: app1
        #  bound_service_account_names: [ "default", "vault", "test-vault-vault-secrets-webhook" ]
        #  bound_service_account_namespaces: [ "test-vault", "app1" ]
        #  policies: [ "app1" ]
        #  ttl: 1h
...
```

app1.yaml
```yaml
...
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.test-vault.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        #vault.security.banzaicloud.io/vault-role: "app1"
...
```

app1 logs
```
time="2020-02-14T14:43:17Z" level=info msg="Received new Vault token"
time="2020-02-14T14:43:17Z" level=info msg="Initial Vault token arrived"
time="2020-02-14T14:43:17Z" level=info msg="Renewed Vault Token"
time="2020-02-14T14:43:17Z" level=fatal msg="failed to read secret from path: secret/data/app1 Error making API request.\n\nURL: GET https://vault.test-vault.svc.cluster.local:8200/v1/secret/data/app1?version=-1\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n" app=vault-env
```

# Test3 - Several secrets

vault.yaml
```yaml
...
  externalConfig:
    policies:
      - name: app1
        rules: path "secret/app1/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
            }
      - name: app2
        rules: path "secret/app2/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
            }

    auth:
      - type: kubernetes
        roles:
        - name: app1
          bound_service_account_names: [ "default", "vault", "test-vault-vault-secrets-webhook" ]
          bound_service_account_namespaces: [ "test-vault", "app1" ]
          policies: [ "app1" ]
          ttl: 1h
        - name: app2
          bound_service_account_names: [ "default", "vault", "test-vault-vault-secrets-webhook" ]
          bound_service_account_namespaces: [ "test-vault", "app2" ]
          policies: [ "app2" ]
          ttl: 1h

    secrets:
      - path: secret/app1
        type: kv
        description: General secrets.
        options:
          version: 2
      - path: secret/app2
        type: kv
        description: General secrets.
        options:
          version: 2

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/app1/data/app1
        data:
          data:
            APP_SECRET: APP1_VALUE
      - type: kv
        path: secret/app2/data/app2
        data:
          data:
            APP_SECRET: APP2_VALUE
...
```

app1.yaml
```yaml
...
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.test-vault.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-role: "app1"
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $APP_SECRET && echo going to sleep... && sleep 10000"]
        env:
        - name: APP_SECRET
          value: "vault:secret/app1/data/app1#APP_SECRET"
...
```

app1 logs
```
time="2020-02-14T14:50:48Z" level=info msg="Received new Vault token"
time="2020-02-14T14:50:48Z" level=info msg="Initial Vault token arrived"
time="2020-02-14T14:50:48Z" level=info msg="Renewed Vault Token"
APP1_VALUE
going to sleep...
```

# Conclusion

What am I misunderstanding ?

Is creating multiple secrets the only way to go ?

Thank's in advance

**Comment by bonifaido** [comment]
in the first example this the policy is wrong I think because it allows one level deeper in the path, instead of where the actual secret is relies:
```yaml
- name: app1
        rules: path "secret/data/app1/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
            }
```

vs.

```yaml
startupSecrets:
      - type: kv
        path: secret/data/app1
        data:
          data:
            APP_SECRET: APP1_VALUE
      - type: kv
        path: secret/data/app2
        data:
          data:
            APP_SECRET: APP2_VALUE
```

For this you would need:

```yaml
- name: app1
        rules: path "secret/data/app1" {
            capabilities = ["create", "read", "update"]
            }
- name: app2
        rules: path "secret/data/app2" {
            capabilities = ["create", "read", "update"]
            }
```
