### ISSUE TITLE
Error while injecting Vault Secret using a Kubernetes Secret

### ISSUE THREAD

**Issue by sparqueur** [banzaicloud/bank-vaults#888]
Hello,

I am trying inject a Vault Secret using a Kubernetes Secret as describe in https://banzaicloud.com/docs/bank-vaults/mutating-webhook/

My configuration :
```yaml
    - name: init-keycloak-config
      image: alpine
      command: [ "/bin/sh", "-c" ]
      args:
        - cp -L /keycloak-config-configmap/keycloak.json /keycloak-config/keycloak.json;
          sed -i "s/\${KEYCLOAK-SECRET}/$NEXUS_SECRET/g" /keycloak-config/keycloak.json;
          echo 'aws-secret-key';
          echo $AWS_SECRET_ACCESS_KEY;
          echo 'done'
      env:
      - name: NEXUS_SECRET
        value: {{ include "athenaci.vault.env-secret-path" (list . "shr-keycloak-nexus#NEXUS_SECRET") }}
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-key-secret
            key: AWS_SECRET_ACCESS_KEY
      volumeMounts:
        - mountPath: /keycloak-config
          name: keycloak-config
          readOnly: false
        - mountPath: /keycloak-config-configmap
          name: keycloak-config-configmap
          readOnly: true
```

```yaml
apiVersion: v1
data:
  AWS_SECRET_ACCESS_KEY: dmF1bHQ6c2VjcmV0L2RhdGEvdGVzdC9hdGhlbmEtY2kvc2hyLWtleWNsb2FrLW5leHVzI05FWFVTX1NFQ1JFVA==
kind: Secret
metadata:
  name: aws-key-secret
  namespace: test-nexus
type: Opaque
```

The secret exists in Vault. Here what I get in my log :

```
time="2020-02-21T16:04:48Z" level=info msg="Received new Vault token"
time="2020-02-21T16:04:48Z" level=info msg="Initial Vault token arrived"
aws-secret-key
bin dev etc home keycloak-config keycloak-config-configmap lib media mnt opt proc root run sbin srv sys tmp usr var vault
done
```

Yes, AWS_SECRET_ACCESS_KEY has some kind of `ls` value :-)

**Comment by bonifaido** [comment]
Just checking this, sorry for the delay.

**Comment by bonifaido** [comment]
When you exec into the container what is the value of `echo $AWS_SECRET_ACCESS_KEY`?

**Comment by sparqueur** [comment]
My bad, I should double check my self before disrupting you.
Problem was between the keyboard and the chair :

```yaml
    - name: init-keycloak-config
      image: alpine
      command: [ "/bin/sh", "-c" ]
      args:
        - cp -L /keycloak-config-configmap/keycloak.json /keycloak-config/keycloak.json;
          sed -i "s/\${KEYCLOAK-SECRET}/$AWS_SECRET_ACCESS_KEY/g" /keycloak-config/keycloak.json;
          cat /keycloak-config/keycloak.json;
          echo "$AWS_SECRET_ACCESS_KEY"; ==> GOOD VALUE
          echo $AWS_SECRET_ACCESS_KEY; ==> WRONG VALUE
      env:
      - name: NEXUS_SECRET
        value: {{ include "athenaci.vault.env-secret-path" (list . "shr-keycloak-nexus#NEXUS_SECRET") }}
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-key-secret
            key: AWS_SECRET_ACCESS_KEY
```
