### ISSUE TITLE
vault-env in distroless containers

### ISSUE THREAD

**Issue by tkatrichenko** [banzaicloud/bank-vaults#903]
I'm trying to run my applications using distroless docker images (e.g. from Google https://github.com/GoogleContainerTools/distroless/tree/master/java). The Java application uses Spring to connect to DB and it needs credentials stored in Vault. 

I tried to use the solution with injecting secrets from [here](https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/)
```
        env:
        - name: DB_USERNAME
          value: vault:secret/postgresql#username
        - name: DB_PASSWORD
          value: vault:secret/postgresql#password
```
It worked on the alpine based image but fails on distroless with the error:
```
level=fatal msg="binary not found /bin/sh" app=vault-env
```
So, I'm wondering is it possible to use the solution from Banzaicloud on distroless images?
  
**Environment details**:
- Kubernetes version 1.14:
- Cloud-provider/provisioner IBM Cloud IKS:

/kind bug

**Comment by bonifaido** [comment]
Hi @tkatrichenko,

How does your deployment look like and your Dockerfile (if you have any)? Just asking because of the possible entrypoint (command) and cmd (args) definitions.

**Comment by tkatrichenko** [comment]
Hi @bonifaido , thanks for the answer

My Dockerfile is
```
FROM gcr.io/distroless/java:11

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS=""

ADD target/*.jar app.jar

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005", "-jar", "app.jar"]
```
And my deployment looks like this
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://<VAULT_IP>:8200"
        vault.security.banzaicloud.io/vault-role: "<VAULT_ROLE>"
    spec:
      containers:
      - name: "myapp-distroless"
        image: my_image:distroless
        env:
        - name: DB_USERNAME
          value: vault:secret/postgresql#username
        - name: DB_PASSWORD
          value: vault:secret/postgresql#password
```
