### ISSUE TITLE
Webhook unable to mutate Secret when using external Vault with Vault-namespaces

### ISSUE THREAD

**Issue by wmene** [banzaicloud/bank-vaults#917]
**Describe the bug**:
Our organization uses Vault Enterprise, and our team was assigned a Vault namespace.
We used the helm chart to deploy the Vault webhook to our K8S cluster, and we are able to mutate Pods and grab values from our Vault instance in our datacenter.  As an example we are able to set the Pod's environment variable with this value from Vault:
`vault:kv/data/parent/child/gc#SOME_VAR`

The key to making this work was to set the VAULT_NAMESPACE environment variable in the POD:
```
kind: Deployment
...
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://external-vault.com:443"
...
        env:
        - name: VAULT_NAMESPACE
          value: Foo/Bar
        - name: SOME_VAR
          value: vault:kv/data/parent/child/gc#SOME_VAR
```

We're trying to mutate a K8S secret to read the same value
```
apiVersion: v1
kind: Secret
metadata:
  name: remote-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://external-vault.com:443"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
type: Opaque   
data:
  # value below is vault:kv/data/parent/child/gc#SOME_VAR base64 encoded
  vaultdata: dmF1bHQ6a3YvZGF0YS9wYXJlbnQvY2hpbGQvZ2MjU09NRV9WQVIK
```
I tried to use this secret in a Deployment
```
kind: Deployment
...
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://external-vault.com:443"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
...
      env:
        - name: VAULT_NAMESPACE
          value: Foo/Bar
        - name: DEBUG
          value: "true"
        - name: FROM_SECRET
          valueFrom:
            secretKeyRef:
              name: remote-secret
              key: vaultdata
```

However, we get the following error from the Pod
```
$ kubectl logs pod-12345
time="2020-03-11T19:39:42Z" level=info msg="Received new Vault token"
time="2020-03-11T19:39:42Z" level=info msg="Initial Vault token arrived"
time="2020-03-11T19:39:42Z" level=info msg="Renewed Vault Token"
time="2020-03-11T19:39:42Z" level=fatal msg="key not found: SOME_VAR\n" app=vault-env
```

**Expected behaviour**:
The secret from the external Vault instance from that particular namespace should be fetched.

**Steps to reproduce the bug**:
See above

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.14
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): banzaicloud/vault-secrets-webhook 0.9.0 image
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
