### ISSUE TITLE
etcd-cluster not deployed when combined with non-ha storage

### ISSUE THREAD

**Issue by oschira** [banzaicloud/bank-vaults#923]
**Describe the bug**:
When combining etcd as ha storage with another non-ha storage, the etcd cluster is not deployed.

**Expected behaviour**:
The etcd cluster should be deployed.

**Steps to reproduce the bug**:
Deploy both a non-ha storage like aws s3 and etcd. Here is the relevant part of the configuration:
```yaml
  config:
    storage:
      s3:
        region: "eu-west-1"
        bucket: "my-vault"
    ha_storage:
      etcd:
        address: https://etcd-cluster:2379
        etcd_api: "v3"
```

**Additional context**:
- `storage` and `ha_storage` described in vault documentation: https://www.vaultproject.io/docs/configuration/#inlinecode-ha_storage
- support for `ha_storage` has been added by this commit: https://github.com/banzaicloud/bank-vaults/commit/945bc5aa866fae404f2f8730e2322c5b9d414427
- but not used when checking the need to create an etcd cluster:
  - https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L275
  - https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L1141 

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.14.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 0.9.0
- Install method (e.g. helm or static manifests): helm using vault-operator 0.6.8
- Logs from the misbehaving component (and any other relevant logs):
```bash
$ kubectl logs pod/vault-0 vault
telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
Error initializing HA storage of type etcd: failed to get etcd API version: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd-cluster on 172.20.0.10:53: no such host
```
```bash
$ kubectl get all
NAME                                                                  READY   STATUS             RESTARTS   AGE
pod/vault-0                                                           1/3     CrashLoopBackOff   18         23m
pod/vault-1                                                           1/3     CrashLoopBackOff   18         23m
pod/vault-configurer-6d9b5bb4f7-tvkfw                                 1/1     Running            0          23m
pod/vault-operator-5654fb6db7-8fxf2                                   1/1     Running            0          24m
pod/vault-operator-etcd-operator-etcd-backup-operator-55fb5555rdf9t   1/1     Running            0          24m
pod/vault-operator-etcd-operator-etcd-operator-5d67b57d5b-h2d8z       1/1     Running            0          24m
pod/vault-operator-etcd-operator-etcd-restore-operator-6cbb6fbv6blx   1/1     Running            0          24m

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
service/etcd-restore-operator   ClusterIP   172.20.158.231   <none>        19999/TCP                             24m
service/vault                   ClusterIP   172.20.243.206   <none>        8200/TCP,8201/TCP,9091/TCP,9102/TCP   23m
service/vault-0                 ClusterIP   172.20.71.158    <none>        8200/TCP,8201/TCP,9091/TCP            23m
service/vault-1                 ClusterIP   172.20.55.32     <none>        8200/TCP,8201/TCP,9091/TCP            23m
service/vault-configurer        ClusterIP   172.20.174.240   <none>        9091/TCP                              23m
service/vault-operator          ClusterIP   172.20.96.162    <none>        80/TCP,8383/TCP                       24m

NAME                                                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/vault-configurer                                     1/1     1            1           23m
deployment.apps/vault-operator                                       1/1     1            1           24m
deployment.apps/vault-operator-etcd-operator-etcd-backup-operator    1/1     1            1           24m
deployment.apps/vault-operator-etcd-operator-etcd-operator           1/1     1            1           24m
deployment.apps/vault-operator-etcd-operator-etcd-restore-operator   1/1     1            1           24m

NAME                                                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/vault-configurer-6d9b5bb4f7                                     1         1         1       23m
replicaset.apps/vault-operator-5654fb6db7                                       1         1         1       24m
replicaset.apps/vault-operator-etcd-operator-etcd-backup-operator-55fb55555c    1         1         1       24m
replicaset.apps/vault-operator-etcd-operator-etcd-operator-5d67b57d5b           1         1         1       24m
replicaset.apps/vault-operator-etcd-operator-etcd-restore-operator-6cbb6fbb54   1         1         1       24m

NAME                     READY   AGE
statefulset.apps/vault   0/2     23m
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 2
  image: vault:1.3.1
  bankVaultsImage: banzaicloud/bank-vaults:latest

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Specify how many nodes you would like to have in your etcd cluster
  # NOTE: -1 disables automatic etcd provisioning
  etcdSize: 1

  # This option allows you to annotate the ETCD Cluster that Vault Operator creates.
  # It's specifically to annotate the ETCD Cluster as 'clusterwide' for a cluster wide
  # ETCD Operator, however it can be used to set any arbitrary annotations on the ETCD Cluster.
  etcdAnnotations:
    etcd.database.coreos.com/scope: clusterwide

  etcdVersion: "3.3.17"

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces:
    - "vswh"

  # Insted of credentialsConfig one can use IAM instance profiles, or kube2iam for example:
  annotations:
    iam.amazonaws.com/role: "role-arn..."

  # Describe where you would like to store the Vault unseal keys and root token
  # in S3 encrypted with KMS.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      preFlightChecks: true
    aws:
      kmsKeyId: "94c836b9-4907-47a7-928e-85d5d5518eff"
      kmsRegion: "us-east-1"
      s3Bucket: "my-vault"
      s3Region: "us-east-1"

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      s3:
        region: "us-east-1"
        bucket: "my-vault"
    ha_storage:
      etcd:
        address: https://etcd-cluster:2379
        # NOTE: specifiying the etcd API version is strongly encouraged,
        # since etcd version 3.4 doesn't offer v2 version by default anymore.
        # https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md
        etcd_api: "v3"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.default:8200
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["default", "vswh"]
            policies: allow_secrets
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID: secretId
            AWS_SECRET_ACCESS_KEY: s3cr3t
      - type: kv
        path: secret/data/dockerrepo
        data:
          data:
            DOCKER_REPO_USER: dockerrepouser
            DOCKER_REPO_PASSWORD: dockerrepopassword
      - type: kv
        path: secret/data/mysql
        data:
          data:
            MYSQL_ROOT_PASSWORD: s3cr3t
            MYSQL_PASSWORD: 3xtr3ms3cr3t

```

I would be happy to try fixing this issue by providing a PR.

/kind bug
