### ISSUE TITLE
[vault-secrets-webhook] index out of range [5] when 4 volumeMounts use the same Secret

### ISSUE THREAD

**Issue by joshuasimon-taulia** [banzaicloud/bank-vaults#939]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
When an object contains 4 or more `volumeMounts` which pull from the same k8s `Secret` and aren't in sequential order, the secrets are not injected into the `Deployment` object, and the below error is observed in the vault-secrets-webhook pod logs.

**Expected behaviour**:
The secrets should inject into the env var correctly.

**Steps to reproduce the bug**:
Create a k8s `deployment` which mounts 4 `volumeMounts` from the same `Secret`. ie:
```yaml
        volumeMounts:
        - mountPath: /mnt/generator
          name: generate-certs
        - mountPath: /mnt/certs
          name: certs
        - mountPath: /mnt/ca  # uses the 'certs' secret
          name: ca
        - mountPath: /etc/shared
          name: config-dir
        - mountPath: /mnt/sso  # uses the 'certs' secret
          name: sso-certs
        - mountPath: /mnt/global  # uses the 'certs' secret
          name: global-truststore
        - name: "wildcard"  # uses the 'certs' secret
          mountPath: "/mnt/wildcard"
...
      volumes:
      - name: "config-dir"
        emptyDir: {}
      - name: "certs"
        emptyDir: {}
      - name: "ca"
        secret:
          secretName: "certs"
          items:
          - key: ca-pem-contents
            path: "ca.pem"
          - key: ca-key-contents
            path: "ca.key"
      - name: "global-truststore"
        secret:
          secretName: "certs"
          items:
          - key: global-truststore-contents
            path: "global-truststore.jks"
      - name: "generate-certs"
        configMap:
          name: "generate-certs"
          items:
          - key: "generate-certs"
            path: generate-certs.sh
            mode: 0755
      - name: "sso-certs"
        secret:
          secretName: "certs"
          items:
          - key: idp-contents
            path: "idp-keystore.p12"
          - key: sp-contents
            path: "sp-keystore.p12"
      - name: "wildcard"
        secret:
          secretName: "certs"
          items:
          - key: wildcard
            path: "wildcard.jks"
```
when the volumeMounts which share the same Volume are in sequential order, everything works as expected: ie:
```yaml
        volumeMounts:
        - mountPath: /mnt/generator
          name: generate-certs
        - mountPath: /mnt/certs
          name: certs
        - mountPath: /etc/shared
          name: config-dir
        - mountPath: /mnt/ca  # uses the 'certs' secret
          name: ca
        - mountPath: /mnt/sso  # uses the 'certs' secret
          name: sso-certs
        - mountPath: /mnt/global  # uses the 'certs' secret
          name: global-truststore
        - name: "wildcard"  # uses the 'certs' secret
          mountPath: "/mnt/wildcard"
```

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.14.10-gke.32
- Cloud-provider/provisioner: GKE
- bank-vaults version: 1.0.1
- Install method: helm
- Logs from the misbehaving component:
```
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 2020/04/08 02:58:15 http2: panic serving 192.168.188.58:59716: runtime error: index out of range [5] with length 5
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook goroutine 73289 [running]:
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook net/http.(*http2serverConn).runHandler.func1(0xc00012c6f8, 0xc0006fdf8e, 0xc00054e180)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x16b
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook panic(0x15f8880, 0xc0008ab9e0)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/runtime/panic.go:967 +0x166
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.backtrace(0xc000567400, 0x5, 0x8, 0xc000567a00, 0x8, 0x8, 0xc000474c90, 0x23, 0x4, 0x6, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:327 +0x103d
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.backtrace(0xc000567400, 0x5, 0x8, 0xc000567a00, 0x8, 0x8, 0xc000474c90, 0x23, 0x5, 0x7, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:331 +0x90a
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.backtrace(0xc000567400, 0x5, 0x8, 0xc000567a00, 0x8, 0x8, 0xc000474c90, 0x23, 0x5, 0x8, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:319 +0xae4
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.compareEditDistance(0xc000567400, 0x5, 0x8, 0xc000567a00, 0x8, 0x8, 0xc000474c90, 0x23, 0xc, 0x3, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:302 +0x3b0
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.handleValues(0x1487a00, 0xc0007bafe0, 0x1487a00, 0xc0007bb760, 0xc000474c90, 0x23, 0xc000533200, 0x2e, 0x30, 0xc000533200, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:215 +0x8e0
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.diff(0xc0001f61b0, 0xc000538c00, 0xc0008ab780, 0x16, 0xc000533200, 0x2e, 0x30, 0x400, 0x1, 0x30, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:168 +0x3ff
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.handleValues(0x1520c20, 0xc0001f61b0, 0x1520c20, 0xc000538c00, 0xc0008ab780, 0x16, 0xc000533200, 0x1f, 0x30, 0xc000533200, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:204 +0xd5a
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.handleValues(0x1487a00, 0xc0007bb140, 0x1487a00, 0xc0007bb9c0, 0xc0008ab260, 0x14, 0x24ee800, 0x0, 0x0, 0x24ee800, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:226 +0x7dd
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.diff(0xc0004cd320, 0xc0001f7d40, 0xc000766940, 0x5, 0x24ee800, 0x0, 0x0, 0x400, 0x4, 0x10, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:168 +0x3ff
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.handleValues(0x1520c20, 0xc0004cd320, 0x1520c20, 0xc0001f7d40, 0xc000766940, 0x5, 0x24ee800, 0x0, 0x0, 0xc000010698, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:204 +0xd5a
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.diff(0xc0004cd200, 0xc0004cd230, 0x0, 0x0, 0x24ee800, 0x0, 0x0, 0x0, 0x3500, 0x328c, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:168 +0x3ff
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/appscode/jsonpatch.CreatePatch(0xc000728000, 0x2dbd, 0x3000, 0xc000348a00, 0x328c, 0x3500, 0x0, 0x0, 0x1659de0, 0x16aedc0, ...)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/appscode/jsonpatch@v0.0.0-20180911074601-5af499cf01c8/jsonpatch.go:69 +0x19d
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/slok/kubewebhook/pkg/webhook/mutating.(*staticWebhook).mutatingAdmissionReview(0xc0000832c0, 0x19ebb60, 0xc000552a50, 0xc000552990, 0x1a10a40, 0xc0003cf000, 0x1a10a40, 0xc0003cf800, 0xc0003cf000)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook@v0.3.0/pkg/webhook/mutating/webhook.go:147 +0x188
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/slok/kubewebhook/pkg/webhook/mutating.(*staticWebhook).Review(0xc0000832c0, 0x19ebb60, 0xc000552a50, 0xc000552990, 0x1623400)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook@v0.3.0/pkg/webhook/mutating/webhook.go:123 +0x3b0
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/slok/kubewebhook/pkg/webhook/internal/instrumenting.(*Webhook).Review(0xc000341ef0, 0x19ebb60, 0xc000552a20, 0xc000552990, 0x0)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook@v0.3.0/pkg/webhook/internal/instrumenting/instrumenting.go:42 +0x246
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook github.com/slok/kubewebhook/pkg/http.HandlerFor.func1(0x19e7ba0, 0xc00012c6f8, 0xc0005afe00)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook@v0.3.0/pkg/http/handler.go:64 +0x1e7
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook net/http.HandlerFunc.ServeHTTP(0xc000121ba0, 0x19e7ba0, 0xc00012c6f8, 0xc0005afe00)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:2012 +0x44
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook net/http.(*ServeMux).ServeHTTP(0xc000080940, 0x19e7ba0, 0xc00012c6f8, 0xc0005afe00)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:2387 +0x1a5
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook net/http.serverHandler.ServeHTTP(0xc0001ec1c0, 0x19e7ba0, 0xc00012c6f8, 0xc0005afe00)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:2807 +0xa3
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook net/http.initALPNRequest.ServeHTTP(0x19ebb60, 0xc00029c870, 0xc0003bd180, 0xc0001ec1c0, 0x19e7ba0, 0xc00012c6f8, 0xc0005afe00)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:3381 +0x8d
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook net/http.(*http2serverConn).runHandler(0xc00054e180, 0xc00012c6f8, 0xc0005afe00, 0xc000760f60)
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/h2_bundle.go:5720 +0x8b
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook created by net/http.(*http2serverConn).processHeaders
vault-secrets-webhook-5cf68d948b-hgd87 vault-secrets-webhook 	/usr/local/go/src/net/http/h2_bundle.go:5454 +0x4e1
```
full object example definition:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets-seccontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-secrets-seccontext
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-secrets-seccontext
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        # vault.security.banzaicloud.io/vault-tls-secret: vault-tls
        vault.security.banzaicloud.io/vault-role: "jx"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        # vault.security.banzaicloud.io/vault-agent: "true"
    spec:
      securityContext:
        runAsUser: 1000
      initContainers:
      - name: init-ubuntu
        image: ubuntu
        command:
        - sh
        - '-c'
        - |
          echo "secret: $JASYPT_PASSWORD" > /etc/shared/test1.txt
          cat /etc/shared/test1.txt
          echo $JASYPT_PASSWORD && echo initContainers ready
        env:
        - name: JASYPT_PASSWORD
          value: vault:secret/data/myorg#JASYPT_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /mnt/generator
          name: generate-certs
        - mountPath: /mnt/certs
          name: certs
        - mountPath: /etc/shared
          name: config-dir
        - mountPath: /mnt/ca
          name: ca
        - mountPath: /mnt/sso
          name: sso-certs
        - mountPath: /mnt/global
          name: global-truststore
        - name: "wildcard"
          mountPath: "/mnt/wildcard"
      containers:
      - name: alpine
        image: alpine
        command:
        - sh
        - '-c'
        - |
          echo $JASYPT_PASSWORD && echo going to sleep... && sleep 10000
        env:
        - name: JASYPT_PASSWORD
          value: vault:secret/data/myorg#JASYPT_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: config-dir
          mountPath: /etc/shared
      volumes:
      - name: "config-dir"
        emptyDir: {}
      - name: "certs"
        emptyDir: {}
      - name: "ca"
        secret:
          secretName: "certs"
          items:
          - key: ca-pem-contents
            path: "ca.pem"
          - key: ca-key-contents
            path: "ca.key"
      - name: "global-truststore"
        secret:
          secretName: "certs"
          items:
          - key: global-truststore-contents
            path: "global-truststore.jks"
      - name: "generate-certs"
        configMap:
          name: "generate-certs"
          items:
          - key: "generate-certs"
            path: generate-certs.sh
            mode: 0755
      - name: "sso-certs"
        secret:
          secretName: "certs"
          items:
          - key: idp-contents
            path: "idp-keystore.p12"
          - key: sp-contents
            path: "sp-keystore.p12"
      - name: "wildcard"
        secret:
          secretName: "certs"
          items:
          - key: wildcard
            path: "wildcard.jks"
```
ref #548
/kind bug
