### ISSUE TITLE
rabitMQ secret engine configuration issue

### ISSUE THREAD

**Issue by osnagovskyi** [banzaicloud/bank-vaults#96]
**Describe the bug**
When trying to configure rabbitMQ secret engine using externalConfig values `vault-configurer` container crashes with following error message:
```
panic: interface conversion: interface {} is map[interface {}]interface {}, not []interface {}

goroutine 1 [running]:
github.com/banzaicloud/bank-vaults/pkg/vault.(*vault).configureSecretEngines(0xc4204c0d80, 0x0, 0x0)
	/go/src/github.com/banzaicloud/bank-vaults/pkg/vault/vault.go:509 +0x129d
```
Here's the corresponding section of config:
```
externalConfig:
  secrets:
    - type: rabbitmq
        description: internal-Rabbit
        configuration:
          config:
             connection:
                connection_url: "hostname:15672"
                username: user
                password: password
          roles:
            - name: rolename
               vhosts:
                 - /web:
                      write: "production_.*" 
                      read: "production_.*"
```

**To Reproduce**
Deploy bank-vault using vault [helm-chart](https://github.com/banzaicloud/banzai-charts/tree/master/vault) and use described portion of config to setup rabbitMQ secret engine. 

**Version**
```
vault-configurer:
    Image:         banzaicloud/bank-vaults:latest
    Image ID:      docker-pullable://banzaicloud/bank-vaults@sha256:d76d992a02708d326c1bb117a0f3067c0c96bb2d892557032969100152dd4d2e
```

**Comment by tarokkk** [comment]
@osnagovskyi 

There are some mistakes in your configuration. According to the official [RabbitMQ Secret engine docs](https://www.vaultproject.io/docs/secrets/rabbitmq/index.html) the example configuration should looks like something similar to this:

```
  secrets:
    - type: rabbitmq
      description: internal-Rabbit
      configuration:
        config:
          - name: connection
            connection_uri: "http://hostname:15672"
            username: user
            password: password
        roles:
          - name: prod_role
            vhosts: '{"/web":{"write": "production_.*", "read": "production_.*"}}'
```

Please note that other than structural changes `connection_url` should be `connection_uri` with the proper http scheme.

If you still have troubles let us know!
