### ISSUE TITLE
Gitlab CI pipeline with vault-env / webhook

### ISSUE THREAD

**Issue by wizard580** [banzaicloud/bank-vaults#969]
**Describe the bug**:
I configured gitlab-runner and runner pods to have all annotations required to work with webhook + vault-env injection. Everything is working fine unless pipeline uses services. (https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service)
If I do not use service my job runner pods getting injected /vault/vault-env binary and I can use all secrets available to me. 
If I'm defining services like this:
```
services:
  - docker:18.09-dind
```
my pod start and work but there are no injected vault-env so I can't use secrets.

I found workaround: define service not globally but for steps that really needs it. But if that step will need vaulted secret - this will be the end. No way around AFAIK.

**Expected behaviour**:
All pods with properly crafted env variables should get vount-env injected.

**Steps to reproduce the bug**:
```
services: 
- docker:18.09-dind

variables:
  KUBERNETES_SERVICE_ACCOUNT: gitlab-runner
  LOCAL_AWS_SECRET_ACCESS_KEY: vault:secret/data/accounts/aws_super_secret#AWS_SECRET_ACCESS_KEY

stages:
  - helm_test

helm:VAULT_test:
  stage: helm_test
  image: some-helm-docker-image
  script:
    - ls -la /vault/*
    - /vault/vault-env /bin/bash -c "echo \${LOCAL_AWS_SECRET_ACCESS_KEY}"
```

**Environment details**:
- Kubernetes version v1.15.11
- Cloud-provider AWS
- bank-vaults version 1.1.0:
- Install method: helm + static CR manifest

/kind bug
